import test from 'node:test';import assert from 'node:assert/strict';import {join} from 'node:path';import {tmpdir} from 'node:os';import {rm} from 'node:fs/promises';import {freshPrivateDirectory} from './helpers/private-dir.ts';import {StateStore} from '../src/state/store.ts';import {CollectorHost} from '../src/runtime/collector-service.ts';import {Collector} from '../src/runtime/collector.ts';
import {panelViewStore} from '../src/runtime/panel-views.ts';
async function fixture(t:any){const dir=await freshPrivateDirectory(join(tmpdir(),'prism-poll-'));t.after(()=>rm(dir,{recursive:true,force:true}));const store=new StateStore(dir);await store.write('views',[{tabId:'tab',paneId:'panel',terminalId:'view',targetTerminalId:'native',open:true}]);let now=1000;t.mock.method(Date,'now',()=>now);let snapshots=0,projections=0,viewReads=0;const original=store.read.bind(store);t.mock.method(store,'read',async(name:string)=>{if(name==='views')viewReads++;return original(name);});const snapshot:any={protocol:22,focused_tab_id:'tab',focused_workspace_id:'w',focused_pane_id:'panel',layouts:[],agents:[{terminal_id:'native',pane_id:'agent',tab_id:'tab',workspace_id:'w'}],panes:[{terminal_id:'native',pane_id:'agent',tab_id:'tab',workspace_id:'w'},{terminal_id:'view',pane_id:'panel',tab_id:'tab',workspace_id:'w'}]};const rpc:any={call:async(method:string)=>{assert.equal(method,'session.snapshot');snapshots++;return{snapshot:structuredClone(snapshot)};}};const data:any={sessions:[],updatedAt:1,stale:false,diagnostics:[]};const collector:any={data,revision:1,setVisibleSelections(){},setFocusedOwnerTerminalId(){},dataForView(){projections++;return data;},processOutput:async(_session:any,_target:any,assertVisible:any)=>{await assertVisible();return{owned:true};}};const host=new CollectorHost(collector,store,rpc);const poll=(extra:any={})=>host.request('view.poll',{terminalId:'view',key:'pi:owner',visible:true,subtree:false,expanded:false,...extra});return{host,poll,snapshot,collector,setNow:(n:number)=>now=n,get snapshots(){return snapshots;},get projections(){return projections;},get viewReads(){return viewReads;}};}
test('unchanged view polls reuse one authoritative snapshot and records read and omit dashboard bodies',async t=>{const f=await fixture(t);const first:any=await f.poll();assert.ok(first.snapshot);assert.equal(typeof first.revision,'string');for(let n=0;n<12;n++){const value:any=await f.poll({revision:first.revision,snapshotRevision:first.snapshotRevision});assert.equal(value.unchanged,true);assert.equal(value.data,undefined);assert.equal(value.snapshot,undefined);}assert.equal(f.snapshots,1);assert.equal(f.viewReads,1);assert.equal(f.projections,1);f.setNow(2000);const next:any=await f.poll({revision:first.revision,snapshotRevision:first.snapshotRevision});assert.equal(f.snapshots,2);assert.equal(next.snapshot,undefined,'equal snapshot revisions avoid repeated native metadata');});
test('selection changes return their projection while explicit refresh and process output force current visibility checks',async t=>{const f=await fixture(t);const first:any=await f.poll();const second:any=await f.poll({key:'pi:worker',revision:first.revision,snapshotRevision:first.snapshotRevision});assert.ok(second.data);assert.notEqual(second.revision,first.revision);await f.poll({forceSnapshot:true});assert.equal(f.snapshots,2);f.snapshot.panes=f.snapshot.panes.filter((pane:any)=>pane.terminal_id!=='view');await assert.rejects(f.host.request('process-output',{terminalId:'view',session:'pi:owner',processTarget:{key:'p',owner:'pi:owner'}}),/no longer visible/);assert.equal(f.snapshots,3);});
test('per-revision projections reuse usage and history work without losing independent scopes',()=>{const c=new Collector({rpc:{call:async()=>({})} as any,stateDir:'/unused-pure-projection',settings:{nativeMode:'inspector-only',providerHomes:{},todosEnabled:false,sampleIntervalMs:2000,follow:false,ascii:true,monochrome:true},index:{close(){}} as any,sampler:{sample:async()=>{throw Error('unused');},close:async()=>{}},git:{close(){}} as any});c.data={sessions:[{key:'pi:owner',children:['pi:child'],evidence:{id:'owner',provider:'pi',messages:[],tools:[],goals:[],usage:[{id:'u',kind:'delta',input:10,output:1,includesChildren:false}],availability:'known'}},{key:'pi:child',parentKey:'pi:owner',children:[],evidence:{id:'child',provider:'pi',messages:[],tools:[],goals:[],usage:[{id:'u2',kind:'delta',input:20,output:1,includesChildren:false}],availability:'known'}}] as any,updatedAt:1,stale:false,diagnostics:[]};const first=c.dataForView('pi:owner');assert.equal(c.dataForView('pi:owner'),first);const subtree=c.dataForView('pi:owner',true);assert.notEqual(subtree,first);assert.equal(subtree.sessions[0].usage?.input,30);assert.equal(first.sessions[0].usage?.input,10);c.data.sessions[0].evidence.usage.push({id:'new',kind:'delta',input:5,output:1,includesChildren:false});c.emit('data',c.data);assert.notEqual(c.dataForView('pi:owner'),first);assert.equal(c.dataForView('pi:owner').sessions[0].usage?.input,15);});
test('owner accent follows only the ready live exact focused panel target and clears reused or foreign identities',async()=>{const {focusedPanelOwner}=await import('../src/runtime/collector-service.ts');const record:any={tabId:'tab',paneId:'panel',terminalId:'view',targetTerminalId:'native',open:true,ready:true,pid:process.pid};const snapshot:any={focused_tab_id:'tab',focused_pane_id:'panel',agents:[{pane_id:'agent',terminal_id:'native',tab_id:'tab'}],panes:[{pane_id:'panel',terminal_id:'view',tab_id:'tab'},{pane_id:'agent',terminal_id:'native',tab_id:'tab'}]};assert.equal(focusedPanelOwner([record],snapshot),'native');for(const invalid of [{...record,ready:false},{...record,pid:undefined},{...record,open:false},{...record,terminalId:'reused'}])assert.equal(focusedPanelOwner([invalid],snapshot),undefined);assert.equal(focusedPanelOwner([record],{...snapshot,focused_pane_id:'agent'}),undefined);assert.equal(focusedPanelOwner([record],{...snapshot,focused_tab_id:'other'}),undefined);assert.equal(focusedPanelOwner([record],{...snapshot,panes:[snapshot.panes[0],{...snapshot.panes[1],terminal_id:'replacement'}]}),undefined);});
test('hidden changed revisions send only visibility metadata and resume with full current data',async t=>{const f=await fixture(t);const first:any=await f.poll({visible:false});f.collector.revision=2;const hidden:any=await f.poll({visible:false,revision:first.revision,snapshotRevision:first.snapshotRevision});assert.equal(hidden.data,undefined);assert.equal(hidden.unchanged,true);assert.equal(f.projections,1);const visible:any=await f.poll({visible:true,revision:hidden.revision,snapshotRevision:hidden.snapshotRevision});assert.ok(visible.data);assert.equal(f.projections,2);});
test('a shared snapshot read before newer authoritative inventory cannot roll back its focus',async t=>{
 const f=await fixture(t),readStartedAt=performance.now();const first:any=await f.poll();
 const old=structuredClone(f.snapshot);old.focused_pane_id='agent';
 const rejected:any=await f.host.request('native-snapshot',{snapshot:old,readStartedAt});assert.equal(rejected.observed,false);
 const current:any=await f.poll({revision:first.revision});assert.equal(current.snapshot.focused_pane_id,'panel');assert.equal(current.snapshotRevision,first.snapshotRevision);
});
test('queued pre-sizing shared geometry cannot mark a default sibling custom but a later user resize is saved',async t=>{
 const dir=await freshPrivateDirectory(join(tmpdir(),'prism-snapshot-width-'));t.after(()=>rm(dir,{recursive:true,force:true}));const store=new StateStore(dir);
 const natives=['a','b'].map(pane_id=>({pane_id,terminal_id:'native-'+pane_id,tab_id:'tab'})),panels:any[]=[],ratios=new Map<string,number>();let queued:Promise<any>|undefined;let host:CollectorHost;
 const node=(target:string):any=>{const pane=panels.find(p=>p.target===target);return pane?{type:'split',direction:'right',ratio:ratios.get(target),first:{type:'pane',pane_id:target},second:{type:'pane',pane_id:pane.pane_id}}:{type:'pane',pane_id:target};};
 const snapshot=()=>({protocol:22,agents:[],focused_tab_id:'tab',focused_pane_id:'a',panes:[...natives,...panels],layouts:[{tab_id:'tab',panes:natives.flatMap((native,i)=>{const pane=panels.find(p=>p.target===native.pane_id),width=pane?Math.round(140*ratios.get(native.pane_id)!):140;return[{pane_id:native.pane_id,rect:{x:0,y:i*40,width,height:40}},...pane?[{pane_id:pane.pane_id,rect:{x:width,y:i*40,width:140-width,height:40}}]:[]];}),splits:panels.map(pane=>({id:'split-'+pane.target,direction:'right',ratio:ratios.get(pane.target),rect:{x:0,y:pane.target==='a'?0:40,width:140,height:40}}))}]});
 const rpc:any={call:async(method:string,p:any={})=>{
  if(method==='session.snapshot')return{snapshot:structuredClone(snapshot())};
  if(method==='plugin.pane.open'){const pane={pane_id:'panel-'+p.target_pane_id,terminal_id:'view-'+p.target_pane_id,tab_id:'tab',target:p.target_pane_id};panels.push(pane);ratios.set(pane.target,0.5);return{plugin_pane:{plugin_id:'iob.herdr-prism',entrypoint:'inspector',pane}};}
  if(method==='layout.export'){if(p.pane_id==='panel-b')queued=host.request('native-snapshot',{snapshot:structuredClone(snapshot()),readStartedAt:performance.now()});return{layout:{root:{type:'split',direction:'down',first:node('a'),second:node('b')}}};}
  if(method==='layout.set_split_ratio'){ratios.set(panels.find(pane=>pane.pane_id===p.pane_id).target,p.ratio);return{};}
  throw Error(method);
 }};
 const data:any={sessions:[],stale:false},collector:any={data,revision:1,setVisibleSelections(){},setFocusedOwnerTerminalId(){},dataForView(){return data;}};
 host=new CollectorHost(collector,store,rpc);await host.request('open-view',{targetPaneId:'a'});await host.request('open-view',{targetPaneId:'b'});await queued;
 const sizes=['a','b'].map(id=>panelViewStore(dir,'tab','native-'+id));
 for(const size of sizes)assert.deepEqual(await size.read('panel-size'),{columns:60,custom:false},'programmatic default geometry is not a user preference');
 await host.request('view.poll',{terminalId:'view-b',visible:true,subtree:false,expanded:false});
 for(const size of sizes)assert.equal((await size.read<any>('panel-size')).custom,false,'fresh post-sizing inventory keeps both defaults');
 ratios.set('b',0.5);await host.request('native-snapshot',{snapshot:structuredClone(snapshot()),readStartedAt:performance.now()});
 assert.deepEqual(await sizes[1].read('panel-size'),{columns:70,custom:true},'fresh real split-ratio changes remain persisted');assert.equal((await sizes[0].read<any>('panel-size')).custom,false);
});
test('switching disjoint visible sessions warms CPU and rehydrates each newly observed todo history',async t=>{const dir=await freshPrivateDirectory(join(tmpdir(),'prism-observed-switch-'));t.after(()=>rm(dir,{recursive:true,force:true}));let now=1000;t.mock.method(Date,'now',()=>now);const agents=['a','b'].map((id,i)=>({pane_id:id,terminal_id:'t-'+id,tab_id:'tab',agent:'pi',agent_session:{kind:'id',value:id}}));const evidence=['a','b'].map(id=>({id,provider:'pi',messages:[],tools:[],usage:[],goals:[],availability:'known'}));const reads:string[]=[];const index:any={setActiveRefs(){},setDetailedRefs(){},refreshSnapshots:async()=>evidence,resolveSnapshotCached:(_p:string,ref:any)=>evidence.find(e=>e.id===ref.value),readTodoState:async(_p:string,ref:any)=>{reads.push(ref.value);return undefined;},diagnostics:[],close(){}};const rpc:any={call:async(method:string,p:any)=>method==='session.snapshot'?{snapshot:{protocol:22,agents,panes:agents}}:method==='agent.get'?{agent:agents.find(a=>a.pane_id===p.target)}:method==='pane.process_info'?{process_info:{foreground_processes:[{pid:p.pane_id==='a'?42:43,name:'pi'}]}}:{}};const sampler={sample:async()=>({platform:'fixture',bootId:'boot',sampledAt:now,monotonicNs:String(BigInt(now)*1000000n),processes:[42,43].map(pid=>({pid,ppid:1,startTime:'1',cpuNs:String(BigInt(now)*1000000n),rssBytes:'100',name:'pi'}))}),close:async()=>{}};const c=new Collector({rpc,index,sampler,stateDir:dir,settings:{nativeMode:'inspector-only',providerHomes:{},todosEnabled:true,sampleIntervalMs:2000,follow:false,ascii:true,monochrome:true},git:{close(){}} as any});t.after(()=>c.close({clearNative:false}));await c.init();for(const id of ['a','b','a']){c.setVisibleSelections([{key:'pi:'+id,subtree:false,expanded:false}]);await c.refresh();now+=1000;await c.sampleProcesses();assert.equal(c.dataForView('pi:'+id).sessions.find(s=>s.key==='pi:'+id)?.resource?.cpuPercent,undefined,'new disjoint selection starts with a warmup sample');now+=1000;await c.sampleProcesses();assert.equal(c.dataForView('pi:'+id).sessions.find(s=>s.key==='pi:'+id)?.resource?.cpuPercent,100);}assert.deepEqual(reads,['a','b','a']);});
