import {freshPrivateDirectory} from './helpers/private-dir.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import { writeFile, readFile, rm, stat } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { configure, unconfigure, loadSettings, nativeRows } from '../src/config/index.ts';
async function fixture(t:any,text:string) {const dir=await freshPrivateDirectory(join(tmpdir(),'hat-config-')); t.after(()=>rm(dir,{recursive:true,force:true})); const path=join(dir,'config.toml'); await writeFile(path,text); return {dir,path,state:join(dir,'state')};}
test('configuration preserves TOML multiline strings/comments and reverses exact original rows',async t=>{const original='# hello\n[other]\ntext = """\n[ui.sidebar.agents]\nrows = []\n"""\n["ui".sidebar.agents] # table\n# retain\nrows = [\n ["agent", "workspace"]\n] # trailing\n[unrelated]\nfoo = true\n'; const f=await fixture(t,original); assert.equal((await configure(f.path,f.state,{ownNative:true})).changed,true); const configured=await readFile(f.path,'utf8'); assert.ok(configured.includes('# retain')); assert.ok(configured.includes('[unrelated]\nfoo = true')); assert.equal((configured.match(/hat_add/g)||[]).length,1); assert.equal((await configure(f.path,f.state,{ownNative:true})).changed,false); assert.equal((await unconfigure(f.path,f.state)).changed,true); assert.equal(await readFile(f.path,'utf8'),original); assert.equal((await unconfigure(f.path,f.state)).changed,false); });
test('foreign rows including per-provider overrides require explicit ownership and restore',async t=>{const original='[ui.sidebar.agents]\nrows = [["$radar_name"]]\n[ui.sidebar.agents.rows_by_agent]\npi = [["$tree_label"]]\n'; const f=await fixture(t,original); await assert.rejects(configure(f.path,f.state,{}),/ownNative/); await configure(f.path,f.state,{ownNative:true}); const text=await readFile(f.path,'utf8'); assert.ok(!text.includes('$radar_name')); assert.ok(!text.includes('$tree_label')); await unconfigure(f.path,f.state); assert.equal(await readFile(f.path,'utf8'),original); });
test('unconfigure preserves changed user values while restoring still-owned values',async t=>{const f=await fixture(t,'[ui.sidebar.agents]\nrows = [["agent"]]\n'); await configure(f.path,f.state,{ownNative:true}); let text=await readFile(f.path,'utf8'); text=text.replace('$hat_goal','$my_goal'); await writeFile(f.path,text+'\n[user]\nx = 1\n'); const result=await unconfigure(f.path,f.state); assert.ok(result.conflicts.includes('ui.sidebar.agents.rows')); assert.ok((await readFile(f.path,'utf8')).includes('$my_goal')); assert.ok((await readFile(f.path,'utf8')).includes('[user]')); });
test('hash guard refuses concurrent mutation and inspector-only is a no-op',async t=>{const f=await fixture(t,'# base\n'); await configure(f.path,f.state,{mode:'inspector-only'}); assert.equal(await readFile(f.path,'utf8'),'# base\n'); await assert.rejects(configure(f.path,f.state,{ownNative:true,beforeCommit:()=>writeFile(f.path,'# newer\n')}),/concurrent/); assert.equal(await readFile(f.path,'utf8'),'# newer\n'); });
test('settings default opt-in ACTION and native rows have built-in fallback and bounded hat keys',async t=>{const f=await fixture(t,''); const s=await loadSettings(f.dir); assert.equal(s.todosEnabled,false); assert.equal(s.sampleIntervalMs,2000); assert.equal(s.nativeMode,'overview'); const rows=nativeRows(); const tokens=rows.flat().map(x=>typeof x==='string'?x:x.token); assert.ok(tokens.includes('agent')); assert.ok(tokens.includes('workspace')); assert.ok(tokens.includes('tab')); assert.ok(rows.length<=16); assert.ok(rows.every(row=>row.length<=16)); assert.ok(new Set(tokens.filter(x=>x.startsWith('$hat_'))).size<=14); await configure(f.path,f.state,{ownNative:true}); if(process.platform!=='win32') assert.equal((await stat(f.state)).mode&0o777,0o700); });
test('quoted dotted table component is unrelated and backslash quotes scan safely',async t=>{const original='["ui.sidebar.agents"]\nrows = [["keep"]]\n[other]\npath = "C:\\\\" # valid ending backslash\n[ui.sidebar.agents]\nrows = [["agent"]]\n';const f=await fixture(t,original);await configure(f.path,f.state,{ownNative:true});const text=await readFile(f.path,'utf8');assert.ok(text.includes('["ui.sidebar.agents"]\nrows = [["keep"]]'));await unconfigure(f.path,f.state);assert.equal(await readFile(f.path,'utf8'),original);});
test('optional keybindings remain owned across reconfiguration and unrelated user edits',async t=>{const original='[ui.sidebar.agents]\nrows = [["agent"]]\n[keys]\nfocus_agent = "original"\n';const f=await fixture(t,original);await configure(f.path,f.state,{ownNative:true,keybindings:{focus_agent:'prefix+alt+1..9'}});await configure(f.path,f.state,{ownNative:true,keybindings:{focus_workspace:'prefix+1..9'}});assert.ok(!(await readFile(f.path,'utf8')).includes('[keybindings]'));await writeFile(f.path,(await readFile(f.path,'utf8'))+'\n[user]\nx = 1\n');await unconfigure(f.path,f.state);const text=await readFile(f.path,'utf8');assert.ok(text.includes('focus_agent = "original"'));assert.ok(text.includes('[user]\nx = 1'));});

test('plugin action keys use canonical command array and preserve other command bindings',async t=>{const original='[[keys.command]]\nkey = "ctrl+x"\ntype = "plugin_action"\ncommand = "other:run"\n';const f=await fixture(t,original);await configure(f.path,f.state,{ownNative:true,pluginActionKey:{key:'prefix+a',command:'iob.herdr-prism:open',description:'Prism'}});const text=await readFile(f.path,'utf8');assert.equal((text.match(/\[\[keys.command\]\]/g)||[]).length,2);assert.ok(text.includes('command = "iob.herdr-prism:open"'));await writeFile(f.path,text+'\n[user]\nx = 1\n');await unconfigure(f.path,f.state);const result=await readFile(f.path,'utf8');assert.ok(result.includes('command = "other:run"'));assert.ok(!result.includes('iob.herdr-prism:open'));});

test('Prism installer shortcut is reversible in inspector-only mode and never takes a conflicting prefix+i',async t=>{
 const binding={key:'prefix+i',command:'iob.herdr-prism.open',description:'Open Prism'};
 const original='[keys]\nprefix = "ctrl+b"\n[ui.sidebar.agents]\nrows = [["agent"]]\n';const f=await fixture(t,original);
 const result=await configure(f.path,f.state,{mode:'inspector-only',pluginActionKey:binding,shortcutIfFree:true});
 assert.equal(result.shortcut,'configured');const text=await readFile(f.path,'utf8');assert.ok(text.includes('key = "prefix+i"'));assert.ok(text.includes('command = "iob.herdr-prism.open"'));assert.ok(text.includes('rows = [["agent"]]'));assert.ok(!text.includes('hat_'));
 await configure(f.path,f.state,{mode:'inspector-only',pluginActionKey:binding,shortcutIfFree:true});assert.equal((await readFile(f.path,'utf8')).split('key = "prefix+i"').length,2);
 await unconfigure(f.path,f.state);assert.equal(await readFile(f.path,'utf8'),original);
 for(const conflict of ['[keys]\nzoom = "prefix+i"\n','[[keys.command]]\nkey = \'PREFIX+I\'\ntype = "plugin_action"\ncommand = "other.open"\n','[keys]\ncommand = []\n','[keys]\nnext_tab = ["prefix+i", "ctrl+alt+n"]\n','[keys]\nnext_tab = " prefix+i "\n','[[keys.command]]\nkey = ["prefix+i"]\ntype = "shell"\ncommand = "echo keep"\n']){
  const c=await fixture(t,conflict);assert.equal((await configure(c.path,c.state,{mode:'inspector-only',pluginActionKey:binding,shortcutIfFree:true})).shortcut,'conflict');assert.equal(await readFile(c.path,'utf8'),conflict);
 }
 const existing='[[keys.command]]\nkey = "prefix+i"\ntype = "plugin_action"\ncommand = "iob.herdr-prism.open"\n';const e=await fixture(t,existing);
 assert.equal((await configure(e.path,e.state,{mode:'inspector-only',pluginActionKey:binding,shortcutIfFree:true})).shortcut,'existing');assert.equal(await readFile(e.path,'utf8'),existing);
});

test('cost rates carry currency and native light and mono presets are supported',async t=>{const f=await fixture(t,'');await writeFile(join(f.dir,'settings.json'),JSON.stringify({costRates:{model:{input:1,output:2,currency:'USD'}}}));assert.equal((await loadSettings(f.dir)).costRates?.model.currency,'USD');const light=nativeRows('light').flat().filter(x=>typeof x!=='string');const mono=nativeRows('mono').flat();assert.ok(light.some(x=>typeof x!=='string'&&x.fg!=='#42B883'));assert.ok(mono.every(x=>typeof x==='string'));});
test('configured TOML validates with independent Python parser and canonical Herdr keys',async t=>{const {execFile}=await import('node:child_process');const {promisify}=await import('node:util');const run=promisify(execFile);try{await run('python3',['--version']);}catch{t.skip('Python tomllib unavailable on this host');return;}const original='title = "fixture"\n[ui.sidebar.agents]\nrows = [["agent"]]\n[ui.sidebar.agents.rows_by_agent]\npi = [["agent"]]\n[[keys.command]]\nkey = "ctrl+x"\ntype = "plugin_action"\ncommand = "other:run"\n';const f=await fixture(t,original);await configure(f.path,f.state,{ownNative:true,keybindings:{focus_agent:'prefix+alt+1..9'},pluginActionKey:{key:'prefix+a',command:'iob.herdr-prism:open'}});const parsed=JSON.parse((await run('python3',['-c','import tomllib,json,sys; print(json.dumps(tomllib.load(open(sys.argv[1],"rb"))))',f.path])).stdout);assert.equal(parsed.keys.focus_agent,'prefix+alt+1..9');assert.equal(parsed.keys.command.length,2);assert.equal(parsed.keys.command[1].type,'plugin_action');assert.equal(parsed.ui.sidebar.agents.rows[1][1],'agent');assert.equal(parsed.ui.sidebar.agents.rows_by_agent.pi[1][1],'agent');await unconfigure(f.path,f.state);assert.equal(await readFile(f.path,'utf8'),original);});
test('unsupported dotted or inline ancestor topology is rejected before configuration writes',async t=>{const originals=['ui.sidebar.agents.expanded = true\n','[ui]\nsidebar = { agents = { expanded = true } }\n'];const {execFile}=await import('node:child_process');const {promisify}=await import('node:util');const run=promisify(execFile);for(const original of originals){const f=await fixture(t,original);await assert.rejects(configure(f.path,f.state,{ownNative:true}),/Unsupported existing TOML topology/);assert.equal(await readFile(f.path,'utf8'),original);const {readdir}=await import('node:fs/promises');assert.deepEqual(await readdir(f.state),[]);try{await run('python3',['--version']);}catch{continue;}const parsed=JSON.parse((await run('python3',['-c','import tomllib,json,sys; print(json.dumps(tomllib.load(open(sys.argv[1],"rb"))))',f.path])).stdout);assert.equal(parsed.ui.sidebar.agents.expanded,true);}});
