import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, mkdir, symlink, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { GitCache } from '../src/git/cache.ts';
import { parseNumstat, parseStatus } from '../src/git/status.ts';
const exec = promisify(execFile);
async function git(cwd:string,...args:string[]) { return (await exec('git',args,{cwd,env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}})).stdout; }
async function repo(t:any) { const cwd=await mkdtemp(join(tmpdir(),'hat-git-')); t.after(()=>rm(cwd,{recursive:true,force:true})); await git(cwd,'init','-b','main'); await git(cwd,'config','user.name','Fixture'); await git(cwd,'config','user.email','fixture@example.invalid'); return cwd; }
test('HEAD net numstat does not add staged and unstaged overlaps and does not read untracked',async t=>{ const cwd=await repo(t); const cache=new GitCache({ttlMs:0}); t.after(()=>cache.close()); await writeFile(join(cwd,'a'),'one\ntwo\n'); await git(cwd,'add','.'); await git(cwd,'commit','-m','base'); await writeFile(join(cwd,'a'),'one\nthree\n'); await git(cwd,'add','a'); await writeFile(join(cwd,'a'),'one\ntwo\n'); await writeFile(join(cwd,'untracked'),'hundreds\nof\nlines\n'); const s=await cache.get(cwd); assert.equal(s.added,0); assert.equal(s.deleted,0); assert.equal(s.untrackedFiles,1); assert.equal(s.stagedFiles,1); assert.equal(s.unstagedFiles,1); });
test('real roots and worktree family canonicalize symlinks and subdirectories',async t=>{const cwd=await repo(t); await writeFile(join(cwd,'a'),'a\n'); await git(cwd,'add','.'); await git(cwd,'commit','-m','base'); const wt=join(cwd,'work tree'); await git(cwd,'worktree','add','-b','feature',wt); await mkdir(join(wt,'nested')); const alias=join(cwd,'alias'); await symlink(wt,alias,'junction'); const cache=new GitCache(); t.after(()=>cache.close()); const [a,b,c]=await Promise.all([cache.get(cwd),cache.get(join(wt,'nested')),cache.get(alias)]); assert.equal(b.checkoutKey,c.checkoutKey); assert.notEqual(a.checkoutKey,b.checkoutKey); assert.equal(a.familyKey,b.familyKey); assert.equal(b.branch,'feature'); });
test('unborn, detached, nonGit and timeout stale states remain explicit',async t=>{const cwd=await repo(t); const cache=new GitCache({ttlMs:0}); t.after(()=>cache.close()); let s=await cache.get(cwd); assert.equal(s.branchState,'unborn'); assert.equal(s.added,undefined); await writeFile(join(cwd,'a'),'a\n'); await git(cwd,'add','.'); await git(cwd,'commit','-m','base'); await git(cwd,'checkout','--detach'); s=await cache.get(cwd); assert.equal(s.branchState,'detached'); assert.ok(s.head); const plain=await mkdtemp(join(tmpdir(),'hat-nongit-')); t.after(()=>rm(plain,{recursive:true,force:true})); assert.equal((await cache.get(plain)).branchState,'non-git'); const bad=new GitCache({timeoutMs:1,runner:async()=>{throw Object.assign(new Error('Git timed out'),{code:'ETIMEDOUT'});}}); t.after(()=>bad.close()); assert.equal((await bad.get(cwd)).availability,'unavailable'); });
test('NUL parsing keeps renamed newline and binary paths separate',()=>{const s=parseNumstat('2\t1\t\0old\nname\0new\nname\0-\t-\tbin\0'); assert.deepEqual(s,{added:2,deleted:1,binaryFiles:1}); const status=parseStatus('# branch.oid abc\0# branch.head main\0# branch.upstream origin/main\0# branch.ab +2 -3\0u UU N... 100644 100644 100644 100644 a b c conflict\0? x\nname\0'); assert.equal(status.conflicts,1); assert.equal(status.untrackedFiles,1); assert.equal(status.ahead,2); assert.equal(status.behind,3); });
test('refresh failure returns aged stale last measurement; invalidation retains it',async t=>{const cwd=await repo(t); await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');let fail=false,now=1000;const cache=new GitCache({ttlMs:5000,now:()=>now,runner:async(c,args)=>{if(fail)throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT'});return git(c,...args);}});t.after(()=>cache.close());const first=await cache.get(cwd);assert.equal(first.availability,'known');now=9000;fail=true;cache.invalidate(cwd);const stale=await cache.get(cwd);assert.equal(stale.availability,'stale');assert.equal(stale.ageMs,8000);assert.equal(stale.added,0);assert.match(stale.reason!,/timed out/);});
test('host queue caps children and one checkout refresh is shared across aliases',async t=>{const cwd=await repo(t);await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');await mkdir(join(cwd,'nested'));let active=0,peak=0,statusCalls=0;const cache=new GitCache({runner:async(c,args)=>{active++;peak=Math.max(peak,active);if(args[0]==='status')statusCalls++;try{return await git(c,...args);}finally{active--;}}});t.after(()=>cache.close());const values=await Promise.all([cache.get(cwd),cache.get(join(cwd,'nested')),cache.get(cwd)]);assert.ok(peak<=2);assert.equal(statusCalls,1);assert.equal(values[0].checkoutKey,values[1].checkoutKey);});
test('real binary rename newline path conflict and local upstream divergence',async t=>{const cwd=await repo(t);await writeFile(join(cwd,'old\nname'),'one\ntwo\n');await writeFile(join(cwd,'binary'),Buffer.from([0,1,2]));await writeFile(join(cwd,'conflict'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');await git(cwd,'branch','upstream');await git(cwd,'config','branch.main.remote','.');await git(cwd,'config','branch.main.merge','refs/heads/upstream');await git(cwd,'mv','old\nname','new\nname');await writeFile(join(cwd,'binary'),Buffer.from([0,2,3]));await git(cwd,'add','.');const cache=new GitCache({ttlMs:0});t.after(()=>cache.close());let s=await cache.get(cwd);assert.equal(s.binaryFiles,1);assert.equal(s.added,0);assert.equal(s.deleted,0);await git(cwd,'commit','-m','rename and binary');s=await cache.get(cwd);assert.equal(s.ahead,1);assert.equal(s.behind,0);await git(cwd,'checkout','upstream');await writeFile(join(cwd,'conflict'),'upstream\n');await git(cwd,'add','.');await git(cwd,'commit','-m','upstream edit');await git(cwd,'checkout','main');await writeFile(join(cwd,'conflict'),'main\n');await git(cwd,'add','.');await git(cwd,'commit','-m','main edit');await assert.rejects(git(cwd,'merge','upstream'));s=await cache.get(cwd);assert.equal(s.conflicts,1);assert.equal(s.ahead,2);assert.equal(s.behind,1);});
test('Git cwd identity ignores inherited GIT_DIR and GIT_WORK_TREE redirection',async t=>{const cwd=await repo(t);const other=await repo(t);await git(other,'symbolic-ref','HEAD','refs/heads/wrong');const previousDir=process.env.GIT_DIR,previousTree=process.env.GIT_WORK_TREE;process.env.GIT_DIR=join(other,'.git');process.env.GIT_WORK_TREE=other;try{const cache=new GitCache();t.after(()=>cache.close());const s=await cache.get(cwd);assert.equal(s.root,await import('node:fs/promises').then(m=>m.realpath(cwd)));assert.equal(s.branch,'main');}finally{if(previousDir===undefined)delete process.env.GIT_DIR;else process.env.GIT_DIR=previousDir;if(previousTree===undefined)delete process.env.GIT_WORK_TREE;else process.env.GIT_WORK_TREE=previousTree;}});
test('cache rejects invalid resource budgets',()=>{assert.throws(()=>new GitCache({maxEntries:-1}),/maxEntries/);assert.throws(()=>new GitCache({timeoutMs:0}),/timeoutMs/);});
test('invalidated symlink checkout aliases resolve their current target',async t=>{const cwd=await repo(t);await writeFile(join(cwd,'a'),'a\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');const wt=join(cwd,'worktree');await git(cwd,'worktree','add','-b','feature',wt);const alias=join(cwd,'pointer');await symlink(wt,alias,'junction');const cache=new GitCache();t.after(()=>cache.close());assert.equal((await cache.get(alias)).branch,'feature');await rm(alias);await symlink(cwd,alias,'junction');cache.invalidate(alias);assert.equal((await cache.get(alias)).branch,'main');});
test('untracked directory counts actual files rather than collapsed directory entries',async t=>{const cwd=await repo(t);await mkdir(join(cwd,'new directory'));await writeFile(join(cwd,'new directory','one'),'one\n');await writeFile(join(cwd,'new directory','two'),'two\n');const cache=new GitCache();t.after(()=>cache.close());assert.equal((await cache.get(cwd)).untrackedFiles,2);});
test('idle per-read TTL reuses measured Git facts but working reads and explicit invalidation refresh them',async t=>{
 const cwd=await repo(t);let now=1000,statusCalls=0;const cache=new GitCache({now:()=>now,runner:async(c,args)=>{if(args[0]==='status')statusCalls++;return git(c,...args);}});t.after(()=>cache.close());
 assert.equal((await cache.get(cwd)).untrackedFiles,0);await writeFile(join(cwd,'new'),'fixture');now=7000;
 const idle=await cache.get(cwd,{ttlMs:30000});assert.equal(idle.untrackedFiles,0);assert.equal(idle.ageMs,6000);assert.equal(statusCalls,1);
 assert.equal((await cache.get(cwd,{ttlMs:5000})).untrackedFiles,1);assert.equal(statusCalls,2);
 await writeFile(join(cwd,'another'),'fixture');cache.invalidate(cwd);assert.equal((await cache.get(cwd,{ttlMs:30000})).untrackedFiles,2);assert.equal(statusCalls,3);
 await assert.rejects(cache.get(cwd,{ttlMs:-1}),/ttlMs/);
});
