import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, mkdir, symlink, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { GitCache } from '../src/git/cache.ts';
import { parseNumstat, parseStatus } from '../src/git/status.ts';
const exec = promisify(execFile);
async function git(cwd:string,...args:string[]) { return (await exec('git',args,{cwd,env:{...process.env,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:'/dev/null'}})).stdout; }
async function repo(t:any) { const cwd=await mkdtemp(join(tmpdir(),'hat-git-')); t.after(()=>rm(cwd,{recursive:true,force:true})); await git(cwd,'init','-b','main'); await git(cwd,'config','user.name','Fixture'); await git(cwd,'config','user.email','fixture@example.invalid'); return cwd; }
test('HEAD net numstat does not add staged and unstaged overlaps and does not read untracked',async t=>{ const cwd=await repo(t); const cache=new GitCache({ttlMs:0}); t.after(()=>cache.close()); await writeFile(join(cwd,'a'),'one\ntwo\n'); await git(cwd,'add','.'); await git(cwd,'commit','-m','base'); await writeFile(join(cwd,'a'),'one\nthree\n'); await git(cwd,'add','a'); await writeFile(join(cwd,'a'),'one\ntwo\n'); await writeFile(join(cwd,'untracked'),'hundreds\nof\nlines\n'); const s=await cache.get(cwd); assert.equal(s.added,0); assert.equal(s.deleted,0); assert.equal(s.untrackedFiles,1); assert.equal(s.stagedFiles,1); assert.equal(s.unstagedFiles,1); });
test('real roots and worktree family canonicalize symlinks and subdirectories',async t=>{const cwd=await repo(t); await writeFile(join(cwd,'a'),'a\n'); await git(cwd,'add','.'); await git(cwd,'commit','-m','base'); const wt=join(cwd,'work tree'); await git(cwd,'worktree','add','-b','feature',wt); await mkdir(join(wt,'nested')); const alias=join(cwd,'alias'); await symlink(wt,alias,'junction'); const cache=new GitCache(); t.after(()=>cache.close()); const [a,b,c]=await Promise.all([cache.get(cwd),cache.get(join(wt,'nested')),cache.get(alias)]); assert.equal(b.checkoutKey,c.checkoutKey); assert.notEqual(a.checkoutKey,b.checkoutKey); assert.equal(a.familyKey,b.familyKey); assert.equal(b.branch,'feature'); });
test('unborn, detached, nonGit and timeout stale states remain explicit',async t=>{const cwd=await repo(t); const cache=new GitCache({ttlMs:0}); t.after(()=>cache.close()); let s=await cache.get(cwd); assert.equal(s.branchState,'unborn'); assert.equal(s.added,undefined); await writeFile(join(cwd,'a'),'a\n'); await git(cwd,'add','.'); await git(cwd,'commit','-m','base'); await git(cwd,'checkout','--detach'); s=await cache.get(cwd); assert.equal(s.branchState,'detached'); assert.ok(s.head); const plain=await mkdtemp(join(tmpdir(),'hat-nongit-')); t.after(()=>rm(plain,{recursive:true,force:true})); assert.equal((await cache.get(plain)).branchState,'non-git'); const bad=new GitCache({timeoutMs:1,runner:async()=>{throw Object.assign(new Error('Git timed out'),{code:'ETIMEDOUT'});}}); t.after(()=>bad.close()); assert.equal((await bad.get(cwd)).availability,'unavailable'); });
test('NUL parsing keeps renamed newline and binary paths separate',()=>{const s=parseNumstat('2\t1\t\0old\nname\0new\nname\0-\t-\tbin\0'); assert.deepEqual(s,{added:2,deleted:1,binaryFiles:1}); const status=parseStatus('# branch.oid abc\0# branch.head main\0# branch.upstream origin/main\0# branch.ab +2 -3\0u UU N... 100644 100644 100644 100644 a b c conflict\0? x\nname\0'); assert.equal(status.conflicts,1); assert.equal(status.untrackedFiles,1); assert.equal(status.ahead,2); assert.equal(status.behind,3); });
test('refresh failure returns aged stale last measurement; invalidation retains it',async t=>{const cwd=await repo(t); await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');let fail=false,now=1000;const cache=new GitCache({ttlMs:5000,now:()=>now,runner:async(c,args)=>{if(fail)throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT'});return git(c,...args);}});t.after(()=>cache.close());const first=await cache.get(cwd);assert.equal(first.availability,'known');now=9000;fail=true;cache.invalidate(cwd);const stale=await cache.get(cwd);assert.equal(stale.availability,'stale');assert.equal(stale.ageMs,8000);assert.equal(stale.added,0);assert.match(stale.reason!,/timed out/);});
test('host queue caps children and one checkout refresh is shared across aliases',async t=>{const cwd=await repo(t);await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');await mkdir(join(cwd,'nested'));let active=0,peak=0,statusCalls=0;const cache=new GitCache({runner:async(c,args)=>{active++;peak=Math.max(peak,active);if(args[0]==='status')statusCalls++;try{return await git(c,...args);}finally{active--;}}});t.after(()=>cache.close());const values=await Promise.all([cache.get(cwd),cache.get(join(cwd,'nested')),cache.get(cwd)]);assert.ok(peak<=2);assert.equal(statusCalls,1);assert.equal(values[0].checkoutKey,values[1].checkoutKey);});
test('real binary Unicode-space rename conflict and local upstream divergence',async t=>{const cwd=await repo(t);await writeFile(join(cwd,'old 日本 name'),'one\ntwo\n');await writeFile(join(cwd,'binary'),Buffer.from([0,1,2]));await writeFile(join(cwd,'conflict'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');await git(cwd,'branch','upstream');await git(cwd,'config','branch.main.remote','.');await git(cwd,'config','branch.main.merge','refs/heads/upstream');await git(cwd,'mv','old 日本 name','new 日本 name');await writeFile(join(cwd,'binary'),Buffer.from([0,2,3]));await git(cwd,'add','.');const cache=new GitCache({ttlMs:0});t.after(()=>cache.close());let s=await cache.get(cwd);assert.equal(s.binaryFiles,1);assert.equal(s.added,0);assert.equal(s.deleted,0);await git(cwd,'commit','-m','rename and binary');s=await cache.get(cwd);assert.equal(s.ahead,1);assert.equal(s.behind,0);await git(cwd,'checkout','upstream');await writeFile(join(cwd,'conflict'),'upstream\n');await git(cwd,'add','.');await git(cwd,'commit','-m','upstream edit');await git(cwd,'checkout','main');await writeFile(join(cwd,'conflict'),'main\n');await git(cwd,'add','.');await git(cwd,'commit','-m','main edit');await assert.rejects(git(cwd,'merge','upstream'));s=await cache.get(cwd);assert.equal(s.conflicts,1);assert.equal(s.ahead,2);assert.equal(s.behind,1);});
test('Git cwd identity ignores inherited GIT_DIR and GIT_WORK_TREE redirection',async t=>{const cwd=await repo(t);const other=await repo(t);await git(other,'symbolic-ref','HEAD','refs/heads/wrong');const previousDir=process.env.GIT_DIR,previousTree=process.env.GIT_WORK_TREE;process.env.GIT_DIR=join(other,'.git');process.env.GIT_WORK_TREE=other;try{const cache=new GitCache();t.after(()=>cache.close());const s=await cache.get(cwd);assert.equal(s.root,await import('node:fs/promises').then(m=>m.realpath(cwd)));assert.equal(s.branch,'main');}finally{if(previousDir===undefined)delete process.env.GIT_DIR;else process.env.GIT_DIR=previousDir;if(previousTree===undefined)delete process.env.GIT_WORK_TREE;else process.env.GIT_WORK_TREE=previousTree;}});
test('cache rejects invalid resource budgets',()=>{assert.throws(()=>new GitCache({maxEntries:-1}),/maxEntries/);assert.throws(()=>new GitCache({timeoutMs:0}),/timeoutMs/);});
test('invalidated symlink checkout aliases resolve their current target',async t=>{const cwd=await repo(t);await writeFile(join(cwd,'a'),'a\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');const wt=join(cwd,'worktree');await git(cwd,'worktree','add','-b','feature',wt);const alias=join(cwd,'pointer');await symlink(wt,alias,'junction');const cache=new GitCache();t.after(()=>cache.close());assert.equal((await cache.get(alias)).branch,'feature');await rm(alias);await symlink(cwd,alias,'junction');cache.invalidate(alias);assert.equal((await cache.get(alias)).branch,'main');});
test('untracked directory counts actual files rather than collapsed directory entries',async t=>{const cwd=await repo(t);await mkdir(join(cwd,'new directory'));await writeFile(join(cwd,'new directory','one'),'one\n');await writeFile(join(cwd,'new directory','two'),'two\n');const cache=new GitCache();t.after(()=>cache.close());assert.equal((await cache.get(cwd)).untrackedFiles,2);});
test('idle per-read TTL reuses measured Git facts but working reads and explicit invalidation refresh them',async t=>{
 const cwd=await repo(t);let now=1000,statusCalls=0;const cache=new GitCache({now:()=>now,runner:async(c,args)=>{if(args[0]==='status')statusCalls++;return git(c,...args);}});t.after(()=>cache.close());
 assert.equal((await cache.get(cwd)).untrackedFiles,0);await writeFile(join(cwd,'new'),'fixture');now=7000;
 const idle=await cache.get(cwd,{ttlMs:30000});assert.equal(idle.untrackedFiles,0);assert.equal(idle.ageMs,6000);assert.equal(statusCalls,1);
 assert.equal((await cache.get(cwd,{ttlMs:5000})).untrackedFiles,1);assert.equal(statusCalls,2);
 await writeFile(join(cwd,'another'),'fixture');cache.invalidate(cwd);assert.equal((await cache.get(cwd,{ttlMs:30000})).untrackedFiles,2);assert.equal(statusCalls,3);
 await assert.rejects(cache.get(cwd,{ttlMs:-1}),/ttlMs/);
});
test('metadata-only Git lookup resolves worktree identity without status or diff scans',async t=>{
 const cwd=await repo(t);await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');const wt=join(cwd,'linked');await git(cwd,'worktree','add','-b','feature',wt);await mkdir(join(wt,'nested'));const alias=join(cwd,'metadata-alias');await symlink(wt,alias,'junction');const calls:string[][]=[];const cache=new GitCache({runner:async(c,args)=>{calls.push(args);return git(c,...args);}});t.after(()=>cache.close());
 const [main,worktree,linked]=await Promise.all([cache.getIdentity(cwd),cache.getIdentity(join(wt,'nested')),cache.getIdentity(alias)]);
 assert.equal(main.identityOnly,true);assert.equal(worktree.branch,'feature');assert.equal(worktree.branchState,'named');assert.equal(worktree.checkoutKey,linked.checkoutKey);assert.equal(main.familyKey,worktree.familyKey);assert.notEqual(main.checkoutKey,worktree.checkoutKey);assert.ok(worktree.head);assert.equal(worktree.added,undefined);assert.equal(worktree.untrackedFiles,undefined);assert.ok(calls.every(args=>args[0]==='rev-parse'||args[0]==='symbolic-ref'));
});
test('metadata cache retains independent measured counts but invalidates them on HEAD changes',async t=>{
 const cwd=await repo(t);await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');let now=1000,statusCalls=0;const cache=new GitCache({ttlMs:60000,now:()=>now,runner:async(c,args)=>{if(args[0]==='status')statusCalls++;return git(c,...args);}});t.after(()=>cache.close());const full=await cache.get(cwd);const first=await cache.getIdentity(cwd);assert.equal(first.added,undefined);assert.equal((await cache.get(cwd)).sampledAt,full.sampledAt);assert.equal(statusCalls,1);
 await git(cwd,'checkout','-b','changed');now=32000;assert.equal((await cache.getIdentity(cwd)).branch,'changed');assert.equal((await cache.get(cwd)).branch,'changed');assert.equal(statusCalls,2);
});
test('metadata-only cache handles unborn, detached and negative results with bounded TTL',async t=>{
 const cwd=await repo(t);let now=1000,calls=0;const cache=new GitCache({now:()=>now,runner:async(c,args)=>{calls++;return git(c,...args);}});t.after(()=>cache.close());const unborn=await cache.getIdentity(cwd);assert.equal(unborn.branch,'main');assert.equal(unborn.branchState,'unborn');assert.equal(unborn.head,undefined);await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');await git(cwd,'checkout','--detach');cache.invalidate(cwd);assert.equal((await cache.getIdentity(cwd)).branchState,'detached');
 const plain=await mkdtemp(join(tmpdir(),'hat-metadata-negative-'));t.after(()=>rm(plain,{recursive:true,force:true}));const negative=await cache.getIdentity(plain);assert.equal(negative.availability,'not_applicable');assert.equal(negative.branchState,'non-git');const before=calls;now=2000;assert.equal((await cache.getIdentity(plain)).ageMs,1000);assert.equal(calls,before);now=32000;await cache.getIdentity(plain);assert.ok(calls>before);await assert.rejects(cache.getIdentity(cwd,{ttlMs:-1}),/ttlMs/);
});
test('metadata polling deduplicates aliases, respects host process budget, and caches retry failures',async t=>{
 const cwd=await repo(t);await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');await mkdir(join(cwd,'nested'));let now=1000,active=0,peak=0,headCalls=0,calls=0,fail=false;const cache=new GitCache({now:()=>now,runner:async(c,args)=>{calls++;active++;peak=Math.max(peak,active);try{if(fail)throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT'});if(args.includes('HEAD'))headCalls++;return await git(c,...args);}finally{active--;}}});t.after(()=>cache.close());
 const values=await Promise.all([cache.getIdentity(cwd),cache.getIdentity(cwd),cache.getIdentity(join(cwd,'nested'))]);assert.equal(values[0].checkoutKey,values[2].checkoutKey);assert.ok(peak<=2);assert.equal(headCalls,2);
 now=32000;fail=true;const stale=await cache.getIdentity(cwd);assert.equal(stale.availability,'stale');assert.equal(stale.ageMs,31000);const before=calls;now=33000;assert.equal((await cache.getIdentity(cwd)).ageMs,32000);assert.equal(calls,before);
});
test('metadata HEAD movement invalidates counts even when the branch name stays the same',async t=>{
 const cwd=await repo(t);await writeFile(join(cwd,'a'),'base\n');await git(cwd,'add','.');await git(cwd,'commit','-m','base');const cache=new GitCache({ttlMs:60000});t.after(()=>cache.close());await writeFile(join(cwd,'a'),'base\nextra\n');assert.equal((await cache.get(cwd)).added,1);const before=await cache.getIdentity(cwd);await git(cwd,'add','.');await git(cwd,'commit','-m','changed');const after=await cache.getIdentity(cwd,{ttlMs:0});assert.equal(after.branch,before.branch);assert.notEqual(after.head,before.head);assert.equal((await cache.get(cwd)).added,0);
});
test('closing metadata cache aborts an active Git child and never launches queued work',async t=>{
 const cwd=await repo(t);let entered!:()=>void;const ready=new Promise<void>(resolve=>entered=resolve);let calls=0;const cache=new GitCache({runner:async(_cwd,_args,{signal})=>{calls++;entered();return new Promise((_resolve,reject)=>signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));}});const pending=cache.getIdentity(cwd);await ready;cache.close();assert.equal((await pending).availability,'unavailable');assert.equal((await cache.getIdentity(cwd)).availability,'unavailable');assert.equal(calls,1);
});
