import test from 'node:test';
import assert from 'node:assert/strict';
import {availableParallelism,tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {spawn} from 'node:child_process';
import {once} from 'node:events';
import {createInterface} from 'node:readline';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {setTimeout as delay} from 'node:timers/promises';
import {createSampler,type ProcessSampler} from '../src/process/sampler.ts';
import {ProcessTracker} from '../src/process/ownership.ts';
import {Collector} from '../src/runtime/collector.ts';
import type {Rpc,HerdrAgent} from '../src/model/types.ts';
const helper=process.env.HAT_NATIVE_HELPER??resolve(`native/sampler/target/debug/hat-sampler${process.platform==='win32'?'.exe':''}`);
const executable=resolve('test/fixtures/process/pi');
async function readable(ctx:any,sampler:ProcessSampler){try{await sampler.sample();return true;}catch(error){if(process.env.HAT_REQUIRE_NATIVE!=='1'&&/boot identity unavailable|enumeration denied/.test(String(error))){ctx.skip(`Actual OS enumeration denied: ${String(error)}`);return false;}throw error;}}
async function startHarness(cwd:string){const child=spawn(process.execPath,[executable],{cwd,stdio:['pipe','pipe','pipe']});const reader=createInterface({input:child.stdout});let timer:NodeJS.Timeout;try{const result=await Promise.race([once(reader,'line').then(([line])=>JSON.parse(line) as {pid:number;workers:number[]}),new Promise<never>((_,reject)=>{timer=setTimeout(()=>reject(new Error('Controlled harness startup timeout')),5000);})]);assert.equal(result.pid,child.pid);assert.equal(result.workers.length,2);return {child,pids:[result.pid,...result.workers],async close(){reader.close();if(child.exitCode!==null)return;const exited=once(child,'exit');child.stdin.end();await Promise.race([exited,delay(3000,undefined,{ref:false}).then(()=>{child.kill();return exited;})]);}};}catch(error){child.stdin.end();child.kill();reader.close();throw error;}finally{clearTimeout(timer!);}}
test('real host multicore ownership warms up and subtree union exceeds one logical core',{timeout:30000,skip:availableParallelism()<2},async(ctx)=>{
 const sampler=createSampler({helperPath:helper});const dir=await mkdtemp(join(tmpdir(),'hat-live-multicore-'));let harness:Awaited<ReturnType<typeof startHarness>>|undefined;
 try{if(!await readable(ctx,sampler))return;harness=await startHarness(dir);const tracker=new ProcessTracker();const first=await sampler.sample();const parent=first.processes.find(p=>p.pid===harness!.pids[0]);const child=first.processes.find(p=>p.pid===harness!.pids[1]);assert.ok(parent&&child);const roots=[{sessionKey:'parent',pid:parent.pid,startTime:parent.startTime},{sessionKey:'child',pid:child.pid,startTime:child.startTime}];tracker.update(first,roots);assert.equal(tracker.view('parent',true,['child']).cpuPercent,undefined);
 let peak=0;for(let i=0;i<3;i++){await delay(900);const batch=await sampler.sample();tracker.update(batch,roots);const view=tracker.view('parent',true,['child']);assert.deepEqual(new Set(view.processes.map(p=>p.pid)),new Set(harness.pids));assert.equal(view.cpuCoverage.readable,3);assert.ok(view.cpuPercent!==undefined,'actual counters require a measured second sample');peak=Math.max(peak,view.cpuPercent);const exclusive=new Set(tracker.view('parent').processes.map(p=>p.key));assert.ok(tracker.view('child').processes.every(p=>!exclusive.has(p.key)));assert.equal(view.memoryBytes,view.processes.reduce((sum,p)=>sum+BigInt(p.rssBytes),0n).toString());if(peak>100)break;}
 assert.ok(peak>100,`Two controlled CPU workers on ${availableParallelism()} logical cores measured ${peak}%`);
 }finally{await harness?.close();await sampler.close();await rm(dir,{recursive:true,force:true});}
});
test('actual host sampler feeds an exact-session foreground collector and closes cleanly',{timeout:30000},async(ctx)=>{
 const sampler=createSampler({helperPath:helper});const dir=await mkdtemp(join(tmpdir(),'hat-live-collector-'));let harness:Awaited<ReturnType<typeof startHarness>>|undefined;let collector:Collector|undefined;
 try{if(!await readable(ctx,sampler))return;harness=await startHarness(dir);await mkdir(join(dir,'pi-home'),{recursive:true});const transcript=join(dir,'pi-home','controlled.jsonl');await writeFile(transcript,[{type:'session',version:3,id:'controlled-live',cwd:dir,timestamp:new Date().toISOString()},{type:'message',id:'request',message:{role:'user',content:'Controlled process acceptance'}}].map(r=>JSON.stringify(r)+'\n').join(''));
 const agent:HerdrAgent={pane_id:'controlled:pane',terminal_id:'controlled:terminal',workspace_id:'controlled:workspace',tab_id:'controlled:tab',agent:'pi',agent_status:'working',agent_session:{source:'herdr:pi',agent:'pi',kind:'path',value:transcript},focused:false,revision:1};
 const rpc:Rpc={async call<T>(method:string){if(method==='session.snapshot')return {snapshot:{protocol:22,version:'0.9.3',agents:[agent],panes:[],tabs:[],workspaces:[],layouts:[]}} as T;if(method==='agent.get')return {agent} as T;if(method==='pane.process_info')return {process_info:{foreground_processes:[{pid:harness!.pids[0],name:'node',argv:[process.execPath,executable]}]}} as T;if(method==='agent.view.clear')return {} as T;throw new Error(`Unexpected harness RPC ${method}`);}};
 collector=new Collector({paneOpen:true,rpc,sampler,stateDir:join(dir,'state'),settings:{nativeMode:'inspector-only',providerHomes:{pi:join(dir,'pi-home'),codex:join(dir,'empty-codex'),claude:join(dir,'empty-claude')},todosEnabled:false,sampleIntervalMs:2000,follow:false,ascii:true,monochrome:true}});
 await collector.init();await collector.refresh();assert.equal(collector.data.sessions.length,1);assert.equal(collector.data.sessions[0]!.key,'pi:controlled-live');await collector.sampleProcesses();assert.equal(collector.data.sessions[0]!.resource!.cpuPercent,undefined);await delay(900);await collector.sampleProcesses();const session=collector.data.sessions[0]!;const view=session.resource!;assert.deepEqual(new Set(view.processes.map(p=>p.pid)),new Set(harness.pids));assert.equal(view.cpuCoverage.readable,3);assert.ok(view.cpuPercent!==undefined&&view.cpuPercent>20,`Real collector measured CPU ${view.cpuPercent}; ${view.reason??''}`);assert.ok(BigInt(view.memoryBytes!)>32n*1024n*1024n);assert.equal(view.memoryLabel,process.platform==='win32'?'working-set sum':'RSS sum');assert.ok(session.history!.cpu!.some(value=>value!==undefined&&value>0));await collector.close();collector=undefined;await assert.rejects(sampler.sample(),/closed/);assert.equal(harness.child.exitCode,null,'collector must not terminate the observed harness');
 }finally{await collector?.close();await harness?.close();await sampler.close();await rm(dir,{recursive:true,force:true});}
});
