import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, appendFile, rename, rm, symlink, stat, utimes } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join,resolve } from 'node:path';

const module = await import('../src/providers/index.ts').catch(() => ({})) as any;
const line = (record: unknown) => JSON.stringify(record) + '\n';
const meta = (id: string, parent?: string) => ({type:'session_meta', timestamp:'2026-10-06T10:00:00Z', payload:{id,cwd:'/same',cli_version:'0.154.0',source:parent ? {subagent:{thread_spawn:{parent_thread_id:parent}}} : 'cli'}});
const text = (id: string, body: string, role='assistant', channel='final') => ({type:'response_item',timestamp:'2026-10-06T10:01:00Z',payload:{type:'message',id,role,channel,content:[{type:'output_text',text:body}]}});
async function home(t: any) { const root = await mkdtemp(join(tmpdir(),'hat-provider-')); t.after(()=>rm(root,{recursive:true,force:true})); return root; }
async function put(root: string, path: string, records: unknown[]) { const file = join(root,path); await mkdir(join(file,'..'),{recursive:true}); await writeFile(file,records.map(line).join('')); return file; }
function index(root: string, extra={}) { assert.equal(typeof module.ProviderIndex,'function','provider exact-evidence index is implemented'); return new module.ProviderIndex({codexHome:join(root,'codex'),claudeHome:join(root,'claude'),piHome:join(root,'pi'),directoryScanMs:0,...extra}); }
test('reference history recovers old edits beyond the hot window and incrementally follows append, truncate and rotation',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[
 meta('r'),text('first','See `src/a.ts`'),
 {type:'response_item',payload:{type:'function_call',call_id:'patch',name:'apply_patch',arguments:'*** Begin Patch\n*** Update File: src/a.ts\n@@\n-a\n+b\n*** End Patch'}},
 {type:'response_item',payload:{type:'function_call_output',call_id:'patch',output:'Success'}},
 ...Array.from({length:250},(_,i)=>text('later'+i,'No reference here'))
 ]);const ix=index(root,{maxMessages:200});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);await ix.refresh();
 assert.equal(typeof ix.readReferences,'function','historical reference reader missing');
 let state=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(state.refs.length,1);assert.equal(state.refs[0].messageId,'first');assert.equal(state.refs[0].edited,true);assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).messages.length,200);
 await appendFile(file,line(text('latest','Again `src/a.ts`')));await ix.refresh();state=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(state.refs[0].messageId,'latest');assert.deepEqual(state.refs[0].sources.map((s:any)=>s.messageId),['first','latest']);
 await writeFile(file,[meta('r'),text('replacement','See `src/b.ts`')].map(line).join(''));await ix.refresh();state=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(state.refs.length,1);assert.equal(state.refs[0].target,resolve('/same','src','b.ts'));
 await rename(file,file+'.old');await writeFile(file,[meta('r'),text('rotated','See `src/c.ts`')].map(line).join(''));await ix.refresh();state=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(state.refs[0].messageId,'rotated');assert.equal(state.refs.length,1);
 assert.equal(await ix.readReferences('codex',{kind:'id',value:'r'},()=>false),undefined);
});
test('reference history preserves standalone successful patch events after cwd changes without inferring failed edits',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),text('first','See `src/a.ts` and `src/b.ts`'),{type:'event_msg',payload:{type:'patch_apply_end',success:true,changes:{'src/a.ts':{}}}},{type:'event_msg',payload:{type:'patch_apply_end',success:false,changes:{'src/b.ts':{}}}},{type:'turn_context',payload:{cwd:'/another-checkout'}},...Array.from({length:250},(_,i)=>text('plain-'+i,'No references'))]);
 const ix=index(root);t.after(()=>ix.close());await ix.refresh();const state=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);
 assert.equal(state.refs.find((r:any)=>r.target===resolve('/same','src','a.ts')).edited,true);assert.equal(state.refs.find((r:any)=>r.target===resolve('/same','src','b.ts')).edited,false);assert.equal(state.refs.length,2);
});
test('reference target pages recover every target beyond the hot bound with generation-checked cursors',async t=>{
 const root=await home(t),records=Array.from({length:2105},(_,i)=>text('ref-'+i,'See `src/ref-'+i+'.ts`'));
 const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),...records,{type:'event_msg',payload:{type:'patch_apply_end',success:true,changes:{'src/ref-0.ts':{}}}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();
 const hot=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(hot.refs.length,2000);assert.equal(hot.limited,true);
 assert.equal(typeof ix.pageReferences,'function','older target pagination missing');const excluded=hot.refs.map((r:any)=>r.id),seen=new Set<string>();let cursor:any;let pages=0;let first:any;
 do{const page=await ix.pageReferences('codex',{kind:'id',value:'r'},{limit:50,excludeIds:excluded,cursor},()=>true);assert.ok(page);assert.ok(page.refs.length<=50);for(const ref of page.refs){assert.ok(!seen.has(ref.id),'target repeated across pages');seen.add(ref.id);assert.ok(ref.cursor);if(ref.messageId==='ref-0')first=ref;}cursor=page.hasMore?page.cursor:undefined;pages++;assert.ok(pages<5);}while(cursor);
 assert.equal(seen.size,105);assert.equal(first.edited,true);assert.equal((await ix.readReferenceMessage(first.cursor,()=>true)).id,'ref-0');assert.equal((await ix.readReferences('codex',{kind:'id',value:'r'},()=>true)).refs.length,2000);
 const page=await ix.pageReferences('codex',{kind:'id',value:'r'},{limit:10,excludeIds:excluded},()=>true);await appendFile(file,line(text('new-ref','See `src/new.ts`')));
 await assert.rejects(ix.pageReferences('codex',{kind:'id',value:'r'},{limit:10,excludeIds:excluded,cursor:page.cursor},()=>true),/history changed/i);
 assert.equal(await ix.pageReferences('codex',{kind:'id',value:'r'},{},()=>false),undefined);
 let checks=0;assert.equal(await ix.pageReferences('codex',{kind:'id',value:'r'},{limit:50},()=>++checks<200),undefined);assert.ok(checks>=200,'cancellation must occur inside a record scan');assert.equal((await ix.pageReferences('codex',{kind:'id',value:'r'},{limit:10},()=>true)).refs.length,10,'a cancelled request cannot poison the next page');
});
test('reference source pages recover all mentions, deduplicate mirrors and reject replaced source bodies',async t=>{
 const root=await home(t),mentions=Array.from({length:150},(_,i)=>text('mention-'+i,'Mention '+i+' of `src/shared.ts`'));
 const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),...mentions]);await put(root,'codex/archived_sessions/r.jsonl',[meta('r'),...mentions.slice(100)]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const hot=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(hot.refs[0].sources.length,100);
 assert.equal(typeof ix.pageReferenceSources,'function','older mention pagination missing');const seen=new Set<string>();let cursor:any,first:any;let pages=0;
 do{const page=await ix.pageReferenceSources('codex',{kind:'id',value:'r'},hot.refs[0].id,{limit:50,cursor},()=>true);assert.ok(page);assert.equal(page.partial,false,'a hot metadata cap must not claim that the source input is incomplete');assert.ok(page.sources.length<=50);for(const source of page.sources){assert.ok(!seen.has(source.messageId),'mirror source repeated across pages');seen.add(source.messageId);assert.ok(source.cursor);if(source.messageId==='mention-0')first=source;}cursor=page.hasMore?page.cursor:undefined;pages++;assert.ok(pages<5);}while(cursor);
 assert.equal(seen.size,150);assert.equal((await ix.readReferenceMessage(first.cursor,()=>true)).text,'Mention 0 of `src/shared.ts`');assert.equal(await ix.readReferenceMessage(first.cursor,()=>false),undefined);
 const scoped=await ix.pageReferenceSources('codex',{kind:'id',value:'r'},hot.refs[0].id,{limit:10},()=>true);await assert.rejects(ix.pageReferenceSources('codex',{kind:'id',value:'r'},'f'.repeat(24),{cursor:scoped.cursor},()=>true),/cursor scope/i);assert.equal(await ix.pageReferenceSources('codex',{kind:'id',value:'r'},'',{},()=>true),undefined);
 await writeFile(file,[meta('other'),text('mention-0','Different body `src/shared.ts`')].map(line).join(''));assert.equal(await ix.readReferenceMessage(first.cursor,()=>true),undefined,'reused source path cannot return another session or revision');
 let checks=0;assert.equal(await ix.pageReferenceSources('codex',{kind:'id',value:'r'},hot.refs[0].id,{},()=>++checks<4),undefined);
});
test('reference page boundaries separate targets in one message and cannot repeat targets mentioned on both sides',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),text('many',Array.from({length:405},(_,i)=>'`src/one-'+i+'.ts`').join(' ')),...Array.from({length:100},(_,i)=>text('again-'+i,'Again `src/one-'+i+'.ts`'))]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();assert.equal(typeof ix.pageReferences,'function');let cursor:any;const seen=new Set<string>();let pages=0;
 do{const page=await ix.pageReferences('codex',{kind:'id',value:'r'},{limit:50,cursor},()=>true);for(const ref of page.refs){assert.ok(!seen.has(ref.id),'a target repeated across the cursor boundary');seen.add(ref.id);}cursor=page.hasMore?page.cursor:undefined;assert.ok(++pages<12);}while(cursor);assert.equal(seen.size,405,'all targets sharing one source offset must remain pageable');
});
test('reference source jumps distinguish completed revisions with the same message ID',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),text('same-id','First revision `src/a.ts`'),text('same-id','Second revision `src/a.ts`')]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const hot=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(hot.refs[0].sources.length,2);const page=await ix.pageReferenceSources('codex',{kind:'id',value:'r'},hot.refs[0].id,{},()=>true);assert.equal(page.sources.length,2);assert.notEqual(page.sources[0].cursor.hash,page.sources[1].cursor.hash);assert.equal((await ix.readReferenceMessage(page.sources[0].cursor,()=>true)).text,'Second revision `src/a.ts`');assert.equal((await ix.readReferenceMessage(page.sources[1].cursor,()=>true)).text,'First revision `src/a.ts`');
});
test('historical Claude source assembly retains unfinished visible blocks across unrelated messages',async t=>{
 const root=await home(t),assistant=(body:string,stop:string|null)=>({type:'assistant',sessionId:'r',cwd:'/same',message:{id:'streamed',role:'assistant',content:[{type:'thinking',thinking:'HIDDEN /private/reasoning.ts'},{type:'text',text:body}],stop_reason:stop}});
 await put(root,'claude/projects/p/r.jsonl',[assistant('Earlier `src/first.ts`',null),...Array.from({length:4},(_,i)=>({type:'user',sessionId:'r',cwd:'/same',message:{id:'user-'+i,role:'user',content:[{type:'text',text:'Unrelated user input'}]}})),assistant('Final `src/final.ts`','end_turn')]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const hot=await ix.readReferences('claude',{kind:'id',value:'r'},()=>true);assert.equal(hot.refs.length,2,'an unfinished assistant prefix must survive the tiny historical message window');const first=hot.refs.find((ref:any)=>ref.target===resolve('/same','src','first.ts'));const source=await ix.readReferenceMessage(first.cursor,()=>true);assert.equal(source.text,'Earlier `src/first.ts`\nFinal `src/final.ts`');assert.ok(!JSON.stringify(hot).includes('reasoning'));
});
test('unfinished Claude assembly overflow is bounded and labels reference coverage partial',async t=>{
 const root=await home(t),rows=Array.from({length:17},(_,i)=>({type:'assistant',sessionId:'r',cwd:'/same',message:{id:'pending-'+i,role:'assistant',content:[{type:'text',text:'Unfinished `src/old-'+i+'.ts`'}],stop_reason:null}}));await put(root,'claude/projects/p/r.jsonl',[...rows,{type:'assistant',sessionId:'r',cwd:'/same',message:{id:'pending-0',role:'assistant',content:[{type:'text',text:'Completed `src/end.ts`'}],stop_reason:'end_turn'}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const state=await ix.readReferences('claude',{kind:'id',value:'r'},()=>true);assert.equal(state.limited,true);const page=await ix.pageReferences('claude',{kind:'id',value:'r'},{},()=>true);assert.equal(page.partial,true,'assembly overflow must be distinct from a complete empty source');
});
test('reference history deduplicates mirrors and cancellation never becomes malformed input or a partial result',async t=>{
 const root=await home(t);await put(root,'codex/archived_sessions/r.jsonl',[meta('r'),text('first','`src/a.ts`'),text('shared','`src/b.ts`')]);await put(root,'codex/sessions/r.jsonl',[meta('r'),text('shared','`src/b.ts`'),text('latest','`src/a.ts`')]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();
 const state=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);const a=state.refs.find((r:any)=>r.target===resolve('/same','src','a.ts'));assert.deepEqual(a.sources.map((s:any)=>s.messageId),['first','latest']);assert.equal(a.messageId,'latest');assert.equal(state.refs.find((r:any)=>r.target===resolve('/same','src','b.ts')).sources.length,1);
 assert.ok(Number.isFinite(state.observedAt),'reference existence evidence needs an observation time');const repeated=await ix.readReferences('codex',{kind:'id',value:'r'},()=>true);assert.equal(repeated.observedAt,state.observedAt,'unchanged history must reuse its existence-check evidence');
 const {JsonlTail}=await import('../src/providers/tail.ts');const file=await put(root,'cancel.jsonl',Array.from({length:50},(_,i)=>({count:i})));const tail=new JsonlTail(1024);let active=true;let count=0;const diagnostics:string[]=[];
 await assert.rejects(tail.read(file,()=>{count++;if(count===2)active=false;},()=>{},message=>diagnostics.push(message),()=>active),{name:'AbortError'});assert.equal(count,2);assert.deepEqual(diagnostics,[]);
 let checks=0;assert.equal(await ix.readReferences('codex',{kind:'id',value:'r'},()=>++checks<4),undefined);assert.equal((await ix.readReferences('codex',{kind:'id',value:'r'},()=>true)).refs.length,2);
});

test('exact session IDs isolate same-cwd sessions and retain four explicit Codex descendant levels',async t=>{
 const root=await home(t);
 for(const [id,parent] of [['root',undefined],['child','root'],['grand','child'],['great','grand'],['other',undefined]]) await put(root,`codex/sessions/2026/10/06/rollout-${id}.jsonl`,[meta(id!,parent),text('m',id!)]);
 const ix=index(root); t.after(()=>ix.close()); const all=await ix.refresh();
 assert.equal(all.length,5); assert.equal((await ix.resolve('codex',{kind:'id',value:'grand'}))?.parentId,'child');
 assert.deepEqual((await ix.resolve('codex',{kind:'id',value:'other'}))?.messages.map((m:any)=>m.text),['other']);
 assert.equal(await ix.resolve('codex',{kind:'id',value:'/same'}),undefined);
 assert.deepEqual(all.map((s:any)=>s.id).sort(),['child','grand','great','other','root']);
});
test('Codex excludes hidden content and deduplicates recorded mirrors while preserving tools, edits, model, cache and turn evidence',async t=>{
 const root=await home(t); const file=await put(root,'codex/sessions/a.jsonl',[
 meta('r'),{type:'turn_context',payload:{turn_id:'turn',model:'gpt-test',cwd:'/turn'}},text('u','request','user'),text('secret','hidden','assistant','analysis'),text('sys','instructions','developer'),text('a','visible'),
 {type:'event_msg',payload:{type:'agent_message',message:'visible'}},
 {type:'response_item',payload:{type:'function_call',call_id:'patch',name:'apply_patch',arguments:'*** Begin Patch\n*** Update File: src/é.ts\n@@\n-a\n+b\n*** End Patch'}},
 {type:'response_item',payload:{type:'function_call_output',call_id:'patch',output:'Success. Updated the following files:\nM src/é.ts'}},
 {type:'event_msg',timestamp:'2026-10-06T10:02:00Z',payload:{type:'task_started',turn_id:'turn'}},
 {type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:100,cached_input_tokens:40,output_tokens:5,reasoning_output_tokens:2,total_tokens:105},last_token_usage:{input_tokens:100,cached_input_tokens:40,output_tokens:5,total_tokens:105},model_context_window:200000}}},
 {type:'event_msg',timestamp:'2026-10-06T10:02:02Z',payload:{type:'task_complete',turn_id:'turn'}},
 ]);
 const ix=index(root); t.after(()=>ix.close()); await ix.refresh(); const s=await ix.resolve('codex',{kind:'path',value:file});
 assert.deepEqual(s.messages.filter((m:any)=>m.role!=='tool').map((m:any)=>m.text),['request','visible']); assert.equal(s.model,'gpt-test');
 assert.equal(s.messages[1].cwd,'/turn'); assert.equal(s.tools[0].status,'done'); assert.deepEqual(s.tools[0].editedPaths,['src/é.ts']);
 assert.equal(s.usage[0].input,100); assert.equal(s.usage[0].cacheRead,40); assert.equal(s.usage[0].cacheSemantics,'subset'); assert.equal(s.usage[0].kind,'cumulative');
 assert.equal(s.usage.find((u:any)=>u.turnMs!==undefined).turnMs,2000); assert.equal(s.usage[0].generationMs,undefined); assert.deepEqual(s.goals,[]);
});
test('Codex paired spawn results establish descendants without accepting unrelated session_id results',async t=>{
 const root=await home(t); await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'response_item',payload:{type:'function_call',call_id:'s',name:'spawn_agent',arguments:'{"message":"Build parser"}'}},{type:'response_item',payload:{type:'function_call_output',call_id:'s',output:'{"agent_id":"c"}'}},{type:'response_item',payload:{type:'function_call',call_id:'e',name:'exec_command',arguments:'{}'}},{type:'response_item',payload:{type:'function_call_output',call_id:'e',output:'{"session_id":"unrelated"}'}}]);
 await put(root,'codex/sessions/c.jsonl',[meta('c')]); await put(root,'codex/sessions/unrelated.jsonl',[meta('unrelated')]);
 const ix=index(root);t.after(()=>ix.close());await ix.refresh();assert.equal((await ix.resolve('codex',{kind:'id',value:'c'})).parentId,'r');assert.equal((await ix.resolve('codex',{kind:'id',value:'c'})).task,'Build parser');assert.equal((await ix.resolve('codex',{kind:'id',value:'unrelated'})).parentId,undefined);
});
test('incremental tail defers incomplete records, reports malformed/oversize data, handles truncate and rotation',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),text('a','first')]);const ix=index(root,{maxRecordBytes:1024,maxMessages:2});t.after(()=>ix.close());await ix.refresh();
 await appendFile(file,'{"type":"response_item","payload":'); await ix.refresh();assert.equal((await ix.resolve('codex',{kind:'id',value:'r'})).messages.length,1);
 await appendFile(file,'{"type":"message","id":"b","role":"assistant","content":[{"type":"output_text","text":"second"}]}}\nnot-json\n'+line({noise:'x'.repeat(2000)})+line(text('c','third')));
 await ix.refresh();let s=await ix.resolve('codex',{kind:'id',value:'r'});assert.deepEqual(s.messages.map((m:any)=>m.text),['second','third']);assert.equal(s.availability,'partial');assert.ok(s.diagnostics.some((d:string)=>/malformed/i.test(d)));assert.ok(s.diagnostics.some((d:string)=>/oversize|limit/i.test(d)));
 await writeFile(file,line(meta('r'))+line(text('z','truncated')));await ix.refresh();assert.deepEqual((await ix.resolve('codex',{kind:'id',value:'r'})).messages.map((m:any)=>m.text),['truncated']);
 await rename(file,file+'.old');await writeFile(file,line(meta('new'))+line(text('n','rotated')));await ix.refresh();assert.equal(await ix.resolve('codex',{kind:'id',value:'r'}),undefined);assert.equal((await ix.resolve('codex',{kind:'id',value:'new'})).messages[0].text,'rotated');
 await rm(file);const missing=await ix.resolve('codex',{kind:'id',value:'new'});assert.equal(missing.availability,'unavailable');assert.match(missing.reason,/ENOENT|unavailable|missing/i);
});
test('Claude indexes main and flat nested subagents by explicit paired Agent links and merges streaming identity',async t=>{
 const root=await home(t);
 const assistant=(uuid:string,id:string,content:unknown[],usage?:unknown)=>({type:'assistant',uuid,sessionId:'main',cwd:'/same',timestamp:'2026-10-06T10:00:00Z',requestId:'req',message:{id,role:'assistant',model:'claude-test',content,usage,stop_reason:'end_turn'}});
 await put(root,'claude/projects/project/main.jsonl',[{type:'user',uuid:'u',sessionId:'main',message:{role:'user',content:'initial'}},assistant('a','msg',[{type:'text',text:'Hello'},{type:'thinking',thinking:'secret'},{type:'tool_use',id:'spawn',name:'Agent',input:{prompt:'Nested work'}}],{input_tokens:10,output_tokens:2,cache_read_input_tokens:30,cache_creation_input_tokens:4}),assistant('a2','msg',[{type:'text',text:'Hello world'}],{input_tokens:10,output_tokens:5,cache_read_input_tokens:30,cache_creation_input_tokens:4}),{type:'user',uuid:'tr',sessionId:'main',toolUseResult:{agentId:'child'},message:{role:'user',content:[{type:'tool_result',tool_use_id:'spawn',content:'agentId: child'}]}}]);
 for(const [id,child] of [['child','grand'],['grand','great'],['great',undefined]]) await put(root,`claude/projects/project/main/subagents/agent-${id}.jsonl`,[{type:'user',uuid:'u',sessionId:'main',agentId:id,isSidechain:true,message:{role:'user',content:'task'}},...(child?[assistant('s','smsg',[{type:'tool_use',id:'spawn'+id,name:'Task',input:{prompt:'deeper'}}]),{type:'user',uuid:'r',sessionId:'main',agentId:id,toolUseResult:{agentId:child},message:{role:'user',content:[{type:'tool_result',tool_use_id:'spawn'+id,content:'done'}]}}]:[])]);
 const ix=index(root);t.after(()=>ix.close());const all=await ix.refresh();assert.equal(all.length,4);const s=await ix.resolve('claude',{kind:'id',value:'main'});assert.equal(s.messages.filter((m:any)=>m.role==='assistant').length,1);assert.equal(s.messages.find((m:any)=>m.role==='assistant').text,'Hello world');assert.equal(s.usage.length,1);assert.equal(s.usage[0].output,5);assert.equal(s.usage[0].cacheSemantics,'separate');
 assert.equal((await ix.resolve('claude',{kind:'id',value:'child'})).parentId,'main');assert.equal((await ix.resolve('claude',{kind:'id',value:'grand'})).parentId,'child');assert.equal((await ix.resolve('claude',{kind:'id',value:'great'})).parentId,'grand');assert.equal(s.goals.length,0);
});
test('Pi header IDs and canonical paths resolve exactly; ordinary forks do not fabricate delegated children',async t=>{
 const root=await home(t);const parent=await put(root,'pi/sessions/project/parent.jsonl',[{type:'session',version:3,id:'p',cwd:'/same',timestamp:'2026-10-06T09:00:00Z'}]);
 const file=await put(root,'pi/sessions/project/fork.jsonl',[{type:'session',version:3,id:'f',cwd:'/same',parentSession:parent},{type:'session_info',id:'info',name:'Fork'},{type:'model_change',id:'model',provider:'anthropic',modelId:'pi-model'},{type:'message',id:'m',timestamp:'2026-10-06T10:00:00Z',message:{role:'assistant',model:'pi-model',content:[{type:'thinking',thinking:'hidden'},{type:'text',text:'Read src/x.ts'}],usage:{input:10,output:2,cacheRead:30,cacheWrite:5,totalTokens:47},stopReason:'stop'}}]);
 await symlink(file,join(root,'alias.jsonl'));const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=await ix.resolve('pi',{kind:'path',value:join(root,'alias.jsonl')});assert.equal(s.id,'f');assert.equal(s.title,'Fork');assert.equal(s.parentId,undefined);assert.ok(s.diagnostics.some((d:string)=>/fork/i.test(d)));assert.equal(s.messages[0].text,'Read src/x.ts');assert.equal(s.usage[0].cacheSemantics,'separate');assert.equal(s.usage[0].total,47);
 assert.equal((await ix.resolve('pi',{kind:'id',value:'p'})).id,'p');
});
test('versioned explicit Pi companion facts separate goal/task from prompts and reject future schemas',async t=>{
 const root=await home(t);await put(root,'pi/sessions/r.jsonl',[{type:'session',version:3,id:'r',cwd:'/same'}]);await put(root,'pi/sessions/c.jsonl',[{type:'session',version:3,id:'c',cwd:'/same'},{type:'custom',id:'e',customType:'iob.herdr-prism',data:{version:1,kind:'delegation',parent:{provider:'pi',id:'r'},task:'Build tests'}},{type:'custom',id:'g',customType:'iob.herdr-prism',data:{version:1,kind:'goal',id:'goal',objective:'Ship',status:'active'}},{type:'custom',id:'bad',customType:'iob.herdr-prism',data:{version:99,kind:'goal',objective:'Wrong'}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=await ix.resolve('pi',{kind:'id',value:'c'});assert.equal(s.parentId,'r');assert.equal(s.task,'Build tests');assert.equal(s.goals.length,1);assert.equal(s.goals[0].objective,'Ship');assert.ok(s.diagnostics.some((d:string)=>/version/i.test(d)));
});
test('untrusted transcript controls are inert and unsupported Pi schemas are explicitly partial',async t=>{
 const root=await home(t);await put(root,'pi/sessions/r.jsonl',[{type:'session',version:999,id:'r',cwd:'/same'},{type:'message',id:'m',message:{role:'assistant',content:[{type:'text',text:'\u001b]52;c;evil\u0007Safe\u0000'}]}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=await ix.resolve('pi',{kind:'id',value:'r'});assert.equal(s.availability,'partial');assert.equal(s.messages.length,0);assert.ok(s.diagnostics.some((d:string)=>/version/i.test(d)));
});
test('older messages page outside the hot window and cached exact resolution does not rescan the homes',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),text('a','oldest'),text('b','middle'),text('c','latest')]);const ix=index(root,{maxMessages:1});t.after(()=>ix.close());await ix.refresh();assert.equal((await ix.resolve('codex',{kind:'id',value:'r'})).messages.length,1);
 assert.equal(typeof ix.page,'function');assert.equal(typeof ix.readMessage,'function');assert.equal(typeof ix.resolveCached,'function');
 const page=await ix.page('codex',{kind:'id',value:'r'},{beforeId:'c',limit:2});assert.deepEqual(page.map((m:any)=>m.id),['a','b']);assert.equal((await ix.readMessage('codex',{kind:'id',value:'r'},'a')).text,'oldest');
 await appendFile(file,line(text('d','not refreshed')));assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).messages[0].id,'c');await ix.refresh();assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).messages[0].id,'d');
});
test('successful Codex goal tool results establish explicit goal state while failed requests and plan tools do not',async t=>{
 const root=await home(t);const goal={threadId:'r',objective:'Ship parser',status:'active',tokensUsed:5,timeUsedSeconds:1,createdAt:1791280800,updatedAt:1791280800};await put(root,'codex/sessions/r.jsonl',[meta('r'),text('prompt','Do something','user'),{type:'response_item',payload:{type:'function_call',call_id:'g',name:'create_goal',arguments:'{"objective":"Ship parser"}'}},{type:'response_item',payload:{type:'function_call_output',call_id:'g',output:JSON.stringify({goal})}},{type:'response_item',payload:{type:'function_call',call_id:'u',name:'update_goal',arguments:'{"status":"complete"}'}},{type:'response_item',payload:{type:'function_call_output',call_id:'u',output:JSON.stringify({goal:{...goal,status:'complete'}})}},{type:'response_item',payload:{type:'function_call',call_id:'fail',name:'create_goal',arguments:'{"objective":"Wrong"}'}},{type:'response_item',payload:{type:'function_call_output',call_id:'fail',output:'{"error":"already active"}'}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=await ix.resolve('codex',{kind:'id',value:'r'});assert.equal(s.goals.length,1);assert.equal(s.goals[0].objective,'Ship parser');assert.equal(s.goals[0].status,'complete');
});
test('Pi companion only emits versioned state and explicitly submitted goal/delegation records',async()=>{
 const companion=await import('../companion/pi/index.ts').catch(()=>({})) as any;assert.equal(typeof companion.default,'function');const records:any[]=[];const commands=new Map<string,any>();const events=new Map<string,any>();
 companion.default({appendEntry:(customType:string,data:any)=>records.push({customType,data}),registerCommand:(name:string,command:any)=>commands.set(name,command),on:(name:string,handler:any)=>events.set(name,handler)});
 assert.equal(records.length,0);await commands.get('prism-goal').handler('Ship parser');await commands.get('prism-parent').handler('{"provider":"codex","id":"root","task":"Build parser"}');await events.get('agent_start')({});
 assert.deepEqual(records.map(r=>[r.customType,r.data.version,r.data.kind]),[['iob.herdr-prism',1,'goal'],['iob.herdr-prism',1,'delegation'],['iob.herdr-prism',1,'state']]);assert.equal(records[0].data.objective,'Ship parser');assert.equal(records[1].data.parent.id,'root');
 assert.throws(()=>commands.get('prism-parent').handler('{"id":""}'),/parent|delegation/i);
});
test('Pi version-one headers, auxiliary usage records and visible custom messages honor current source schemas',async t=>{
 const root=await home(t);await put(root,'pi/sessions/r.jsonl',[{type:'session',id:'r',cwd:'/same'},{type:'usage',id:'aux',kind:'cache_warm',model:'test',usage:{input:10,output:0,cacheRead:2,cacheWrite:4,totalTokens:16}},{type:'custom_message',id:'v',customType:'notice',content:'Visible notice',display:true},{type:'custom_message',id:'h',customType:'hidden',content:'Secret',display:false}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=await ix.resolve('pi',{kind:'id',value:'r'});assert.equal(s.availability,'known');assert.equal(s.usage[0].total,16);assert.deepEqual(s.messages.map((m:any)=>m.text),['Visible notice']);
});
test('Claude assembles split text and tool blocks before an ACTION report is complete and omits incomplete usage fields',async t=>{
 const root=await home(t);const base={type:'assistant',sessionId:'r',requestId:'request',message:{id:'message',role:'assistant',model:'claude-test'}};const file=await put(root,'claude/projects/p/r.jsonl',[{...base,uuid:'block1',message:{...base.message,content:[{type:'text',text:'ACTION: First'}],stop_reason:null,usage:{input_tokens:10,output_tokens:2}}},{...base,uuid:'block2',message:{...base.message,content:[{type:'text',text:'ACTION: Second'}],stop_reason:null,usage:{output_tokens:4}}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();let s=await ix.resolve('claude',{kind:'id',value:'r'});assert.equal(s.messages[0].text,'ACTION: First\nACTION: Second');assert.equal(s.messages[0].complete,false);
 await appendFile(file,line({...base,uuid:'block3',message:{...base.message,content:[{type:'tool_use',id:'t',name:'Read',input:{file_path:'src/x.ts'}}],stop_reason:'tool_use',usage:{output_tokens:5}}}));await ix.refresh();s=await ix.resolve('claude',{kind:'id',value:'r'});assert.equal(s.messages[0].text,'ACTION: First\nACTION: Second');assert.equal(s.messages[0].complete,true);assert.equal(s.messages[0].tools.length,1);assert.equal(s.usage[0].input,10);assert.equal(s.usage[0].output,5);
});
test('Codex duplicate archive mirrors retain exact messages once and preserve older rollout evidence',async t=>{
 const root=await home(t);await put(root,'codex/archived_sessions/r.jsonl',[meta('r'),text('a','old'),text('b','shared')]);await put(root,'codex/sessions/r.jsonl',[meta('r'),text('b','shared'),text('c','new')]);const ix=index(root);t.after(()=>ix.close());const all=await ix.refresh();assert.equal(all.length,1);assert.deepEqual(all[0].messages.map((m:any)=>m.id),['a','b','c']);assert.equal((await ix.readMessage('codex',{kind:'id',value:'r'},'a')).text,'old');assert.deepEqual((await ix.page('codex',{kind:'id',value:'r'},{beforeId:'c',limit:2})).map((m:any)=>m.id),['a','b']);
});
test('a late tool result preserves the call turn cwd instead of another active turn cwd',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'turn_context',payload:{cwd:'/first'}},{type:'response_item',payload:{type:'function_call',call_id:'w',name:'Write',arguments:'{"file_path":"src/a.ts"}'}},{type:'turn_context',payload:{cwd:'/second'}},{type:'response_item',payload:{type:'function_call_output',call_id:'w',output:'success'}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();assert.equal((await ix.resolve('codex',{kind:'id',value:'r'})).messages[0].cwd,'/first');
});
test('Codex child inherited history ordinal excludes inherited parent messages and stable root accounting ID does not merge children',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),text('u','parent request','user')]);const header=meta('c','r');await put(root,'codex/sessions/c.jsonl',[{...header,payload:{...header.payload,session_id:'r',subagent_history_start_ordinal:3}},text('u','parent request','user'),text('old','parent answer'),text('new','child answer')]);const ix=index(root);t.after(()=>ix.close());const all=await ix.refresh();assert.equal(all.length,2);assert.deepEqual((await ix.resolve('codex',{kind:'id',value:'c'})).messages.map((m:any)=>m.text),['child answer']);
});
test('directory inventory scans are cached while known session tails still refresh between scans',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),text('a','first')]);const ix=index(root,{directoryScanMs:60000});t.after(()=>ix.close());await ix.refresh();await put(root,'codex/sessions/new.jsonl',[meta('new')]);await appendFile(file,line(text('b','tail')));const all=await ix.refresh();assert.deepEqual(all.map((s:any)=>s.id),['r']);assert.equal(all[0].messages[1].text,'tail');
});
test('reported cwd preserves newline spelling for file resolution while terminal controls remain sanitized',async t=>{
 const root=await home(t);const header=meta('r');await put(root,'codex/sessions/r.jsonl',[{...header,payload:{...header.payload,cwd:'/repo/line\nbreak'}},text('a','Safe\u001b]52;c;evil\u0007 `src/x.ts`\u0000')]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=await ix.resolve('codex',{kind:'id',value:'r'});assert.equal(s.cwd,'/repo/line\nbreak');assert.equal(s.messages[0].cwd,'/repo/line\nbreak');assert.equal(s.messages[0].text,'Safe `src/x.ts`');
});
test('scoped provider collection reads active exact sessions and deep descendants, retaining unrelated metadata without parsing bodies',async t=>{
 const root=await home(t);for(const [id,parent] of [['r',undefined],['c','r'],['g','c'],['deep','g']])await put(root,`codex/sessions/${id}.jsonl`,[meta(id!,parent),text('m',id!)]);await put(root,'codex/archived_sessions/unrelated.jsonl',[meta('unrelated'),text('secret','Private unrelated body')]);await appendFile(join(root,'codex/archived_sessions/unrelated.jsonl'),'malformed body record\n');const ix=index(root);t.after(()=>ix.close());assert.equal(typeof ix.setActiveRefs,'function');ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);const all=await ix.refresh();assert.equal(all.find((s:any)=>s.id==='deep').messages[0].text,'deep');const unrelated=all.find((s:any)=>s.id==='unrelated');assert.equal(unrelated.messages.length,0);assert.ok(!unrelated.diagnostics.some((d:string)=>/malformed/i.test(d)));
 ix.setActiveRefs([{provider:'codex',kind:'id',value:'unrelated'}]);await ix.refresh();assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).messages.length,0);assert.equal(ix.resolveCached('codex',{kind:'id',value:'unrelated'}).messages[0].text,'Private unrelated body');
});
test('scoped exact Pi and Claude sessions discover explicit children without parsing unrelated same-cwd histories',async t=>{
 const root=await home(t);const piParent=await put(root,'pi/sessions/p.jsonl',[{type:'session',version:3,id:'p',cwd:'/same'}]);await put(root,'pi/sessions/c.jsonl',[{type:'session',version:3,id:'c',cwd:'/same',parentSession:piParent},{type:'custom',id:'d',customType:'iob.herdr-prism',data:{version:1,kind:'delegation',parent:{provider:'pi',id:'p'},task:'child'}},{type:'message',id:'m',message:{role:'assistant',content:[{type:'text',text:'Pi child'}]}}]);await put(root,'pi/sessions/ordinary.jsonl',[{type:'session',version:3,id:'fork',cwd:'/same',parentSession:piParent},{type:'message',id:'private',message:{role:'assistant',content:[{type:'text',text:'Unrelated fork'}]}}]);await put(root,'claude/projects/p/r.jsonl',[{type:'user',uuid:'u',sessionId:'r',message:{role:'user',content:'root'}}]);await put(root,'claude/projects/p/r/subagents/agent-c.jsonl',[{type:'assistant',uuid:'a',sessionId:'r',agentId:'c',message:{id:'a',role:'assistant',content:[{type:'text',text:'Claude child'}],stop_reason:'end_turn'}}]);const ix=index(root);t.after(()=>ix.close());ix.setActiveRefs([{provider:'pi',kind:'path',value:piParent},{provider:'claude',kind:'id',value:'r'}]);await ix.refresh();assert.equal(ix.resolveCached('pi',{kind:'id',value:'c'}).messages[0].text,'Pi child');assert.equal(ix.resolveCached('pi',{kind:'id',value:'fork'}).messages.length,0);assert.equal(ix.resolveCached('claude',{kind:'id',value:'c'}).messages[0].text,'Claude child');
});
test('Pi companion repeats explicit delegated identity at agent boundaries for bounded metadata discovery',async()=>{
 const companion=await import('../companion/pi/index.ts') as any;const records:any[]=[];const commands=new Map<string,any>();const events=new Map<string,any>();companion.default({appendEntry:(_:string,data:any)=>records.push(data),registerCommand:(name:string,command:any)=>commands.set(name,command),on:(name:string,handler:any)=>events.set(name,handler)});commands.get('prism-parent').handler('{"provider":"pi","id":"p","task":"child"}');events.get('agent_end')({});assert.deepEqual(records.at(-1).parent,{provider:'pi',id:'p'});assert.equal(records.at(-1).task,'child');
});
test('Pi companion session changes clear previous delegation and restore only explicit current-session facts',async()=>{
 const companion=await import('../companion/pi/index.ts') as any;const records:any[]=[];const commands=new Map<string,any>();const events=new Map<string,any>();companion.default({appendEntry:(_:string,data:any)=>records.push(data),registerCommand:(name:string,command:any)=>commands.set(name,command),on:(name:string,handler:any)=>events.set(name,handler)});commands.get('prism-parent').handler('{"provider":"pi","id":"old"}');assert.equal(typeof events.get('session_start'),'function');events.get('session_start')({reason:'new'},{sessionManager:{getEntries:()=>[]}});events.get('agent_start')({});assert.equal(records.at(-1).parent,undefined);events.get('session_start')({reason:'resume'},{sessionManager:{getEntries:()=>[{type:'custom',customType:'iob.herdr-prism',data:{version:1,kind:'delegation',parent:{provider:'codex',id:'restored'},task:'work'}}]}});events.get('agent_end')({});assert.equal(records.at(-1).parent.id,'restored');
});
test('a saturated generic inventory cannot starve active exact paths or IDs across providers',async t=>{
 const root=await home(t);await put(root,'codex/sessions/old.jsonl',[meta('old')]);const current=await put(root,'codex/sessions/zzz-active.jsonl',[meta('active'),text('m','current')]);await put(root,'claude/projects/p/c.jsonl',[{type:'user',uuid:'u',sessionId:'c',message:{role:'user',content:'Claude'}}]);const pi=await put(root,'pi/sessions/p.jsonl',[{type:'session',version:3,id:'p',cwd:'/same'}]);const ix=index(root,{maxSessions:1});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'path',value:current},{provider:'claude',kind:'id',value:'c'},{provider:'pi',kind:'path',value:pi}]);await ix.refresh();assert.equal(ix.resolveCached('codex',{kind:'id',value:'active'})?.messages[0]?.text,'current');assert.equal(ix.resolveCached('claude',{kind:'id',value:'c'})?.messages[0]?.text,'Claude');assert.equal(ix.resolveCached('pi',{kind:'id',value:'p'})?.id,'p');
 const ids=index(root,{maxSessions:1});t.after(()=>ids.close());ids.setActiveRefs([{provider:'codex',kind:'id',value:'active'}]);await ids.refresh();assert.equal(ids.resolveCached('codex',{kind:'id',value:'active'})?.messages[0]?.text,'current');
});
test('changing active refs uses the cached metadata index immediately without another directory scan',async t=>{
 const root=await home(t);await put(root,'codex/sessions/a.jsonl',[meta('a'),text('a','first')]);await put(root,'codex/sessions/b.jsonl',[meta('b'),text('b','second')]);const ix=index(root,{maxSessions:1,directoryScanMs:60000});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'a'}]);await ix.refresh();ix.setActiveRefs([{provider:'codex',kind:'id',value:'b'}]);await ix.refresh();assert.equal(ix.resolveCached('codex',{kind:'id',value:'b'})?.messages[0]?.text,'second');
 const external=await put(root,'custom-dir/pi.jsonl',[{type:'session',version:3,id:'external',cwd:'/work'}]);ix.setActiveRefs([{provider:'pi',kind:'path',value:external}]);await ix.refresh();assert.equal(ix.resolveCached('pi',{kind:'id',value:'external'})?.id,'external');
});
test('Codex cumulative thread counters retain one epoch across model changes and timing-only records',async t=>{
 const root=await home(t);const usage=(input:number,output:number)=>({type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:input,output_tokens:output,total_tokens:input+output},last_token_usage:{input_tokens:20,output_tokens:10},model_context_window:200000}}});await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'turn_context',payload:{model:'first'}},usage(100,10),{type:'turn_context',payload:{model:'second'}},usage(120,20),{type:'event_msg',payload:{type:'task_complete',turn_id:'t',duration_ms:2000}}]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.usage[0].epoch,s.usage[1].epoch);const {reduceUsage}=await import('../src/metrics/usage-reducer.ts');const totals=reduceUsage(s.usage);assert.equal(totals.input,120);assert.equal(totals.output,20);assert.equal(totals.total,140);assert.equal(totals.availability,'known');
});
test('lazy ACTION history restores the current list and first source beyond the hot window without retaining old message bodies',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),text('first','ACTION: Run `npm test`'),text('latest','ACTION: Run `npm test`\nACTION: Review release'),...Array.from({length:250},(_,i)=>text('later'+i,'No report '+i))]);const ix=index(root,{maxMessages:200});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);await ix.refresh();assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).messages.length,200);assert.equal(typeof ix.readTodoState,'function');const state=await ix.readTodoState('codex',{kind:'id',value:'r'});assert.equal(state.hasReport,true);assert.equal(state.current.length,2);assert.equal(state.sourceMessageId,'latest');assert.equal(state.items.find((i:any)=>i.text==='Run `npm test`').firstMessageId,'first');assert.ok(!JSON.stringify(state).includes('No report'));assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).messages.length,200);
 await rm(join(root,'codex/sessions/r.jsonl'));assert.equal(await ix.readTodoState('codex',{kind:'id',value:'r'}),undefined);
});
test('unpaired tool results remain visible with unknown call provenance and ACTION replay diagnostics remain bounded',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'response_item',payload:{type:'function_call_output',call_id:'missing',output:'Visible result'}}]);await appendFile(file,'malformed\n'.repeat(100));const ix=index(root);t.after(()=>ix.close());await ix.refresh();const s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.messages[0]?.text,'Visible result');assert.equal(s.tools[0]?.name,'unknown');assert.equal(s.availability,'partial');const state=await ix.readTodoState('codex',{kind:'id',value:'r'});assert.equal(state.hasReport,false);assert.ok(state.diagnostics.length<=64);
});
test('active exact session preserves first user request beyond the hot cap and resets it on rotation without creating a goal',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),text('first','Original request','user'),...Array.from({length:220},(_,i)=>text('a'+i,'reply'))]);const ix=index(root,{maxMessages:200});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);await ix.refresh();let s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.initialRequest?.id,'first');assert.equal(s.initialRequest.text,'Original request');assert.ok(s.initialRequest.source.includes('#'));assert.equal(s.messages.length,200);assert.equal(s.goals.length,0);
 ix.setActiveRefs([]);await ix.refresh();assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).initialRequest,undefined);ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);await rename(file,file+'.old');await writeFile(file,line(meta('r'))+line(text('new','Replacement request','user')));await ix.refresh();s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.initialRequest.text,'Replacement request');
});
test('exact session archive merging preserves the earliest evidenced initial user request',async t=>{
 const root=await home(t);await put(root,'codex/archived_sessions/old.jsonl',[meta('r'),{...text('first','Original request','user'),timestamp:'2026-10-06T09:00:00Z'}]);await put(root,'codex/sessions/current.jsonl',[meta('r'),{...text('later','Later request','user'),timestamp:'2026-10-06T11:00:00Z'}]);const ix=index(root);t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);await ix.refresh();assert.equal(ix.resolveCached('codex',{kind:'id',value:'r'}).initialRequest?.id,'first');
});
test('Codex explicit active turn survives messages and old completions, then clears only its matching boundary',async t=>{
 const root=await home(t);const event=(type:string,turn:string,at:string,extra={})=>({type:'event_msg',timestamp:at,payload:{type,turn_id:turn,...extra}});const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),event('task_started','t1','2026-10-06T10:02:00Z'),text('a','Still working')]);const ix=index(root);t.after(()=>ix.close());await ix.refresh();let s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.activeTurn?.id,'t1');assert.equal(s.activeTurn?.startedAt,Date.parse('2026-10-06T10:02:00Z'));assert.ok(s.activeTurn?.source.endsWith('#'+line(meta('r')).length));
 await appendFile(file,line(event('task_complete','t0','2026-10-06T10:02:05Z')));await ix.refresh();s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.activeTurn?.id,'t1');assert.equal(s.state,'running');assert.ok(!s.usage.some((u:any)=>u.turnId==='t0'&&u.turnMs!==undefined));
 await appendFile(file,line(event('turn_complete','t1','2026-10-06T10:02:10Z')));await ix.refresh();s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.activeTurn,undefined);assert.equal(s.state,'done');assert.equal(s.usage.find((u:any)=>u.turnId==='t1').turnMs,10000);
 await appendFile(file,line(event('turn_started','t2','2026-10-06T10:03:00Z'))+line(event('turn_aborted','t2','2026-10-06T10:03:01Z')));await ix.refresh();s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.activeTurn,undefined);assert.equal(s.state,'interrupted');
 await appendFile(file,line({type:'event_msg',payload:{type:'task_started',turn_id:'t3'}})+line(event('task_complete','t2','2026-10-06T10:03:02Z')));await ix.refresh();s=ix.resolveCached('codex',{kind:'id',value:'r'});assert.equal(s.activeTurn,undefined);assert.equal(s.state,'running');
});
test('unchanged normalized snapshots are cached, immutable opt-in snapshots are safe, and each real source change invalidates revision',async t=>{
 const {EvidenceBuilder}=await import('../src/providers/common.ts');const original=EvidenceBuilder.prototype.snapshot;let snapshots=0;EvidenceBuilder.prototype.snapshot=function(){snapshots++;return original.call(this);};t.after(()=>{EvidenceBuilder.prototype.snapshot=original;});const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),text('a','First')]);await put(root,'codex/archived_sessions/r.jsonl',[meta('r'),text('archive','Archived')]);await put(root,'codex/sessions/c.jsonl',[meta('c')]);const ix=index(root,{directoryScanMs:60000});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);const first=await ix.refresh();assert.ok(first.find((s:any)=>s.id==='r').contentRevision);const before=snapshots;const second=await ix.refresh();assert.equal(snapshots,before,'unchanged files should not normalize snapshots again');assert.equal(first.find((s:any)=>s.id==='r').contentRevision,second.find((s:any)=>s.id==='r').contentRevision);first.find((s:any)=>s.id==='r').messages[0].text='Corrupted caller';assert.ok(!ix.resolveCached('codex',{kind:'id',value:'r'}).messages.some((m:any)=>m.text==='Corrupted caller'));
 assert.equal(typeof ix.refreshSnapshots,'function');const immutable=await ix.refreshSnapshots();const stable=await ix.refreshSnapshots();assert.equal(immutable,stable);assert.ok(Object.isFrozen(immutable));assert.ok(Object.isFrozen(immutable.find((s:any)=>s.id==='r').messages[0]));assert.throws(()=>{immutable.find((s:any)=>s.id==='r').messages[0].text='No';},TypeError);
 const version=immutable.find((s:any)=>s.id==='r').contentRevision;await appendFile(file,line(text('b','Appended')).slice(0,-1));assert.equal((await ix.refreshSnapshots()).find((s:any)=>s.id==='r').contentRevision,version,'a partial line is not normalized content');await appendFile(file,'\n');const appended=await ix.refreshSnapshots();assert.notEqual(appended.find((s:any)=>s.id==='r').contentRevision,version);assert.ok(appended.find((s:any)=>s.id==='r').messages.some((m:any)=>m.text==='Appended'));
 const appendedVersion=appended.find((s:any)=>s.id==='r').contentRevision;await appendFile(file,'malformed\n');const malformed=await ix.refreshSnapshots();assert.notEqual(malformed.find((s:any)=>s.id==='r').contentRevision,appendedVersion);assert.ok(malformed.find((s:any)=>s.id==='r').diagnostics.some((s:string)=>s.includes('malformed')));
 await appendFile(file,line({type:'response_item',payload:{type:'function_call',call_id:'spawn',name:'spawn_agent',arguments:'{"message":"Child task"}'}})+line({type:'response_item',payload:{type:'function_call_output',call_id:'spawn',output:'{"agent_id":"c"}'}}));const linked=await ix.refreshSnapshots();assert.equal(linked.find((s:any)=>s.id==='c').parentId,'r');assert.equal(linked.find((s:any)=>s.id==='c').task,'Child task');ix.setActiveRefs([]);const inactive=await ix.refreshSnapshots();assert.equal(inactive.find((s:any)=>s.id==='r').messages.length,0);assert.notEqual(inactive.find((s:any)=>s.id==='r').contentRevision,linked.find((s:any)=>s.id==='r').contentRevision);
 ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);await rename(file,file+'.old');await writeFile(file,line(meta('r'))+line(text('replacement','Replacement')));const replaced=await ix.refreshSnapshots();assert.ok(replaced.find((s:any)=>s.id==='r').messages.some((m:any)=>m.text==='Replacement'));assert.ok(!replaced.find((s:any)=>s.id==='r').messages.some((m:any)=>m.text==='Appended'));assert.ok(replaced.find((s:any)=>s.id==='r').messages.some((m:any)=>m.text==='Archived'));
});
test('explicit detailed refs hydrate only visible exact session while background appends stay unread until selection',async t=>{
 const {CodexAdapter}=await import('../src/providers/codex.ts');const original=CodexAdapter.prototype.consume;const bodies:string[]=[];CodexAdapter.prototype.consume=function(record){if(record.record.type==='response_item')bodies.push(this.evidence.id);return original.call(this,record);};t.after(()=>{CodexAdapter.prototype.consume=original;});const root=await home(t);const a=await put(root,'codex/sessions/a.jsonl',[meta('a'),text('a1','A first')]);const b=await put(root,'codex/sessions/b.jsonl',[meta('b'),text('b1','B first')]);await put(root,'codex/sessions/c.jsonl',[meta('c','a'),text('c1','Child hidden')]);const ix=index(root,{directoryScanMs:60000});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'a'},{provider:'codex',kind:'id',value:'b'}]);assert.equal(typeof ix.setDetailedRefs,'function');ix.setDetailedRefs([]);let all=await ix.refreshSnapshots();assert.deepEqual(bodies,[]);assert.ok(all.every((s:any)=>s.messages.length===0));assert.equal(all.find((s:any)=>s.id==='c').parentId,'a');ix.setDetailedRefs([{provider:'codex',kind:'id',value:'a'}]);all=await ix.refreshSnapshots();assert.deepEqual(bodies,['a']);assert.equal(all.find((s:any)=>s.id==='a').messages[0]?.text,'A first');assert.equal(all.find((s:any)=>s.id==='b').messages.length,0);assert.equal(all.find((s:any)=>s.id==='c').messages.length,0);
 await appendFile(b,line(text('b2','B appended')));await appendFile(a,line(text('a2','A appended')));all=await ix.refreshSnapshots();assert.deepEqual(bodies,['a','a']);assert.equal(all.find((s:any)=>s.id==='a').messages.at(-1)?.text,'A appended');assert.equal(all.find((s:any)=>s.id==='b').messages.length,0);ix.setDetailedRefs([{provider:'codex',kind:'path',value:b}]);all=await ix.refreshSnapshots();assert.deepEqual(bodies,['a','a','b','b']);assert.equal(all.find((s:any)=>s.id==='a').messages.length,0);assert.equal(all.find((s:any)=>s.id==='b').messages.at(-1)?.text,'B appended');assert.equal(typeof ix.resolveSnapshotCached,'function');const source=ix.resolveSnapshotCached('codex',{kind:'id',value:'b'});assert.equal(source,all.find((s:any)=>s.id==='b'));assert.ok(Object.isFrozen(source.messages));ix.setDetailedRefs([]);await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'b'}).messages.length,0);
 ix.setActiveRefs([]);ix.setDetailedRefs([{provider:'codex',kind:'path',value:a}]);all=await ix.refreshSnapshots();assert.equal(all.find((s:any)=>s.id==='a').messages.at(-1)?.text,'A appended','historical exact selection hydrates without a live attachment');
});
test('previously observed explicit spawn lineage survives closing detailed hydration without retaining message bodies',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'response_item',payload:{type:'function_call',call_id:'s',name:'spawn_agent',arguments:'{"message":"Delegated task"}'}},{type:'response_item',payload:{type:'function_call_output',call_id:'s',output:'{"agent_id":"c"}'}}]);await put(root,'codex/sessions/c.jsonl',[meta('c'),text('hidden','Child body')]);const ix=index(root);t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);ix.setDetailedRefs([{provider:'codex',kind:'id',value:'r'}]);await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'c'}).parentId,'r');ix.setDetailedRefs([]);await ix.refreshSnapshots();const child=ix.resolveSnapshotCached('codex',{kind:'id',value:'c'});assert.equal(child.parentId,'r');assert.equal(child.task,'Delegated task');assert.equal(child.messages.length,0);assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'r'}).messages.length,0);
});
test('metadata rescans reuse unchanged stat identities and invalidate append, same-length rewrite and rotation',async t=>{
 const {CodexAdapter}=await import('../src/providers/codex.ts');const original=CodexAdapter.prototype.consume;let headers=0;CodexAdapter.prototype.consume=function(record){if(record.record.type==='session_meta')headers++;return original.call(this,record);};t.after(()=>{CodexAdapter.prototype.consume=original;});const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),text('a','First')]);const ix=index(root,{directoryScanMs:0});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'path',value:file}]);ix.setDetailedRefs([]);await ix.refreshSnapshots();const initial=headers;await ix.refreshSnapshots();assert.equal(headers,initial,'unchanged metadata should not be decoded again');await appendFile(file,line(text('b','New body')));await ix.refreshSnapshots();assert.equal(headers,initial+1);const beforeRewrite=await stat(file,{bigint:true});await writeFile(file,line(meta('z'))+line(text('a','First'))+line(text('b','New body')));/* Same-length replacement must change the cache's observable stat identity, including on coarse/lazy Windows timestamps. */const changedTime=new Date(Number(beforeRewrite.mtimeMs)+2000);await utimes(file,changedTime,changedTime);const afterRewrite=await stat(file,{bigint:true});assert.equal(afterRewrite.size,beforeRewrite.size);assert.notEqual(afterRewrite.mtimeNs,beforeRewrite.mtimeNs);await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'z'}).id,'z');assert.equal(headers,initial+2);await rename(file,file+'.old');await writeFile(file,line(meta('r')));await ix.refreshSnapshots();assert.equal(headers,initial+3);assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'r'}).id,'r');
});
test('detailed path selection hydrates the selected logical session archives while other sessions remain metadata only',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),{...text('later','Later request','user'),timestamp:'2026-10-06T11:00:00Z'}]);await put(root,'codex/archived_sessions/r.jsonl',[meta('r'),{...text('first','Original request','user'),timestamp:'2026-10-06T09:00:00Z'}]);await put(root,'codex/sessions/other.jsonl',[meta('other'),text('hidden','Other body')]);const ix=index(root);t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'path',value:file}]);ix.setDetailedRefs([{provider:'codex',kind:'path',value:file}]);await ix.refreshSnapshots();const selected=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'});assert.equal(selected.initialRequest?.id,'first');assert.deepEqual(selected.messages.map((m:any)=>m.id),['first','later']);assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'other'}).messages.length,0);
});
test('Pi bounded companion metadata is reused on unchanged rescan and refreshed on a new explicit fact without reading bodies',async t=>{
 const {PiAdapter}=await import('../src/providers/pi.ts');const original=PiAdapter.prototype.consume;let consumed=0;let bodies=0;PiAdapter.prototype.consume=function(record){consumed++;if(record.record.type==='message')bodies++;return original.call(this,record);};t.after(()=>{PiAdapter.prototype.consume=original;});const root=await home(t);const fact=(id:string)=>({type:'custom',customType:'iob.herdr-prism',data:{version:1,kind:'state',state:'idle',parent:{provider:'codex',id}}});const file=await put(root,'pi/sessions/r.jsonl',[{type:'session',version:3,id:'p',cwd:'/same'},{type:'message',id:'body',message:{role:'assistant',content:'x'.repeat(80000)}},fact('parent1')]);const ix=index(root,{directoryScanMs:0});t.after(()=>ix.close());ix.setActiveRefs([{provider:'pi',kind:'id',value:'p'}]);ix.setDetailedRefs([]);await ix.refreshSnapshots();const first=consumed;assert.equal(ix.resolveSnapshotCached('pi',{kind:'id',value:'p'}).parentId,'parent1');await ix.refreshSnapshots();assert.equal(consumed,first);await appendFile(file,line(fact('parent2')));await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('pi',{kind:'id',value:'p'}).parentId,'parent2');assert.ok(consumed>first);assert.equal(bodies,0);
});
test('explicit parent edges retain their original header or paired spawn result sources',async t=>{
 const root=await home(t);const parent=await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'response_item',payload:{type:'function_call',call_id:'s',name:'spawn_agent',arguments:'{"message":"Task"}'}},{type:'response_item',payload:{type:'function_call_output',call_id:'s',output:'{"agent_id":"c"}'}}]);const header=await put(root,'codex/sessions/h.jsonl',[meta('h','r')]);await put(root,'codex/sessions/c.jsonl',[meta('c')]);const claude=await put(root,'claude/projects/project/a.jsonl',[{sessionId:'a',parentAgentId:'r',cwd:'/same',type:'user',message:{role:'user',content:'Request'}}]);const pi=await put(root,'pi/sessions/p.jsonl',[{type:'session',id:'p',version:3},{type:'custom',customType:'iob.herdr-prism',data:{version:1,kind:'delegation',parent:{provider:'codex',id:'r'},task:'Pi task'}}]);const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();assert.ok(ix.resolveSnapshotCached('codex',{kind:'id',value:'h'}).parentSource?.endsWith('h.jsonl#0'));const child=ix.resolveSnapshotCached('codex',{kind:'id',value:'c'});assert.equal(child.parentId,'r');assert.ok(child.parentSource?.endsWith('r.jsonl#'+(line(meta('r')).length+line({type:'response_item',payload:{type:'function_call',call_id:'s',name:'spawn_agent',arguments:'{"message":"Task"}'}}).length)));assert.ok(ix.resolveSnapshotCached('claude',{kind:'id',value:'a'}).parentSource?.endsWith('a.jsonl#0'));assert.ok(ix.resolveSnapshotCached('pi',{kind:'id',value:'p'}).parentSource?.includes('p.jsonl#'));ix.setActiveRefs([{provider:'codex',kind:'id',value:'r'}]);ix.setDetailedRefs([]);await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'c'}).parentSource,child.parentSource);
});
test('cached exact path aliases resolve without fallback reads and follow explicit alias retargeting',async t=>{
 const root=await home(t);const a=await put(root,'codex/sessions/a.jsonl',[meta('a'),text('a','A')]);const b=await put(root,'codex/sessions/b.jsonl',[meta('b'),text('b','B')]);const alias=join(root,'alias.jsonl');await symlink(a,alias);const ix=index(root,{directoryScanMs:60000});t.after(()=>ix.close());ix.setActiveRefs([{provider:'codex',kind:'path',value:alias}]);ix.setDetailedRefs([{provider:'codex',kind:'path',value:alias}]);await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('codex',{kind:'path',value:alias})?.id,'a');assert.equal(ix.resolveSnapshotCached('codex',{kind:'path',value:alias}),ix.resolveSnapshotCached('codex',{kind:'id',value:'a'}));await rm(alias);await symlink(b,alias);await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('codex',{kind:'path',value:alias})?.id,'b');
});
test('immutable private source snapshots preserve caller isolation and earlier revisions after another session appends',async t=>{
 const root=await home(t);const file=await put(root,'codex/sessions/r.jsonl',[meta('r'),text('body','A'.repeat(60000))]);await put(root,'codex/sessions/other.jsonl',[meta('other'),text('sibling','Sibling body')]);const ix=index(root);t.after(()=>ix.close());const refs=[{provider:'codex',kind:'id',value:'r'},{provider:'codex',kind:'id',value:'other'}];ix.setActiveRefs(refs);ix.setDetailedRefs(refs);
 await ix.refreshSnapshots();const first=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'})!,other=ix.resolveSnapshotCached('codex',{kind:'id',value:'other'})!;assert.ok(Object.isFrozen(first.messages[0]));assert.throws(()=>{first.messages[0].text='Mutated';},TypeError);
 const caller=ix.resolveCached('codex',{kind:'id',value:'other'});caller.messages[0].text='Caller mutation';assert.equal(other.messages[0].text,'Sibling body');await ix.refreshSnapshots();assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'r'}),first);
 await appendFile(file,line(text('later','New reply')));await ix.refreshSnapshots();const second=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'})!;assert.deepEqual(first.messages.map((m:any)=>m.id),['body']);assert.deepEqual(second.messages.map((m:any)=>m.id),['body','later']);assert.equal(first.messages[0]!.text,'A'.repeat(60000));assert.equal(ix.resolveSnapshotCached('codex',{kind:'id',value:'other'}),other);assert.equal(other.messages[0].text,'Sibling body');
});
test('Codex token records use explicit turn context and never reuse a completed turn identity for an unidentified new turn',async t=>{
 const root=await home(t);const count=(n:number)=>({type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:n,output_tokens:n}}}});await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'turn_context',payload:{turn_id:'t1'}},{type:'event_msg',timestamp:'2026-10-06T10:00:00Z',payload:{type:'task_started',turn_id:'t1'}},count(1),{type:'event_msg',timestamp:'2026-10-06T10:00:01Z',payload:{type:'task_complete',turn_id:'t1'}},{type:'event_msg',timestamp:'2026-10-06T10:00:02Z',payload:{type:'task_started'}},count(2)]);const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const usage=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'}).usage.filter((u:any)=>u.kind==='cumulative');assert.equal(usage[0].turnId,'t1');assert.equal(usage[1].turnId,undefined);
});
test('current Codex explicit thread goal events preserve owner, source, seconds timestamps and lifecycle status without requiring tool mirrors',async t=>{
 const root=await home(t);const goal={threadId:'r',objective:'Ship sanitized parser',status:'active',tokensUsed:12,timeUsedSeconds:3,createdAt:1791280800,updatedAt:1791280801};const event=(value:any,threadId='r')=>({type:'event_msg',payload:{type:'thread_goal_updated',threadId,goal:value}});await put(root,'codex/sessions/r.jsonl',[meta('r'),text('initial','Initial task','user'),event(goal),event({...goal,status:'budgetLimited',updatedAt:1791280802}),event({...goal,objective:'Wrong owner',threadId:'other'},'other'),event({...goal,objective:'Wrong inner owner',threadId:'other'}),event({...goal,status:'futureStatus'})]);const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const s=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'});assert.equal(s.goals.length,1);assert.equal(s.goals[0].objective,'Ship sanitized parser');assert.equal(s.goals[0].status,'budget_limited');assert.equal(s.goals[0].timestamp,1791280802000);assert.ok(s.goals[0].source?.includes('r.jsonl#'));assert.equal(s.initialRequest?.text,'Initial task');assert.ok(s.diagnostics.some((d:string)=>d.includes('goal')));
});
test('current Codex inter-agent items keep only wholly plaintext communication and never expose mixed encrypted or hidden content',async t=>{
 const root=await home(t);const item=(id:string,content:any[])=>({type:'response_item',payload:{type:'agent_message',id,author:'worker-a',recipient:'worker-b',content,internal_chat_message_metadata_passthrough:{turn_id:'t',create_time:1791280800}}});const plain=item('plain',[{type:'input_text',text:'Visible agent note\u001b]52;c;secret\u0007'}]);await put(root,'codex/sessions/r.jsonl',[meta('r'),plain,plain,item('encrypted',[{type:'input_text',text:'Envelope prefix not complete body'},{type:'encrypted_content',encrypted_content:'HIDDEN_ENCRYPTED_PAYLOAD'}]),item('unsupported',[{type:'reasoning_text',text:'HIDDEN_REASONING'}]),{type:'response_item',payload:{type:'reasoning',content:[{type:'input_text',text:'HIDDEN_CHAIN'}]}}]);const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const s=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'});const message=s.messages.find((m:any)=>m.id==='plain');assert.equal(message?.kind,'inter-agent');assert.equal(message?.text,'Visible agent note');assert.equal(message?.author,'worker-a');assert.equal(message?.recipient,'worker-b');assert.equal(message?.complete,true);assert.equal(s.messages.filter((m:any)=>m.id==='plain').length,1);const encrypted=s.messages.find((m:any)=>m.id==='encrypted');assert.equal(encrypted?.kind,'inter-agent');assert.equal(encrypted?.complete,false);assert.ok(encrypted?.text.includes('unavailable'));assert.ok(!JSON.stringify(s).includes('HIDDEN_'));assert.ok(!JSON.stringify(s).includes('Envelope prefix'));assert.equal(s.initialRequest,undefined);assert.equal(s.goals.length,0);
});
test('current Codex token records retain explicit cumulative turn counters inside one thread observation and reject foreign owners',async t=>{
 const root=await home(t);const counters=(input:number,output:number)=>({input_tokens:input,output_tokens:output,cached_input_tokens:10,cache_write_input_tokens:5,reasoning_output_tokens:2,total_tokens:input+output});const record=(response:string,turn:string,thread:string='r')=>({type:'token_usage_record',payload:{thread_id:thread,turn_id:turn,session_id:'root-accounting',root_turn_id:'root-turn',response_id:response,usage:counters(20,2),turn_token_usage:counters(40,4),thread_token_usage:counters(100,10)}});await put(root,'codex/sessions/r.jsonl',[meta('r'),record('resp','turn-1'),record('resp','turn-1'),record('foreign','turn-1','other'),{type:'token_usage_record',payload:{thread_id:'r',response_id:'unknown-turn',turn_token_usage:counters(500,50),thread_token_usage:counters(120,12)}}]);const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const s=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'});assert.equal(s.usage.length,2);const usage=s.usage.find((u:any)=>u.id==='response:resp');assert.equal(usage.kind,'cumulative');assert.equal(usage.input,100);assert.equal(usage.output,10);assert.equal(usage.turnId,'turn-1');assert.deepEqual(usage.turnCounters,{input:40,output:4,cacheRead:10,cacheWrite:5,reasoning:2,total:44,cacheSemantics:'subset'});assert.equal(s.usage.find((u:any)=>u.id==='response:unknown-turn').turnCounters,undefined);assert.ok(s.diagnostics.some((d:string)=>d.includes('thread')));const {reduceUsage}=await import('../src/metrics/usage-reducer.ts');assert.equal(reduceUsage(s.usage).input,120);
});

test('Codex exact thread snapshots supersede interleaved legacy totals without false counter resets',async t=>{
 const root=await home(t);const legacy=(input:number,last:number)=>({type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:input,output_tokens:input/10,total_tokens:input*1.1},last_token_usage:{input_tokens:last,output_tokens:2,total_tokens:last+2},model_context_window:1000}}});
 const explicit=(input:number)=>({type:'token_usage_record',payload:{thread_id:'r',turn_id:'t',response_id:String(input),thread_token_usage:{input_tokens:input,output_tokens:input/10,total_tokens:input*1.1},turn_token_usage:{input_tokens:20,output_tokens:2,total_tokens:22}}});
 await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'turn_context',payload:{model:'m',turn_id:'t'}},legacy(80,10),explicit(100),legacy(90,20),explicit(120),legacy(100,30)]);
 const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const s=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'});const {reduceUsage}=await import('../src/metrics/usage-reducer.ts');const result=reduceUsage(s.usage);
 assert.equal(result.input,120);assert.equal(result.output,12);assert.equal(result.epochs,1);assert.equal(result.turnUsage?.input,20);assert.equal(result.contextUsed,32);assert.equal(result.contextLimit,1000);assert.equal(s.usage.filter((u:any)=>u.id.startsWith('count:')).length,0);
});
test('Codex foreign or empty exact-thread snapshots do not suppress usable legacy usage',async t=>{
 const root=await home(t);await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:100,output_tokens:10,total_tokens:110},last_token_usage:{total_tokens:20},model_context_window:1000}}},{type:'token_usage_record',payload:{thread_id:'foreign',response_id:'foreign',thread_token_usage:{input_tokens:500}}},{type:'token_usage_record',payload:{thread_id:'r',response_id:'empty',thread_token_usage:{}}}]);
 const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const {reduceUsage}=await import('../src/metrics/usage-reducer.ts');assert.equal(reduceUsage(ix.resolveSnapshotCached('codex',{kind:'id',value:'r'}).usage).input,100);
});

test('Codex omitted context fields preserve the last known snapshot only for the same model',async t=>{
 const root=await home(t),file=await put(root,'codex/sessions/r.jsonl',[meta('r'),{type:'turn_context',payload:{model:'a'}},{type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:100,total_tokens:100},last_token_usage:{total_tokens:20},model_context_window:1000}}},{type:'token_usage_record',payload:{thread_id:'r',response_id:'a',thread_token_usage:{input_tokens:120,total_tokens:120}}},{type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:110,total_tokens:110}}}}]);
 const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const {reduceUsage}=await import('../src/metrics/usage-reducer.ts');let result=reduceUsage(ix.resolveSnapshotCached('codex',{kind:'id',value:'r'}).usage);assert.equal(result.input,120);assert.equal(result.contextUsed,20);assert.equal(result.contextLimit,1000);
 await appendFile(file,JSON.stringify({type:'turn_context',payload:{model:'b'}})+'\n'+JSON.stringify({type:'event_msg',payload:{type:'token_count',info:{total_token_usage:{input_tokens:130,total_tokens:130}}}})+'\n'+JSON.stringify({type:'token_usage_record',payload:{thread_id:'r',response_id:'b',thread_token_usage:{input_tokens:140,total_tokens:140}}})+'\n');
 await ix.refreshSnapshots();result=reduceUsage(ix.resolveSnapshotCached('codex',{kind:'id',value:'r'}).usage);assert.equal(result.contextUsed,undefined);assert.equal(result.contextLimit,undefined);
});

test('Codex exact thread precedence also excludes legacy-only mirrors from logical archive merging',async t=>{
 const root=await home(t);const legacy=(input:number,second:number)=>({type:'event_msg',timestamp:`2026-10-06T10:00:0${second}Z`,payload:{type:'token_count',info:{total_token_usage:{input_tokens:input,output_tokens:input/10,total_tokens:input*1.1}}}}),explicit=(input:number,second:number)=>({type:'token_usage_record',timestamp:`2026-10-06T10:00:0${second}Z`,payload:{thread_id:'r',response_id:String(input),thread_token_usage:{input_tokens:input,output_tokens:input/10,total_tokens:input*1.1}}});
 await put(root,'codex/sessions/current.jsonl',[meta('r'),legacy(80,0),explicit(100,1),legacy(90,2),explicit(120,3),legacy(100,4)]);await put(root,'codex/archived_sessions/mirror.jsonl',[meta('r'),legacy(80,0),legacy(90,2),legacy(100,4)]);
 const ix=index(root);t.after(()=>ix.close());await ix.refreshSnapshots();const s=ix.resolveSnapshotCached('codex',{kind:'id',value:'r'});const {reduceUsage}=await import('../src/metrics/usage-reducer.ts');const result=reduceUsage(s.usage);assert.equal(result.input,120);assert.equal(result.output,12);assert.equal(result.epochs,1);
});
