import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm, readdir, chmod } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createHash } from 'node:crypto';
// Release tools are plain ESM and have no runtime dependencies.
// @ts-ignore plain .mjs release utility
import { checkInstall, verifyHelper } from '../scripts/check-install.mjs';
// @ts-ignore plain .mjs release utility
import { stageRelease } from '../scripts/release.mjs';
async function fixture(t:any){const root=await mkdtemp(join(tmpdir(),'hat-release-'));t.after(()=>rm(root,{recursive:true,force:true}));for(const path of ['dist/entrypoints','dist/herdr','dist/config','companion/pi','scripts','docs'])await mkdir(join(root,path),{recursive:true});for(const file of ['action','inspector','detail','startup','event'])await writeFile(join(root,'dist/entrypoints',file+'.js'),'export const fixture=true;\n');await writeFile(join(root,'dist/config/index.js'),'export const ensurePrivateDir=async()=>{};');await writeFile(join(root,'dist/config/safe-file.js'),'export const atomicWrite=async()=>{};');await writeFile(join(root,'dist/herdr/protocol.json'),JSON.stringify({protocol:22,schemas:{request:{}}}));await writeFile(join(root,'companion/pi/index.js'),'export default ()=>{};\n');await writeFile(join(root,'package.json'),JSON.stringify({name:'herdr-prism',version:'0.1.0',type:'module',engines:{node:'>=22.13'},devDependencies:{compiler:'fixture'},scripts:{build:'do not run'}}));await writeFile(join(root,'herdr-plugin.toml'),'id = "iob.herdr-prism"\n');for(const file of ['LICENSE','THIRD_PARTY_NOTICES.md','README.md'])await writeFile(join(root,file),'fixture '+file+'\n');for(const file of ['install','compatibility','privacy'])await writeFile(join(root,'docs',file+'.md'),'fixture\n');await writeFile(join(root,'scripts/check-install.mjs'),await readFile(new URL('../scripts/check-install.mjs',import.meta.url)));await writeFile(join(root,'scripts/live-install.mjs'),await readFile(new URL('../scripts/live-install.mjs',import.meta.url)));return root;}
async function helper(root:string,platform:string,arch:string){const dir=join(root,'native/sampler/artifacts',platform+'-'+arch);await mkdir(dir,{recursive:true});await mkdir(join(dir,'rust-licenses/licenses'),{recursive:true});await writeFile(join(dir,'rust-licenses/COPYRIGHT-library.html'),'<html>Test-only license fixture</html>');await writeFile(join(dir,'rust-licenses/licenses/MIT.txt'),'Test-only license fixture');const filename=platform==='win32'?'hat-sampler.exe':'hat-sampler';const bytes=Buffer.alloc(256);if(platform==='darwin'){bytes.writeUInt32LE(0xfeedfacf,0);bytes.writeUInt32LE(arch==='arm64'?0x0100000c:0x01000007,4);}else{bytes.write('MZ');bytes.writeUInt32LE(128,0x3c);bytes.write('PE\0\0',128);bytes.writeUInt16LE(0x8664,132);}await writeFile(join(dir,filename),bytes);await chmod(join(dir,filename),0o755);const manifest={version:1,platform,arch,filename,sha256:createHash('sha256').update(bytes).digest('hex')};await writeFile(join(dir,'sha256.json'),JSON.stringify(manifest));return {dir,filename,manifest};}
test('installation rejects old Node, missing dist and unsupported helper targets',async t=>{const root=await fixture(t);assert.equal((await checkInstall({root,platform:'linux',arch:'x64',nodeVersion:'22.13.0'})).ok,true);assert.equal((await checkInstall({root,platform:'linux',arch:'x64',nodeVersion:'22.12.9'})).ok,false);assert.equal((await checkInstall({root,platform:'win32',arch:'arm64',nodeVersion:'24.0.0'})).ok,false);await rm(join(root,'dist/entrypoints/action.js'));const bad=await checkInstall({root,platform:'linux',arch:'x64',nodeVersion:'24.0.0'});assert.equal(bad.ok,false);assert.ok(bad.errors.some((x:string)=>x.includes('action.js')));});
test('helper integrity rejects missing checksum, modified bytes and mislabeled architecture',async t=>{const root=await fixture(t);const h=await helper(root,'darwin','arm64');await assert.rejects(verifyHelper(root,'darwin','arm64'),/missing|ENOENT/i);await mkdir(join(root,'bin'),{recursive:true});const {cp}=await import('node:fs/promises');await cp(h.dir,join(root,'bin/darwin-arm64'),{recursive:true});assert.equal((await verifyHelper(root,'darwin','arm64')).sha256,h.manifest.sha256);await writeFile(join(root,'bin/darwin-arm64',h.filename),'changed');await assert.rejects(verifyHelper(root,'darwin','arm64'),/checksum/i);await writeFile(join(root,'bin/darwin-arm64',h.filename),await readFile(join(h.dir,h.filename)));await writeFile(join(root,'bin/darwin-arm64/sha256.json'),JSON.stringify({...h.manifest,arch:'x64'}));await assert.rejects(verifyHelper(root,'darwin','arm64'),/identity|architecture/i);});
test('Linux release is complete ESM without runtime dependencies or toolchains and refuses overwrite',async t=>{const root=await fixture(t);const output=join(root,'output');await stageRelease({root,output,platforms:['linux-x64']});const packaged=JSON.parse(await readFile(join(output,'package.json'),'utf8'));assert.equal(packaged.type,'module');assert.equal(packaged.devDependencies,undefined);assert.equal(packaged.dependencies,undefined);assert.ok(!packaged.scripts?.build);assert.ok((await readFile(join(output,'dist/herdr/protocol.json'),'utf8')).includes('22'));assert.ok((await readFile(join(output,'companion/pi/index.js'),'utf8')).includes('default'));assert.equal((await checkInstall({root:output,platform:'linux',arch:'x64',nodeVersion:'24.0.0'})).ok,true);const entries=await readdir(output);assert.ok(!entries.includes('src'));assert.ok(!entries.includes('node_modules'));await assert.rejects(stageRelease({root,output,platforms:['linux-x64']}),/exists|overwrite/i);});
test('multi-platform release requires all real helper manifests and hashes every staged file',async t=>{const root=await fixture(t);const output=join(root,'multi');await helper(root,'darwin','arm64');await assert.rejects(stageRelease({root,output,platforms:['all']}),/missing|ENOENT/i);await helper(root,'darwin','x64');await helper(root,'win32','x64');await stageRelease({root,output,platforms:['all']});for(const [platform,arch]of [['darwin','arm64'],['darwin','x64'],['win32','x64']])assert.equal((await checkInstall({root:output,platform,arch,nodeVersion:'24.0.0'})).ok,true);const sums=JSON.parse(await readFile(join(output,'checksums.json'),'utf8'));assert.equal(sums.version,1);for(const [file,digest]of Object.entries(sums.files))assert.equal(createHash('sha256').update(await readFile(join(output,file))).digest('hex'),digest);await writeFile(join(output,'dist/entrypoints/action.js'),'tampered');assert.equal((await checkInstall({root:output,platform:'linux',arch:'x64',nodeVersion:'24.0.0'})).ok,false);});

test('release carries matching toolchain notices and rejects missing license artifact',async t=>{const root=await fixture(t);const h=await helper(root,'darwin','arm64');const output=join(root,'licensed');await rm(join(h.dir,'rust-licenses/COPYRIGHT-library.html'));await assert.rejects(stageRelease({root,output,platforms:['darwin-arm64']}),/Required native license notice missing/i);await writeFile(join(h.dir,'rust-licenses/COPYRIGHT-library.html'),'<html>Test-only license fixture</html>');await stageRelease({root,output,platforms:['darwin-arm64']});assert.match(await readFile(join(output,'bin/darwin-arm64/rust-licenses/COPYRIGHT-library.html'),'utf8'),/Test-only/);});
test('staged release rejects a removed integrity index and preserves existing destination data',async t=>{const root=await fixture(t);const output=join(root,'guarded');await stageRelease({root,output,platforms:['linux-x64']});await rm(join(output,'checksums.json'));const checked=await checkInstall({root:output,platform:'linux',arch:'x64',nodeVersion:'24.0.0'});assert.equal(checked.ok,false);assert.ok(checked.errors.some((x:string)=>x.includes('checksum index missing')));await writeFile(join(output,'user-data'),'keep');await assert.rejects(stageRelease({root,output,platforms:['linux-x64']}),/exists/);assert.equal(await readFile(join(output,'user-data'),'utf8'),'keep');});

test('installation checks finite startup and event hooks referenced by the manifest',async t=>{const root=await fixture(t);await rm(join(root,'dist/entrypoints/startup.js'));const result=await checkInstall({root,platform:'linux',arch:'x64',nodeVersion:'24.0.0'});assert.equal(result.ok,false);assert.ok(result.errors.some((x:string)=>x.includes('startup.js')));});
test('source design and evidence documents referenced by README survive staging when present',async t=>{const root=await fixture(t);await mkdir(join(root,'docs/design'));await writeFile(join(root,'docs/design/herdr-prism.md'),'source design');await writeFile(join(root,'docs/implementation-progress.md'),'actual evidence');const output=join(root,'documented');await stageRelease({root,output,platforms:['linux-x64']});assert.equal(await readFile(join(output,'docs/design/herdr-prism.md'),'utf8'),'source design');assert.equal(await readFile(join(output,'docs/implementation-progress.md'),'utf8'),'actual evidence');});

test('release bundles the live lifecycle wrapper alongside precompiled security helpers',async t=>{const root=await fixture(t),output=join(root,'lifecycle');await stageRelease({root,output,platforms:['linux-x64']});assert.ok((await readFile(join(output,'scripts/live-install.mjs'),'utf8')).includes('liveUninstall'));assert.ok(await readFile(join(output,'dist/config/safe-file.js'),'utf8'));});
