import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,rm,readFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
const module=await import('../src/process/sidebar-sampler.ts').catch(()=>({})) as any;
const stat=(pid:number,start='9007199254740993',cpu='9007199254740995')=>`${pid} (target (worker)) S 1 0 0 0 0 0 0 0 0 0 ${cpu} 8 999999 999999 0 0 4 0 ${start} 0 3\n`;

test('sidebar sampler reads only requested Linux stat paths, caches units/boot and preserves wide counters and identity changes',async t=>{
 assert.equal(typeof module.SidebarSampler,'function');const root=await mkdtemp(join(tmpdir(),'prism-sidebar-proc-'));t.after(()=>rm(root,{recursive:true,force:true}));await mkdir(join(root,'sys/kernel/random'),{recursive:true});await writeFile(join(root,'sys/kernel/random/boot_id'),'fixture-boot\n');await writeFile(join(root,'uptime'),'90071992547410.93 0\n');for(const pid of [42,77,999]){await mkdir(join(root,String(pid)));await writeFile(join(root,String(pid),'stat'),stat(pid));}
 const reads:string[]=[];const commands:any[]=[];const sampler=new module.SidebarSampler({platform:'linux',procRoot:root,runner:async(file:string,args:string[])=>{commands.push([file,args]);return {stdout:args[0]==='CLK_TCK'?'100\n':'4096\n'};},readFile:async(file:string,options:any)=>{reads.push(file);return readFile(file,{encoding:'utf8',signal:options.signal});}});t.after(()=>sampler.close());const first=await sampler.sample([77,42,42]);assert.deepEqual(first.processes.map((p:any)=>p.pid),[42,77]);assert.equal(first.bootId,'fixture-boot');assert.equal(first.processes[0].cpuNs,((9007199254740995n+8n)*10000000n).toString());assert.equal(first.processes[0].rssBytes,'12288');assert.equal(first.processes[0].startTime,'9007199254740993');assert.equal(first.processes[0].uptimeMs,1000);assert.ok(reads.every(p=>!p.includes('/999/')));await writeFile(join(root,'42/stat'),stat(42,'9007199254740994'));const second=await sampler.sample([42]);assert.equal(second.processes[0].startTime,'9007199254740994');assert.equal(reads.filter(p=>p.endsWith('boot_id')).length,1);assert.deepEqual(commands.map(c=>c[1]),[['CLK_TCK'],['PAGESIZE']]);
});
test('denied, exited and mismatched Linux targets produce errors rather than measured zero or foreign rows',async()=>{
 assert.equal(typeof module.SidebarSampler,'function');const sampler=new module.SidebarSampler({platform:'linux',clockTicks:100,pageSize:4096,readFile:async(file:string)=>{if(file.endsWith('boot_id'))return 'boot';if(file.endsWith('uptime'))return '100 0';if(file.endsWith('/42/stat'))throw Object.assign(new Error('denied'),{code:'EACCES'});if(file.endsWith('/77/stat'))throw Object.assign(new Error('gone'),{code:'ENOENT'});return stat(999);}});const batch=await sampler.sample([42,77,88]);assert.deepEqual(batch.processes,[]);assert.ok(batch.errors.some((e:string)=>/pid 42.*EACCES/.test(e)));assert.ok(batch.errors.some((e:string)=>/pid 77.*exited/.test(e)));assert.ok(batch.errors.some((e:string)=>/pid 88.*identity/.test(e)));await sampler.close();
});
test('macOS targeted parser handles cumulative TIME days/hours and wide RSS, keeps stable birth and rejects unrequested/malformed rows',()=>{
 assert.equal(typeof module.parseSidebarPs,'function');const parsed=module.parseSidebarPs('42 1 123456-12:34:56.78 9007199254740993 Mon Jan  2 03:04:05 2023 /tmp/worker with spaces\n77 1 01:02.03 12 Mon Jan  2 03:04:05 2023 node\n999 1 0:00.00 1 Mon Jan  2 03:04:05 2023 other\n',[42,77],Date.UTC(2023,0,2,3,4,6));assert.deepEqual(parsed.processes.map((p:any)=>p.pid),[42,77]);assert.equal(parsed.processes[0].cpuNs,((123456n*86400n+12n*3600n+34n*60n+56n)*1000000000n+780000000n).toString());assert.equal(parsed.processes[0].rssBytes,(9007199254740993n*1024n).toString());assert.equal(parsed.processes[0].startTime,String(Date.UTC(2023,0,2,3,4,5)/1000));assert.equal(parsed.processes[0].uptimeMs,1000);assert.ok(parsed.errors.some((e:string)=>/unrequested.*999/.test(e)));const bad=module.parseSidebarPs('42 1 0:99.00 1 Mon Jan  2 03:04:05 2023 bad\n',[42]);assert.deepEqual(bad.processes,[]);assert.ok(bad.errors.some((e:string)=>/pid 42/.test(e)));
});
test('macOS runner uses only a sorted numeric PID selector, UTC/C locale, bounded argv and caches boot UUID',async()=>{
 assert.equal(typeof module.SidebarSampler,'function');const calls:any[]=[];const sampler=new module.SidebarSampler({platform:'darwin',runner:async(file:string,args:string[],options:any)=>{calls.push({file,args,options});return{stdout:file.endsWith('sysctl')?'boot-uuid\n':'42 1 0:00.01 3 Mon Jan  2 03:04:05 2023 node\n'};}});await sampler.sample([42]);await sampler.sample([42]);const ps=calls.filter(c=>c.file.endsWith('/ps'));assert.equal(ps.length,2);assert.deepEqual(ps[0].args,['-p','42','-o','pid=,ppid=,time=,rss=,lstart=,comm=']);assert.equal(ps[0].options.env.LC_ALL,'C');assert.equal(ps[0].options.env.TZ,'UTC');assert.ok(ps[0].options.signal instanceof AbortSignal);assert.ok(ps[0].options.timeout>0&&ps[0].options.maxBuffer<=512*1024);assert.equal(calls.filter(c=>c.file.endsWith('sysctl')).length,1);await sampler.close();
});
test('PID cap, invalid numeric IDs and empty requests do not start I/O',async()=>{
 assert.equal(typeof module.SidebarSampler,'function');let calls=0;const sampler=new module.SidebarSampler({platform:'darwin',runner:async()=>{calls++;return{stdout:''};}});for(const pids of [[0],[-1],[1.5],[NaN],[2147483648],Array.from({length:129},(_,i)=>i+1)])await assert.rejects(sampler.sample(pids),/PID|128/);assert.deepEqual((await sampler.sample([])).processes,[]);assert.equal(calls,0);await sampler.close();await assert.rejects(sampler.sample([42]),/closed/);
});
test('close aborts a pending targeted query promptly even when the injected runner ignores cancellation',async()=>{
 assert.equal(typeof module.SidebarSampler,'function');let entered!:()=>void;const called=new Promise<void>(resolve=>entered=resolve);let signal:AbortSignal|undefined;const sampler=new module.SidebarSampler({platform:'darwin',runner:async(file:string,_args:string[],options:any)=>{if(file.endsWith('sysctl'))return{stdout:'boot'};signal=options.signal;entered();return new Promise(()=>{});}});const pending=sampler.sample([42]);const rejected=assert.rejects(pending,/closed|abort/i);await called;await sampler.close();await rejected;assert.equal(signal!.aborted,true);await assert.rejects(sampler.sample([42]),/closed/);
});
test('query timeout and excessive output become unavailable errors, without rows or zero counters',async()=>{
 assert.equal(typeof module.SidebarSampler,'function');const slow=new module.SidebarSampler({platform:'darwin',timeoutMs:30,runner:async(file:string)=>file.endsWith('sysctl')?{stdout:'boot'}:new Promise(()=>{})});const batch=await slow.sample([42]);assert.deepEqual(batch.processes,[]);assert.ok(batch.errors.some((e:string)=>/timeout|timed out/i.test(e)));await slow.close();const large=new module.SidebarSampler({platform:'darwin',runner:async(file:string)=>({stdout:file.endsWith('sysctl')?'boot':'x'.repeat(512*1024+1)})});const oversize=await large.sample([42]);assert.deepEqual(oversize.processes,[]);assert.ok(oversize.errors.some((e:string)=>/output|limit/i.test(e)));await large.close();
});
test('actual macOS sidebar query samples only this test process and is read-only',{skip:process.platform!=='darwin'},async()=>{
 assert.equal(typeof module.SidebarSampler,'function');const sampler=new module.SidebarSampler();try{const batch=await sampler.sample([process.pid]);assert.deepEqual(batch.processes.map((p:any)=>p.pid),[process.pid]);assert.match(batch.bootId,/^sidebar-darwin:/);assert.match(batch.processes[0].cpuNs,/^\d+$/);assert.ok(BigInt(batch.processes[0].rssBytes)>0n);assert.ok(batch.processes[0].uptimeMs>=0);}finally{await sampler.close();}
});

test('Windows sidebar is explicitly unavailable without invoking the host-enumerating .NET fallback',async()=>{
 let calls=0;const sampler=new module.SidebarSampler({platform:'win32',runner:async()=>{calls++;throw Error('Must not run');}});const batch=await sampler.sample([42]);assert.deepEqual(batch.processes,[]);assert.ok(batch.errors.some((e:string)=>/Windows.*unavailable.*target-only.*enumerate/.test(e)));assert.equal(calls,0);await sampler.close();
});
test('macOS duplicate target rows never combine identities or publish a counter',()=>{
 const result=module.parseSidebarPs('42 1 0:00.00 1 Mon Jan  2 03:04:05 2023 node\n42 1 0:00.01 3 Tue Jan  3 03:04:05 2023 replacement\n',[42]);assert.deepEqual(result.processes,[]);assert.ok(result.errors.some((e:string)=>/duplicate identity/.test(e)));
});
test('actual Linux targeted sampler reads this test PID without host enumeration',{skip:process.platform!=='linux'},async()=>{
 const sampler=new module.SidebarSampler();try{const batch=await sampler.sample([process.pid]);assert.deepEqual(batch.processes.map((p:any)=>p.pid),[process.pid]);assert.ok(BigInt(batch.processes[0].rssBytes)>0n);assert.match(batch.processes[0].startTime,/^\d+$/);}finally{await sampler.close();}
});
