import {test} from 'node:test';
import assert from 'node:assert/strict';
const screen=await import('../src/tui/screen.ts').catch(()=>({})) as any;
const text=await import('../src/tui/text.ts').catch(()=>({})) as any;
const data={sessions:[{key:'codex:a',depth:0,children:['codex:b'],evidence:{id:'a',provider:'codex',title:'日本語 agent',state:'working',messages:[{id:'m1',role:'assistant',text:'Review src/auth.ts\nACTION: Review plan',timestamp:1}],tools:[],usage:[],goals:[],availability:'known'},resource:{processes:[],availability:'unavailable',memoryLabel:'RSS sum',coverage:{readable:0,total:0}},usage:{input:123,output:45,availability:'known'},todos:[{id:'t1',text:'Review plan',messageId:'m1',checked:false}],refs:[{id:'r1',target:'/repo/auth.ts',messageId:'m1',edited:true}]},{key:'codex:b',depth:1,parentKey:'codex:a',children:[],evidence:{id:'b',provider:'codex',title:'child',messages:[],tools:[],usage:[],goals:[],availability:'known'}}],updatedAt:100,stale:false,diagnostics:[]};
test('Refs labels historical coverage and its evidence age instead of presenting a limited list as lifetime complete',()=>{
 const state=screen.createUiState();state.tab='Refs';state.selectedKey='codex:a';
 for(const [coverage,label]of [['session','Session reference history'],['partial','Partial reference history'],['retained','Retained message references'],['unavailable','Reference source unavailable']]){
  const input={...data,sessions:[{...data.sessions[0],refCoverage:coverage,refUpdatedAt:1000}]};const rendered=screen.renderScreen(input,state,80,24,4000);
  assert.match(rendered.rows[0].text,new RegExp(label));assert.match(rendered.rows[0].text,/3s ago/);
 }
});
test('reference pages and nested source readers preserve anchors and route exact source cursors',()=>{
 const cursor={provider:'codex',sessionId:'a',path:'/fixture/r.jsonl',fileId:'f',offset:1,hash:'a'.repeat(64),file:0,timestamp:1};const ref={...data.sessions[0].refs![0]!,cursor,sources:[{messageId:'m1',cursor}]};const input={...data,sessions:[{...data.sessions[0],refs:[ref],evidence:{...data.sessions[0].evidence,contentRevision:'v1'}}]};const state=screen.createUiState();state.tab='Refs';state.selectedKey='codex:a';let rendered=screen.renderScreen(input,state,42,12);state.cursor=rendered.rows.findIndex((r:any)=>r.id===ref.id);state.cursorId=ref.id;rendered=screen.renderScreen(input,state,42,12);assert.deepEqual(screen.handleKey(state,'s',input,rendered).referenceCursor,cursor);assert.equal(screen.handleKey(state,'space',input,rendered).type,'ref-sources');
 assert.equal(typeof screen.showReferenceSources,'function');const original={cursor:state.cursor,cursorId:state.cursorId,scroll:state.scroll};const pageCursor={version:'v',before:cursor,key:'m1'};screen.showReferenceSources(state,'codex:a',ref,{sources:[{messageId:'m1',cursor}],cursor:pageCursor,hasMore:true,partial:false,observedAt:1},'v1');rendered=screen.renderScreen(input,state,42,12);state.cursor=rendered.rows.findIndex((r:any)=>r.action?.type==='source');state.cursorId=rendered.rows[state.cursor].id;rendered=screen.renderScreen(input,state,42,12);const sourcePosition={cursor:state.cursor,cursorId:state.cursorId,scroll:state.scroll};assert.deepEqual(screen.handleKey(state,'enter',input,rendered).referenceCursor,cursor);assert.equal(screen.handleKey(state,'b',input,rendered).type,'ref-sources');
 screen.showDetail(state,'Exact historical source\n'.repeat(40));screen.renderScreen(input,state,42,12);screen.handleKey(state,'escape',input,rendered);assert.ok(state.refSources);assert.deepEqual({cursor:state.cursor,cursorId:state.cursorId,scroll:state.scroll},sourcePosition);screen.handleKey(state,'escape',input,screen.renderScreen(input,state,42,12));assert.equal(state.refSources,undefined);assert.deepEqual({cursor:state.cursor,cursorId:state.cursorId,scroll:state.scroll},original);
 assert.equal(typeof screen.addReferencePage,'function');screen.addReferencePage(state,'codex:a',{refs:[{...ref,id:'older',messageId:'older',target:'/older.ts',cursor:{...cursor,offset:0}}],cursor:pageCursor,hasMore:true,partial:false,observedAt:1},'v1');rendered=screen.renderScreen(input,state,42,12);assert.ok(rendered.rows.some((r:any)=>r.id==='older'));assert.equal(state.cursorId,ref.id);const changed={...input,sessions:[{...input.sessions[0],evidence:{...input.sessions[0].evidence,contentRevision:'v2'}}]};rendered=screen.renderScreen(changed,state,42,12);assert.ok(rendered.rows.some((r:any)=>/snapshot.*stale/i.test(r.text)));assert.equal(screen.handleKey(state,'b',changed,rendered).restart,true);
 for(let i=0;i<15;i++)screen.addReferencePage(state,'codex:a',{refs:Array.from({length:50},(_,n)=>({...ref,id:'bounded-'+i+'-'+n})),hasMore:true,partial:false,observedAt:1},'v2');assert.ok(state.pagedRefs.get('codex:a').refs.length<=500);
});
test('bounded previews stop at requested lines while preserving graphemes, tabs and explicit full wrapping',()=>{
 assert.deepEqual(text.wrap('日本語👩‍💻e\u0301TAIL',4,2),['日本','語👩‍💻']);assert.deepEqual(text.wrap('ab\tc\nxy',4,2),['ab  ','  c']);assert.deepEqual(text.wrap('ab\tc\nxy',4),['ab  ','  c','xy']);assert.equal(text.wrap('x'.repeat(100000),8,3).length,3);assert.equal(text.wrap('text',8,0).length,0);
});
test('inter-agent rows identify author and recipient while overview separates their counts',()=>{
 const input:any=structuredClone(data);input.sessions[0]!.evidence.messages.push({id:'between',role:'assistant',text:'delegation',kind:'inter-agent',author:'parent',recipient:'child'});const state=screen.createUiState();state.selectedKey='codex:a';let result=screen.renderScreen(input,state,100,40);assert.match(result.rows.find((r:any)=>r.id==='messages').text,/U0 A1/);assert.match(result.rows.find((r:any)=>r.id==='inter-agent-messages').text,/1/);state.tab='Messages';result=screen.renderScreen(input,state,100,40);assert.match(result.rows.find((r:any)=>r.id==='between').text,/Agent parent.*child/);
});
test('six views stay readable at narrow widths and strip terminal-control data',()=>{
  assert.equal(typeof screen.renderScreen,'function','dashboard renderer missing');
  assert.equal(typeof screen.createUiState,'function','dashboard state missing');
  for(const columns of [26,42,80])for(const tab of ['Overview','Agents','Processes','Messages','Refs','To-do']){
    const state=screen.createUiState();state.tab=tab;state.selectedKey='codex:a';const result=screen.renderScreen(data,state,columns,24);
    assert.ok(result.lines.some((line:string)=>line.includes('Codex')||line.includes('codex')));
    assert.ok(result.lines.length<=24);
    for(const line of result.lines)assert.ok(text.cellWidth(line)<=columns,`${columns}: ${line}`);
  }
  assert.equal(text.sanitize('safe\x1b]52;c;secret\x07\x1b[31m\x00end'),'safeend');
  assert.equal(text.cellWidth('日本語'),6);assert.equal(text.cellWidth('👩‍💻'),2);
});
test('agent folding and numeric selection retain the target the user saw',()=>{
  assert.equal(typeof screen.handleKey,'function','keyboard controller missing');
  const state=screen.createUiState();state.tab='Agents';state.selectedKey='codex:a';
  let result=screen.renderScreen(data,state,42,24);assert.ok(result.lines.some((l:string)=>l.includes('child')));
  screen.handleKey(state,'space',data,result);result=screen.renderScreen(data,state,42,24);assert.ok(!result.lines.some((l:string)=>l.includes('child')));
  screen.handleKey(state,'space',data,result);result=screen.renderScreen(data,state,42,24);
  screen.handleKey(state,'2',data,result);
  const reordered={...data,sessions:[data.sessions[1],data.sessions[0]]};
  const action=screen.handleKey(state,'enter',reordered,screen.renderScreen(reordered,state,42,24));
  assert.equal(action?.sessionKey,'codex:b');
});
test('denied process placeholders remain unavailable and a deep PPID tree folds descendants',()=>{
 const processes=[{key:'p1',pid:1,ppid:0,name:'root',startTime:'1',cpuNs:'0',rssBytes:'1024',cpuPercent:2,owner:'codex:a',availability:'known'},{key:'p2',pid:2,ppid:1,name:'child',startTime:'2',cpuNs:'0',rssBytes:'2048',cpuPercent:1,owner:'codex:a',availability:'known'},{key:'p3',pid:3,ppid:2,name:'grandchild',startTime:'3',cpuNs:'0',rssBytes:'4096',owner:'codex:a',availability:'known'},{key:'p4',pid:4,ppid:3,name:'denied',startTime:'4',cpuNs:'0',rssBytes:'0',owner:'codex:a',availability:'unavailable'}];const input={...data,sessions:[{...data.sessions[0],resource:{processes,availability:'partial',memoryLabel:'RSS sum',coverage:{readable:3,total:4}}}]};const state=screen.createUiState();state.tab='Processes';state.selectedKey='codex:a';let result=screen.renderScreen(input,state,80,24);const denied=result.rows.find((r:any)=>r.id==='p4');assert.ok(denied.text.includes('—'));assert.ok(!denied.text.includes('0MiB'));assert.ok(result.rows.find((r:any)=>r.id==='p3').text.startsWith('    '));state.cursor=result.rows.findIndex((r:any)=>r.id==='p1');state.cursorId='p1';screen.handleKey(state,'space',input,result);result=screen.renderScreen(input,state,80,24);assert.ok(!result.rows.some((r:any)=>r.id==='p4'));screen.handleKey(state,'space',input,result);result=screen.renderScreen(input,state,80,24);assert.ok(result.rows.some((r:any)=>r.id==='p4'));
});
test('closing full message detail restores the saved reader position',()=>{
 const state=screen.createUiState();state.tab='Messages';state.selectedKey='codex:a';state.cursor=1;state.scroll=1;state.cursorId='m1:line:0';assert.equal(typeof screen.showDetail,'function');screen.showDetail(state,'Detail\n'.repeat(100));screen.renderScreen(data,state,26,12);screen.handleKey(state,'escape',data,screen.renderScreen(data,state,26,12));assert.equal(state.detail,undefined);assert.equal(state.cursor,1);assert.equal(state.scroll,1);assert.equal(state.cursorId,'m1:line:0');
});
test('message history paging merges chronologically, bounds retained pages, and scrollback tracks new items without jumping',()=>{
 const input={...data,sessions:[{...data.sessions[0],evidence:{...data.sessions[0].evidence,messages:[{id:'m2',role:'assistant',text:'second',timestamp:2},{id:'m3',role:'assistant',text:'third',timestamp:3}]}}]};const state=screen.createUiState();state.tab='Messages';state.selectedKey='codex:a';let result=screen.renderScreen(input,state,80,10);screen.handleKey(state,'home',input,result);result=screen.renderScreen(input,state,80,10);const action=screen.handleKey(state,'b',input,result);assert.equal(action?.type,'page-messages');assert.equal(action?.beforeId,'m2');assert.equal(typeof screen.addMessagePage,'function');screen.addMessagePage(state,'codex:a',[{id:'m1',role:'assistant',text:'old',timestamp:1},{id:'m2',role:'assistant',text:'second',timestamp:2}]);result=screen.renderScreen(input,state,80,10);assert.deepEqual(result.rows.filter((r:any)=>r.action?.id&&r.id===r.action.id).map((r:any)=>r.id),['m1','m2','m3']);const cursorId=state.cursorId;
 const updated={...input,sessions:[{...input.sessions[0],evidence:{...input.sessions[0].evidence,messages:[...input.sessions[0].evidence.messages,{id:'m4',role:'assistant',text:'new',timestamp:4}]}}]};result=screen.renderScreen(updated,state,80,10);assert.equal(state.cursorId,cursorId);assert.ok(result.lines.some((l:string)=>/1 new/.test(l)));screen.handleKey(state,'end',updated,result);result=screen.renderScreen(updated,state,80,10);assert.ok(!result.lines.some((l:string)=>/1 new/.test(l)));assert.equal(state.cursor,result.sectionRegions.find((r:any)=>r.id==='Retained messages').indices.at(-1));
 screen.addMessagePage(state,'codex:a',Array.from({length:1500},(_,i)=>({id:'old'+i,role:'user',text:'body',timestamp:-i})));assert.ok(state.pagedMessages.get('codex:a').length<=1000);
});
test('Overview reports full descendant statuses and explicit durations, and To-do copy prefers one inline command',()=>{
 const nested={...data,sessions:[{...data.sessions[0],usage:{...data.sessions[0].usage,turnMs:3000,generationMs:1000},todos:[{id:'checked',text:'Already done',messageId:'m1',checked:true},{id:'pending',text:'Run `npm test` now',messageId:'m1',checked:false}]},{...data.sessions[1],children:['codex:c'],evidence:{...data.sessions[1].evidence,state:'running'}},{key:'codex:c',depth:2,parentKey:'codex:b',children:[],evidence:{...data.sessions[1].evidence,id:'c',state:'waiting'}}]};const state=screen.createUiState();state.selectedKey='codex:a';let result=screen.renderScreen(nested,state,80,50);assert.ok(result.rows.some((r:any)=>r.id==='children'&&r.text.includes('2')));assert.ok(result.rows.some((r:any)=>r.id==='children'&&r.text.includes('waiting 1')));assert.ok(result.rows.find((r:any)=>r.id==='process-uptime').action.text.includes('Reported turn: 3s'));assert.ok(result.lines[0].includes('日本語 agent'));state.tab='To-do';result=screen.renderScreen(nested,state,80,24);assert.equal(result.rows[1].id,'pending');screen.handleKey(state,'down',nested,result);result=screen.renderScreen(nested,state,80,24);assert.equal(screen.handleKey(state,'y',nested,result)?.text,'npm test');
});
test('default diagnostic export omits all session content, paths, goals and raw identities',async()=>{
 const api=await import('../src/tui/export.ts').catch(()=>({})) as any;assert.equal(typeof api.diagnosticExport,'function');const secret={...data,sessions:[{...data.sessions[0],evidence:{...data.sessions[0].evidence,id:'private-id',title:'private-title',cwd:'/private/repo',task:'private-task',messages:[{id:'private-message',role:'user',text:'private-body'}],goals:[{id:'goal',objective:'private-goal'}]},resource:{...data.sessions[0].resource,processes:[{pid:123,ppid:122,name:'private-argv',key:'private-pid',startTime:'private-start',rssBytes:'123',cpuNs:'456',owner:'private-owner'}]},refs:[{id:'ref',target:'/private/ref',messageId:'private-message',edited:true}],todos:[{id:'todo',text:'private-action',messageId:'private-message',checked:false}]}],diagnostics:['private-diagnostic /secret']};const serialized=api.diagnosticExport(secret);assert.ok(!serialized.includes('private'));assert.ok(!serialized.includes('/secret'));assert.ok(serialized.includes('session-1'));assert.ok(serialized.includes('codex'));assert.ok(serialized.includes('unavailable'));
});
test('paged older messages survive a full retained window and details restore a real scrolled reader',()=>{
 const hot=Array.from({length:200},(_,i)=>({id:'m'+(1000+i),role:'assistant',text:'Body '+i,timestamp:1000+i}));const input={...data,sessions:[{...data.sessions[0],evidence:{...data.sessions[0].evidence,messages:hot}}]};const state=screen.createUiState();state.tab='Messages';state.selectedKey='codex:a';screen.addMessagePage(state,'codex:a',Array.from({length:1000},(_,i)=>({id:'m'+i,role:'assistant',text:'Prior '+i,timestamp:i})));let result=screen.renderScreen(input,state,80,10);screen.handleKey(state,'home',input,result);result=screen.renderScreen(input,state,80,10);screen.addMessagePage(state,'codex:a',[{id:'older',role:'assistant',text:'Older body',timestamp:-1}]);result=screen.renderScreen(input,state,80,10);assert.ok(result.rows.some((r:any)=>r.id==='older'));
 for(let i=0;i<12;i++){screen.handleKey(state,'down',input,result);result=screen.renderScreen(input,state,80,10);}const saved={cursor:state.cursor,cursorId:state.cursorId,scroll:state.scroll};screen.showDetail(state,'Long detail\n'.repeat(100));result=screen.renderScreen(input,state,80,10);screen.handleKey(state,'escape',input,result);screen.renderScreen(input,state,80,10);assert.deepEqual({cursor:state.cursor,cursorId:state.cursorId,scroll:state.scroll},saved);
});
test('tab reader positions persist and process cycles render once without recursion',()=>{
 const input={...data,sessions:[{...data.sessions[0],resource:{...data.sessions[0].resource,processes:[{key:'p1',pid:1,ppid:2,startTime:'1',name:'cycle one',rssBytes:'0',cpuNs:'0',owner:'codex:a'},{key:'p2',pid:2,ppid:1,startTime:'1',name:'cycle two',rssBytes:'0',cpuNs:'0',owner:'codex:a'}]}}]};const state=screen.createUiState();state.selectedKey='codex:a';let result=screen.renderScreen(input,state,80,10);screen.handleKey(state,'down',input,result);result=screen.renderScreen(input,state,80,10);const selected=state.cursorId;screen.handleKey(state,'tab',input,result);result=screen.renderScreen(input,state,80,10);screen.handleKey(state,'shift+tab',input,result);screen.renderScreen(input,state,80,10);assert.equal(state.cursorId,selected);state.tab='Processes';result=screen.renderScreen(input,state,80,10);assert.equal(result.rows.filter((r:any)=>['p1','p2'].includes(r.id)).length,2);
});
test('deep agent rows retain depth and full breadcrumb details while activity counts state retained coverage',()=>{
 const sessions=Array.from({length:8},(_,i)=>({key:'codex:'+i,depth:i,parentKey:i?'codex:'+(i-1):undefined,children:i<7?['codex:'+(i+1)]:[],evidence:{...data.sessions[0].evidence,id:String(i),title:'Level '+i}}));const input={...data,sessions};const state=screen.createUiState();state.selectedKey='codex:0';state.tab='Agents';let result=screen.renderScreen(input,state,80,40);assert.ok(result.rows.find((r:any)=>r.id==='codex:7').text.includes('d7'));state.cursor=result.rows.findIndex((r:any)=>r.id==='codex:7');state.cursorId='codex:7';const action=screen.handleKey(state,'d',input,result);assert.equal(action?.type,'message');assert.ok(action.text.includes('Level 0'));assert.ok(action.text.includes('Level 7'));state.tab='Overview';result=screen.renderScreen(input,state,80,40);assert.ok(result.rows.find((r:any)=>r.id==='messages').text.includes('retained'));assert.ok(result.rows.find((r:any)=>r.id==='messages').text.includes('tools'));
});
test('mouse disclosure follows the drawn agent glyph and adjacent row clicks inspect without native focus',()=>{
 const sessions=Array.from({length:9},(_,i)=>({key:'codex:'+i,depth:i,parentKey:i?'codex:'+(i-1):undefined,children:i<8?['codex:'+(i+1)]:[],evidence:{...data.sessions[0].evidence,id:String(i),title:'Level '+i}}));const input={...data,sessions};
 for(const ascii of [false,true])for(const depth of [0,1,2,5,7]){
  const state=screen.createUiState();state.tab='Agents';state.ascii=ascii;state.selectedKey='codex:0';state.cursor=depth;state.cursorId='codex:'+depth;
  let result=screen.renderScreen(input,state,36,12);let region=result.rowRegions.find((r:any)=>r.index===depth);assert.ok(region);
  assert.equal(result.lines[region.y-1][region.disclosureX-1],ascii?'-':'▾');
  assert.equal(screen.handleRowClick(state,region.disclosureX,region.y,input,result),undefined);assert.ok(state.collapsed.has('codex:'+depth));assert.equal(state.selectedKey,'codex:0');
  result=screen.renderScreen(input,state,36,12);assert.equal(result.rows.length,depth+1);region=result.rowRegions.find((r:any)=>r.index===depth);
  screen.handleRowClick(state,region.disclosureX,region.y,input,result);result=screen.renderScreen(input,state,36,12);assert.equal(result.rows.length,9);region=result.rowRegions.find((r:any)=>r.index===depth);
  const action=screen.handleRowClick(state,region.actionX,region.y,input,result);assert.equal(action?.type,'select');assert.equal(action.sessionKey,'codex:'+depth);assert.equal(state.collapsed.has('codex:'+depth),false);
 }
});
test('process disclosure folds the drawn subtree while footer clicks cannot activate hidden rows',()=>{
 const processes=Array.from({length:12},(_,i)=>({key:'p'+i,pid:100+i,ppid:99+i,startTime:String(i+1),cpuNs:'0',rssBytes:'1024',name:'process '+i,owner:'codex:a',availability:'known'}));const input={...data,sessions:[{...data.sessions[0],resource:{...data.sessions[0].resource,processes}}]};
 for(const depth of [0,1,2,7]){
  const state=screen.createUiState();state.tab='Processes';state.selectedKey='codex:a';state.cursorId='p'+depth;
  let result=screen.renderScreen(input,state,36,12);let region=result.rowRegions.find((r:any)=>result.rows[r.index]?.id==='p'+depth);assert.ok(region);assert.equal(result.lines[region.y-1][region.disclosureX-1],'▾');
  assert.equal(screen.handleRowClick(state,region.disclosureX,region.y,input,result),undefined);assert.ok(state.collapsed.has('process:codex:a:p'+depth));
  result=screen.renderScreen(input,state,36,12);assert.equal(result.rows.filter((r:any)=>r.section==='Owned processes'&&r.id.startsWith('p')).length,depth+1);region=result.rowRegions.find((r:any)=>result.rows[r.index]?.id==='p'+depth);screen.handleRowClick(state,region.disclosureX,region.y,input,result);
  result=screen.renderScreen(input,state,36,12);assert.equal(result.rows.filter((r:any)=>r.id.startsWith('p')).length,12);region=result.rowRegions.find((r:any)=>result.rows[r.index]?.id==='p'+depth);
  const action=screen.handleRowClick(state,region.actionX,region.y,input,result);assert.equal(action?.type,'message');assert.ok(action.document.sections.find((s:any)=>s.id==='identity').fields.some((f:any)=>f.label==='PID'&&f.value===String(100+depth)));
  const cursor=state.cursorId;for(const [x,y]of [[1,1],[4,result.lines.length],[0,result.bodyStart+1]])assert.equal(screen.handleRowClick(state,x,y,input,result),undefined);assert.equal(state.cursorId,cursor);
 }
});
test('demo mode remains labeled on any selected child and positive small resident values do not look like measured zero',()=>{
 const input={...data,demo:true,sessions:[{...data.sessions[0],resource:{...data.sessions[0].resource,memoryBytes:'1024',availability:'known'}} ,data.sessions[1]]};const state=screen.createUiState();state.selectedKey='codex:b';let result=screen.renderScreen(input,state,80,30);assert.ok(result.lines[0].includes('[DEMO]'));state.selectedKey='codex:a';result=screen.renderScreen(input,state,80,30);assert.ok(result.rows.find((r:any)=>r.id==='memory').text.includes('1KiB'));
});
test('To-do current list age and repeat markers stay separate from first-source age and explicit Goal provenance',()=>{
 const input={...data,sessions:[{...data.sessions[0],todoStatus:'reported',todoSourceMessageId:'latest-list',todoReportedAt:5000,todos:[{id:'t',text:'Review',messageId:'first-source',latestMessageId:'latest-list',firstSeenAt:1000,checked:true,repeated:true,source:'transcript'}],history:{cpu:[1,undefined,2],memory:['1024',undefined,'2048']},evidence:{...data.sessions[0].evidence,initialRequest:{id:'original',role:'user',text:'Initial request only',timestamp:1,source:'prefix#123'},task:'Delegated work',goals:[{id:'g',objective:'Explicit objective',status:'active',source:'goal-tool',timestamp:1000}],messages:[{id:'u',role:'user',text:'Later request',timestamp:2000}]}}]};const state=screen.createUiState();state.selectedKey='codex:a';let result=screen.renderScreen(input,state,80,40,10000);const goal=result.rows.find((r:any)=>r.id==='goal');assert.equal(goal.action?.type,'message');assert.ok(goal.action.text.includes('Status: active'));assert.ok(goal.action.text.includes('Source: goal-tool'));assert.ok(goal.action.document.sections.find((s:any)=>s.id==='initial').text.includes('Initial request only'));assert.ok(result.rows.find((r:any)=>r.id==='memory').action.document.sections.flatMap((s:any)=>s.fields??[]).find((f:any)=>f.label==='History').value.includes(' '));state.tab='To-do';result=screen.renderScreen(input,state,80,30,10000);assert.ok(result.rows[0].text.includes('5s'));assert.equal(result.rows[0].action.id,'latest-list');assert.ok(result.rows[1].text.includes('repeat · locally checked'));assert.ok(result.rows[1].text.includes('9s'));assert.equal(result.rows[1].sourceId,'first-source');
});
test('Overview uses measured validated harness uptime without substituting a child or denied process',()=>{
 const process={key:'p',pid:1,startTime:'1',cpuNs:'0',rssBytes:'0',name:'harness',owner:'codex:a',isHarness:true,uptimeMs:12345,availability:'known'};const make=(processes:any[])=>({...data,sessions:[{...data.sessions[0],resource:{...data.sessions[0].resource,processes}}]});const state=screen.createUiState();state.selectedKey='codex:a';let result=screen.renderScreen(make([process]),state,80,40);assert.ok(result.rows.find((r:any)=>r.id==='process-uptime').text.includes('12.3s'));for(const unavailable of [{...process,isHarness:false},{...process,availability:'unavailable'},{...process,uptimeMs:undefined}]){result=screen.renderScreen(make([unavailable]),state,80,40);assert.ok(result.rows.find((r:any)=>r.id==='process-uptime').text.includes('Harness uptime —'));}
});
test('Messages retain explicit tool result visibility and show associated summaries without requiring expansion',()=>{
 const tool={id:'call',name:'exec_command',status:'done',summary:'Tests passed'};const messages=[{id:'assistant',role:'assistant',text:'Checking',timestamp:1,tools:[tool]},{id:'tool:call',role:'tool',text:'Tests passed',timestamp:2,tools:[tool]}];const input={...data,sessions:[{...data.sessions[0],evidence:{...data.sessions[0].evidence,messages,tools:[tool]}}]};const state=screen.createUiState();state.tab='Messages';state.selectedKey='codex:a';let result=screen.renderScreen(input,state,80,30);assert.ok(result.rows.some((r:any)=>r.id==='assistant:tool:call'&&r.text.includes('Tests passed')));assert.ok(result.rows.some((r:any)=>r.id==='tool:call'&&r.text.includes('Tool result')&&r.text.includes('codex')));const resultBody=result.rows.find((r:any)=>r.id==='tool:call');assert.equal(resultBody.action.id,'tool:call');assert.equal(resultBody.copy,'Tests passed');assert.equal(resultBody.continuations[0].text,'  Tests passed');screen.handleKey(state,'home',input,result);result=screen.renderScreen(input,state,80,30);assert.equal(screen.handleKey(state,'b',input,result)?.beforeId,'assistant');
});
test('Overview current-turn elapsed requires explicit sourced boundary and never treats a future start as measured zero',()=>{
 const make=(activeTurn:any)=>({...data,sessions:[{...data.sessions[0],evidence:{...data.sessions[0].evidence,activeTurn}}]});const state=screen.createUiState();state.selectedKey='codex:a';let result=screen.renderScreen(make({id:'t1',startedAt:1000,source:'rollout#100'}),state,80,40,4000);let row=result.rows.find((r:any)=>r.id==='process-uptime');assert.ok(row.text.includes('current turn 3s'));assert.ok(row.action.text.includes('rollout#100'));assert.ok(row.action.text.includes('1970-01-01T00:00:01.000Z'));for(const active of [undefined,{id:'t1',startedAt:5000,source:'rollout#100'},{id:'t1',startedAt:1000}]){result=screen.renderScreen(make(active),state,80,40,4000);assert.ok(result.rows.find((r:any)=>r.id==='process-uptime').text.includes('current turn —'));}
});
test('agent lineage exposes checkout badges and parent provenance while Worktrees groups repository families before checkouts',()=>{
 const git=(root:string,branch:string,family:string)=>({root,branch,familyKey:family,commonDir:family,checkoutKey:root,availability:'known',branchState:'named',sampledAt:1,ageMs:0,cwd:root});const input={...data,sessions:[{...data.sessions[0],git:git('/repo/main','main','/repo/main/.git')},{...data.sessions[1],git:git('/repo/feature','feature','/repo/main/.git'),evidence:{...data.sessions[1].evidence,parentId:'a',parentProvider:'codex',parentSource:'/sessions/root.jsonl#123'}},{...data.sessions[1],key:'codex:c',parentKey:undefined,git:git('/other/tree','other','/other/tree/.git'),evidence:{...data.sessions[1].evidence,id:'c'}}]};const state=screen.createUiState();state.tab='Agents';state.selectedKey='codex:a';let result=screen.renderScreen(input,state,100,40);const child=result.rows.find((r:any)=>r.id==='codex:b');assert.ok(child.text.includes('feature'));assert.ok(child.text.includes('feature@feature'));state.cursor=result.rows.findIndex((r:any)=>r.id==='codex:b');state.cursorId='codex:b';const action=screen.handleKey(state,'d',input,result);assert.ok(action.document.sections.find((s:any)=>s.id==='lineage').fields.some((f:any)=>f.label==='Source'&&f.value==='/sessions/root.jsonl#123'));screen.handleKey(state,'w',input,result);result=screen.renderScreen(input,state,100,40);assert.equal(result.rows.filter((r:any)=>r.id.startsWith('family:')).length,1);assert.equal(result.rows.filter((r:any)=>r.id.startsWith('checkout:')).length,2);assert.ok(result.rows.find((r:any)=>r.id.startsWith('family:')).text.includes('Repository'));assert.ok(result.rows.find((r:any)=>r.id==='checkout:/repo/feature').text.includes('feature'));assert.equal(result.numericTargets.size,2);
});
test('Overview separates current and last recorded turn tokens with coverage and reduction provenance',()=>{
 const turnUsage={turnId:'turn-2',input:12,output:3,cacheRead:4,total:15,availability:'known',coverage:{usable:2,total:2},source:'cumulative-difference',diagnostics:[]};const make=(activeTurn:any,turn=turnUsage)=>({...data,sessions:[{...data.sessions[0],usage:{...data.sessions[0].usage,turnUsage:turn},evidence:{...data.sessions[0].evidence,activeTurn,usage:[{id:'count',turnId:'turn-2',kind:'cumulative',source:'rollout#321'}]}}]});const state=screen.createUiState();state.selectedKey='codex:a';let result=screen.renderScreen(make({id:'turn-2',startedAt:1,source:'rollout#12'}),state,100,50,1000);let row=result.rows.find((r:any)=>r.id==='turn-tokens');assert.ok(row.text.includes('Current turn'));assert.ok(row.text.includes('in 12'));assert.ok(row.text.includes('out 3'));assert.ok(row.action.text.includes('2/2'));assert.ok(row.action.text.includes('cumulative-difference'));assert.ok(row.action.text.includes('rollout#321'));result=screen.renderScreen(make(undefined),state,100,50);assert.ok(result.rows.find((r:any)=>r.id==='turn-tokens').text.includes('Last recorded turn'));const unknown={turnId:'turn-3',availability:'unavailable',coverage:{usable:0,total:0},source:'unknown',diagnostics:['No explicit turn usage']} as any;result=screen.renderScreen(make({id:'turn-3',startedAt:1,source:'rollout#12'},unknown),state,100,50);row=result.rows.find((r:any)=>r.id==='turn-tokens');assert.ok(row.text.includes('Current turn'));assert.ok(row.text.includes('in —'));assert.ok(row.action.text.includes('unavailable'));
});
