import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdir,writeFile,readFile,rm,realpath} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {freshPrivateDirectory} from './helpers/private-dir.ts';
import {StateStore,identityName,processIsAbsent} from '../src/state/store.ts';
import {atomicWrite} from '../src/config/safe-file.ts';
import {loadSettings} from '../src/config/index.ts';
async function fixture(t:any,canonical=false){
 const dir=await freshPrivateDirectory(join(tmpdir(),'prism-update-'));t.after(()=>rm(dir,{recursive:true,force:true}));const root=join(dir,'new'),installed=join(dir,'installed'),configDir=canonical?join(dir,'xdg-config','herdr','plugins','config','iob.herdr-prism'):join(dir,'config'),stateDir=canonical?join(dir,'xdg-state','herdr','plugins','iob.herdr-prism'):join(dir,'state'),configPath=canonical?join(dir,'xdg-config','herdr','config.toml'):join(dir,'config.toml');await mkdir(root,{mode:0o700});await mkdir(installed,{mode:0o700});await writeFile(join(root,'package.json'),JSON.stringify({name:'herdr-prism',type:'module',version:'0.2.0'}));
 const state=new StateStore(stateDir),config=new StateStore(configDir);await state.init();await config.init();const settings='{"nativeMode":"overview","autostart":true,"follow":false,"theme":"light","extra":"preserved"}\n';await writeFile(join(configDir,'settings.json'),settings,{mode:0o600});await config.write('shortcut-preference',{enabled:false});await state.write('lifecycle',{disabled:false});await state.write('configuration',{version:1,values:[{path:'ui.sidebar.agents.rows',written:'ours'}],blocks:[],original:'old config'});await writeFile(configPath,'owned configuration\n',{mode:0o600});await writeFile(join(stateDir,'note-fixture.md'),'before flush',{mode:0o600});
 const endpoints=['socket-a','socket-b'],calls:any[]=[],registrations=new Map<string,any>(endpoints.map(endpoint=>[endpoint,{plugin_id:'iob.herdr-prism',plugin_root:installed,enabled:true,source:{kind:'github',owner:'alexiob',repo:'herdr-prism',managed_path:installed,resolved_commit:'a'.repeat(40)}}]));const snapshots=new Map<string,any>();const stores=new Map<string,StateStore>();
 for(const [i,endpoint]of endpoints.entries()){const store=new StateStore(join(stateDir,'servers',identityName(endpoint)));await store.init();await store.write('server',{endpoint});await store.write('controller',{pid:process.pid});await store.write('views',[{tabId:'tab-'+i,paneId:'panel-'+i,terminalId:'view-'+i,targetTerminalId:'native-'+i,open:i===0},{tabId:'tab-'+i,paneId:'closed-'+i,terminalId:'closed-view-'+i,targetTerminalId:'other-'+i,open:false}]);stores.set(endpoint,store);snapshots.set(endpoint,{protocol:22,focused_pane_id:i===0?'panel-'+i:'native-pane-'+i,agents:[{pane_id:'native-pane-'+i,terminal_id:'native-'+i,tab_id:'tab-'+i}],panes:[{pane_id:'native-pane-'+i,terminal_id:'native-'+i,tab_id:'tab-'+i},{pane_id:'other-pane-'+i,terminal_id:'other-'+i,tab_id:'tab-'+i},...i===0?[{pane_id:'panel-'+i,terminal_id:'view-'+i,tab_id:'tab-'+i}]:[]]});const preferences=new StateStore(join(store.dir,'views','f'.repeat(64)));await preferences.init();await preferences.write('panel-size',{columns:73,custom:true});await preferences.write('preferences',{selectedKey:'manual',pin:true,tab:'Notes'});}
 let activationFailure=false,snapshotFailure:string|undefined,offlineFailure=false,foreign=false;
 const runtime={StateStore,identityName,processIsAbsent,atomicWrite,deactivate:async()=>{calls.push(['deactivate']);await writeFile(join(stateDir,'note-fixture.md'),'draft flushed during shutdown',{mode:0o600});await config.write('settings',{nativeMode:'inspector-only',autostart:false});await state.write('lifecycle',{disabled:true});for(const [endpoint,store]of stores){await store.remove('controller');await store.write('views',(await store.read<any[]>('views'))!.map(v=>({...v,open:false})));const s=snapshots.get(endpoint);s.panes=s.panes.filter((p:any)=>!p.terminal_id.startsWith('view-'));s.focused_pane_id=s.agents[0]?.pane_id??s.panes.find((p:any)=>p.pane_id.startsWith('native-pane-')).pane_id;}return{deactivated:true,configDir,stateDir,conflicts:[]};}};
 const operations={validateSource:async()=>({version:'0.2.0'}),loadRuntime:async()=>runtime,cli:async(args:string[],ctx:any)=>{calls.push(['cli',ctx.endpoint,args]);const endpoint=ctx.endpoint??endpoints[0];if(args[0]==='status')return{stdout:JSON.stringify({running:true,socket:endpoints[0],protocol:22})};if(args[1]==='list')return{stdout:JSON.stringify({result:{type:'plugin_list',plugins:[foreign?{...registrations.get(endpoint),source:{kind:'github',owner:'foreign',repo:'other'}}:registrations.get(endpoint)]}})};if(args[1]==='enable'||args[1]==='disable'){registrations.get(endpoint)!.enabled=args[1]==='enable';return{stdout:'{}'};}throw Error('Unexpected CLI '+args.join(' '));},rpcFactory:(endpoint:string)=>({close(){},call:async(method:string,p:any)=>{calls.push(['rpc',endpoint,method,p]);if(method==='session.snapshot'){if(snapshotFailure===endpoint){const error:any=Error('snapshot denied');if(offlineFailure)error.code='ENOENT';throw error;}return{snapshot:structuredClone(snapshots.get(endpoint))};}if(method==='plugin.link'){registrations.set(endpoint,{...registrations.get(endpoint),enabled:p.enabled,source:p.source});return{};}if(method==='plugin.pane.focus'||method==='agent.focus'||method==='pane.focus'){snapshots.get(endpoint).focused_pane_id=p.pane_id??p.target;return{};}if(method==='server.reload_config')return{};throw Error('Unexpected RPC '+method);}}),activate:async(info:any)=>{calls.push(['activate',info.endpoint,info.action]);assert.equal(await readFile(join(configDir,'settings.json'),'utf8'),settings);assert.equal((await config.read<any>('shortcut-preference')).enabled,false);if(activationFailure){activationFailure=false;throw Error('new activation failed');}const store=stores.get(info.endpoint)!;const intent=(await store.read<any[]>('views'))!;const s=snapshots.get(info.endpoint);const restored=intent.map(v=>v.open?{...v,paneId:'new-'+v.paneId,terminalId:'new-'+v.terminalId,ready:true}:v);await store.write('views',restored);s.panes=[...s.panes,...restored.filter(v=>v.open).map(v=>({pane_id:v.paneId,terminal_id:v.terminalId,tab_id:v.tabId}))];await state.write('lifecycle',{disabled:false});await config.write('settings',{nativeMode:'overview',autostart:true});return{activated:true,configDir,stateDir,conflicts:[]};}};
 let replaced=false,rolledBack=false,finished=false,cancelled=false;const transaction={replace:async()=>{calls.push(['replace']);replaced=true;registrations.get(endpoints[0])!.source.resolved_commit='b'.repeat(40);registrations.get(endpoints[0])!.enabled=false;},rollback:async()=>{calls.push(['rollback']);rolledBack=true;registrations.get(endpoints[0])!.source.resolved_commit='a'.repeat(40);registrations.get(endpoints[0])!.enabled=false;},finish:async()=>{finished=true;},cancel:async()=>{cancelled=true;}};
 return{root,installed,configDir,stateDir,configPath,...canonical?{env:{XDG_CONFIG_HOME:join(dir,'xdg-config'),XDG_STATE_HOME:join(dir,'xdg-state')}}:{},settings,state,config,endpoints,stores,snapshots,calls,operations,transaction,setActivationFailure:()=>activationFailure=true,setSnapshotFailure:(e:string)=>snapshotFailure=e,setOffline:(e:string)=>{snapshotFailure=e;offlineFailure=true;},setForeign:()=>foreign=true,registrations,get replaced(){return replaced;},get rolledBack(){return rolledBack;},get finished(){return finished;},get cancelled(){return cancelled;}};
}
async function engine(){
 // @ts-ignore dependency-free installer lifecycle utility
 const module=await import('../scripts/update.mjs');assert.equal(typeof module.updatePrism,'function','shared update engine missing');return module.updatePrism;
}
test('update preserves open intent, closed panels, exact focus, settings and flushed Notes across every live server',async t=>{const f=await fixture(t),update=await engine();const result=await update(f);assert.equal(result.updated,true);assert.equal(f.finished,true);assert.equal(f.rolledBack,false);assert.equal(await readFile(join(f.configDir,'settings.json'),'utf8'),f.settings);assert.equal(await readFile(join(f.stateDir,'note-fixture.md'),'utf8'),'draft flushed during shutdown');assert.equal(f.snapshots.get('socket-a').focused_pane_id,'new-panel-0');assert.equal(f.snapshots.get('socket-b').focused_pane_id,'native-pane-1');for(const [endpoint,store]of f.stores){const views=(await store.read<any[]>('views'))!;assert.equal(views[1].open,false);assert.equal(views[0].open,endpoint==='socket-a');const preferences=new StateStore(join(store.dir,'views','f'.repeat(64)));assert.deepEqual(await preferences.read('panel-size'),{columns:73,custom:true});assert.deepEqual(await preferences.read('preferences'),{selectedKey:'manual',pin:true,tab:'Notes'});}assert.ok(f.calls.findIndex(c=>c[0]==='deactivate')<f.calls.findIndex(c=>c[0]==='replace'));assert.equal(f.calls.filter(c=>c[0]==='activate').length,2);assert.equal(f.registrations.get('socket-b')!.source.resolved_commit,'b'.repeat(40));});
test('foreign registrations and unsnapshottable live servers are rejected before stopping or replacing',async t=>{const update=await engine();for(const kind of ['foreign','snapshot']){const f=await fixture(t);if(kind==='foreign')f.setForeign();else f.setSnapshotFailure('socket-b');await assert.rejects(update(f),/foreign|snapshot|unsupported/i);assert.equal(f.replaced,false);assert.equal(f.calls.some(c=>c[0]==='deactivate'),false);assert.equal(f.cancelled,true);}});
test('activation failure rolls code and settings back, restores panels and focus, and retains shutdown-flushed Notes',async t=>{const f=await fixture(t),update=await engine();f.setActivationFailure();await assert.rejects(update(f),/activation failed|update failed/i);assert.equal(f.rolledBack,true);assert.equal(f.finished,true);assert.equal(await readFile(join(f.configDir,'settings.json'),'utf8'),f.settings);assert.equal(await readFile(join(f.stateDir,'note-fixture.md'),'utf8'),'draft flushed during shutdown');assert.equal(f.snapshots.get('socket-a').focused_pane_id,'new-panel-0');assert.equal(f.registrations.get('socket-b')!.source.resolved_commit,'a'.repeat(40));assert.equal((await f.state.read<any>('update-recovery')).phase,'rolled-back');});
test('an intentionally deactivated or disabled installation is replaced without activation',async t=>{const f=await fixture(t),update=await engine();await f.state.write('lifecycle',{disabled:true});f.registrations.forEach(r=>r.enabled=false);for(const [endpoint,store]of f.stores){await store.write('views',(await store.read<any[]>('views'))!.map(v=>({...v,open:false})));const snapshot=f.snapshots.get(endpoint);snapshot.panes=snapshot.panes.filter((p:any)=>!p.terminal_id.startsWith('view-'));snapshot.focused_pane_id=snapshot.agents[0].pane_id;}const result=await update(f);assert.equal(result.updated,true);assert.equal(f.calls.some(c=>c[0]==='activate'),false);assert.deepEqual(await f.state.read('lifecycle'),{disabled:true});assert.equal(f.registrations.get('socket-a')!.enabled,false);});
test('a prepared transaction rolls back even if replacement throws after changing files',async t=>{const f=await fixture(t),update=await engine();f.transaction.replace=async()=>{f.calls.push(['replace']);throw Error('partial replacement failed');};await assert.rejects(update(f),/partial replacement failed|update failed/i);assert.equal(f.rolledBack,true);assert.equal(f.calls.some(c=>c[0]==='activate'),true);});
test('finite rollback activation uses the old installed collector and panel code with reviewed lifecycle handling',async t=>{
 const f=await fixture(t);for(const sub of ['runtime','herdr'])await mkdir(join(f.installed,'dist',sub),{recursive:true});await mkdir(join(f.root,'dist/runtime'),{recursive:true});await writeFile(join(f.installed,'package.json'),'{"type":"module"}');
 await writeFile(join(f.installed,'dist/runtime/service.js'),'export async function serviceContext(){return {endpoint:"fixture"};}');await writeFile(join(f.installed,'dist/herdr/client.js'),'export class HerdrClient {close(){}}');
 await writeFile(join(f.installed,'dist/runtime/collector-service.js'),`export async function openTabPanel(_c,target){return {runtime:${JSON.stringify(f.installed)},target};}export async function ensureCollectorService(){return {runtime:${JSON.stringify(f.installed)}};}`);
 await writeFile(join(f.root,'dist/runtime/lifecycle.js'),'export async function activate(context,rpc,options){return {opened:await options.openView("owner-pane"),collector:await options.ensureCollector(),restoreViewsOnly:options.restoreViewsOnly,mode:options.mode};}');
 // @ts-ignore dependency-free recovery subprocess helper
 const {activateRestoredPrism}=await import('../scripts/update-activate.mjs');const result=await activateRestoredPrism({runtimeRoot:f.installed,lifecycleRoot:f.root,mode:'inspector-only'});assert.equal(result.opened.runtime,f.installed);assert.equal(result.opened.target,'owner-pane');assert.equal(result.collector.runtime,f.installed);assert.equal(result.restoreViewsOnly,true);assert.equal(result.mode,'inspector-only');
});
test('an enabled server with no prior collector or open panels stays inactive during an update',async t=>{const f=await fixture(t),update=await engine();await f.stores.get('socket-b')!.remove('controller');await update(f);assert.deepEqual(f.calls.filter(c=>c[0]==='activate').map(c=>c[1]),['socket-a']);});
test('a stopped recorded server retains remembered open panels without blocking an update or starting a collector',async t=>{const f=await fixture(t),update=await engine();const store=f.stores.get('socket-b')!;await store.remove('controller');const views=(await store.read<any[]>('views'))!;views[0].open=true;await store.write('views',views);f.setOffline('socket-b');await update(f);assert.equal((await store.read<any[]>('views'))![0].open,true);assert.deepEqual(f.calls.filter(c=>c[0]==='activate').map(c=>c[1]),['socket-a']);});
test('a deactivated installation retains remembered open intent even though its plugin panes are absent',async t=>{const f=await fixture(t),update=await engine();await f.state.write('lifecycle',{disabled:true});for(const [endpoint,store]of f.stores){await store.remove('controller');const snapshot=f.snapshots.get(endpoint);snapshot.panes=snapshot.panes.filter((p:any)=>!p.terminal_id.startsWith('view-'));snapshot.focused_pane_id=snapshot.agents[0].pane_id;}await update(f);assert.equal(f.calls.some(c=>c[0]==='activate'),false);assert.equal((await f.stores.get('socket-a')!.read<any[]>('views'))![0].open,true);});
test('cleanup failure after verified activation stays updated and reports only concrete recovery paths',async t=>{const f=await fixture(t),update=await engine();(f.transaction as any).recovery={backup:join(f.installed,'old-backup'),prepared:f.root,lock:join(f.installed,'update.lock'),token:'fixture-secret'};f.transaction.finish=async()=>{throw Error('cleanup denied');};const result=await update(f);assert.equal(result.updated,true);assert.equal(result.cleanupPending,true);assert.equal(result.recovery.journal,join(f.stateDir,'update-recovery.json'));assert.equal(result.recovery.backup,join(f.installed,'old-backup'));assert.equal(result.recovery.token,undefined);assert.equal(f.rolledBack,false);assert.equal((await f.state.read<any>('update-recovery')).phase,'complete');});
test('a missing reviewed recovery helper cancels preparation before any shutdown',async t=>{const f=await fixture(t),update=await engine();(f.operations as any).activate=undefined;await assert.rejects(update(f),/ENOENT|update-activate/);assert.equal(f.calls.some(c=>c[0]==='deactivate'),false);assert.equal(f.cancelled,true);});
test('an installation with only stopped recorded servers updates without clearing remembered visibility or starting collectors',async t=>{
 const f=await fixture(t),update=await engine();for(const store of f.stores.values())await store.remove('controller');const cli=f.operations.cli;f.operations.cli=async(args,ctx)=>args[0]==='status'?{stdout:JSON.stringify({running:false})}:cli(args,ctx);
 f.operations.rpcFactory=endpoint=>({close(){},call:async()=>{const error:any=Error('connect ENOENT '+endpoint);error.code='ENOENT';throw error;}});
 const result=await update(f);assert.equal(result.updated,true);assert.equal(result.servers,0);assert.equal(f.calls.some(c=>c[0]==='deactivate'||c[0]==='activate'),false);assert.equal((await f.stores.get('socket-a')!.read<any[]>('views'))![0].open,true);assert.equal(await readFile(join(f.stateDir,'note-fixture.md'),'utf8'),'before flush');
});
test('plain shell focus is left alone when exact and restored with pane.focus after activation moves it',async t=>{
 const update=await engine();for(const moveFocus of [false,true]){const f=await fixture(t);f.snapshots.get('socket-b').agents=[];const rpcFactory=f.operations.rpcFactory;f.operations.rpcFactory=endpoint=>{const rpc=rpcFactory(endpoint);return{close:rpc.close,call:async(method,p)=>{if(method==='agent.focus'&&endpoint==='socket-b')throw Error('not an agent');if(method==='pane.focus'){f.calls.push(['rpc',endpoint,method,p]);f.snapshots.get(endpoint).focused_pane_id=p.pane_id;return{};}return rpc.call(method,p);}};};if(moveFocus){const activate=f.operations.activate;f.operations.activate=async info=>{const value=await activate(info);if(info.endpoint==='socket-b')f.snapshots.get('socket-b').focused_pane_id='other-pane-1';return value;};}await update(f);assert.equal(f.snapshots.get('socket-b').focused_pane_id,'native-pane-1');assert.equal(f.calls.some(c=>c[0]==='rpc'&&c[1]==='socket-b'&&c[2]==='pane.focus'),moveFocus);}
});
test('cleanup failure after verified rollback reports retained recovery paths without undoing the recovery',async t=>{const f=await fixture(t),update=await engine();(f.transaction as any).recovery={backup:join(f.installed,'old-backup'),lock:join(f.installed,'replacement.lock')};f.setActivationFailure();f.transaction.finish=async()=>{throw Error('cleanup denied');};await assert.rejects(update(f),error=>{assert.match(String(error),/original code and panel state restored/);assert.match(String(error),/cleanup pending/);assert.ok(String(error).includes(join(f.stateDir,'update-recovery.json')));assert.ok(String(error).includes(join(f.installed,'replacement.lock')));return true;});assert.equal(f.rolledBack,true);assert.equal(f.snapshots.get('socket-a').focused_pane_id,'new-panel-0');const journal=await f.state.read<any>('update-recovery');assert.equal(journal.phase,'rolled-back');assert.equal(journal.cleanupPending,true);});
test('invalid typed saved settings are rejected before stopping collectors or replacing code',async t=>{
 const update=await engine();for(const invalid of [{sampleIntervalMs:'invalid'},{providerHomes:['invalid']}]){const f=await fixture(t),runtime=f.operations.loadRuntime;f.operations.loadRuntime=async()=>({...await runtime(),loadSettings});const raw=JSON.stringify({...JSON.parse(f.settings),...invalid});await writeFile(join(f.configDir,'settings.json'),raw);await assert.rejects(update(f),/Invalid sampleIntervalMs|Invalid providerHomes/);assert.equal(f.calls.some(c=>c[0]==='deactivate'||c[0]==='replace'),false);assert.equal(f.cancelled,true);assert.equal(await readFile(join(f.configDir,'settings.json'),'utf8'),raw);assert.equal(await readFile(join(f.stateDir,'note-fixture.md'),'utf8'),'before flush');}
});

async function managed(f:any){const receipt={version:1,pluginId:'iob.herdr-prism',token:'7be882db-3ce7-482b-a760-1b47e3bda581',installRoot:await realpath(f.installed),sourceRoot:f.root,configDir:f.configDir,stateDir:f.stateDir};await writeFile(join(f.installed,'.hat-managed-install.json'),JSON.stringify(receipt),{mode:0o600});const marker={version:1,pluginId:receipt.pluginId,token:receipt.token,installRoot:receipt.installRoot};for(const dir of [f.configDir,f.stateDir])await writeFile(join(dir,'.hat-lifecycle-owner.json'),JSON.stringify(marker),{mode:0o600});return {receipt,marker};}
test('foreign plugin environment namespace is ignored while canonical Prism state is preserved',async t=>{
 const f=await fixture(t,true),update=await engine(),foreignConfig=join(f.root,'foreign-config'),foreignState=join(f.root,'foreign-state');await mkdir(foreignConfig);await mkdir(foreignState);await writeFile(join(foreignConfig,'settings.json'),'{"nativeMode":"inspector-only","foreign":true}');await writeFile(join(foreignState,'lifecycle.json'),'{"disabled":true,"foreign":true}');const result=await update({...f,configDir:undefined,stateDir:undefined,env:{...f.env,HERDR_PLUGIN_ID:'foreign.plugin',HERDR_PLUGIN_CONFIG_DIR:foreignConfig,HERDR_PLUGIN_STATE_DIR:foreignState}});assert.equal(result.configDir,f.configDir);assert.equal(result.stateDir,f.stateDir);assert.equal(await readFile(join(foreignConfig,'settings.json'),'utf8'),'{"nativeMode":"inspector-only","foreign":true}');assert.equal(await readFile(join(foreignState,'lifecycle.json'),'utf8'),'{"disabled":true,"foreign":true}');assert.equal(f.calls.filter(c=>c[0]==='activate').length,2);const journal=await f.state.read<any>('update-recovery');assert.ok(journal.servers.every((server:any)=>server.dir.startsWith(f.stateDir)));assert.equal(await readFile(join(f.configDir,'settings.json'),'utf8'),f.settings);
});
test('matching managed namespace owner markers are accepted for local and GitHub registrations',async t=>{const update=await engine();for(const kind of ['local','github']){const f=await fixture(t);await managed(f);if(kind==='local')f.registrations.forEach(r=>r.source={kind:'local',path:f.installed});assert.equal((await update(f)).updated,true);assert.equal(f.cancelled,false);}});
test('missing or mismatched managed namespace owner markers reject before shutdown and replacement',async t=>{const update=await engine();for(const dirKey of ['configDir','stateDir'] as const)for(const mode of ['missing','mismatch']){const f=await fixture(t),{marker}=await managed(f);const path=join(f[dirKey],'.hat-lifecycle-owner.json');if(mode==='missing')await rm(path);else await writeFile(path,JSON.stringify({...marker,token:'foreign-token'}));await assert.rejects(update(f),/owner|ownership|ENOENT/i);assert.equal(f.calls.some(c=>c[0]==='deactivate'||c[0]==='replace'),false);assert.equal(f.cancelled,true);assert.equal(await readFile(join(f.stateDir,'note-fixture.md'),'utf8'),'before flush');}});
test('an invalid existing managed receipt on a GitHub installation is rejected before shutdown',async t=>{const f=await fixture(t),update=await engine();await writeFile(join(f.installed,'.hat-managed-install.json'),JSON.stringify({version:1,pluginId:'foreign.plugin',token:'foreign-secret'}));await assert.rejects(update(f),/receipt|ownership/i);assert.equal(f.calls.some(c=>c[0]==='deactivate'||c[0]==='replace'),false);assert.equal(f.cancelled,true);});
