export type Provider = 'codex' | 'claude' | 'pi' | string;
export type Availability = 'known' | 'unavailable' | 'partial' | 'stale' | 'not_applicable';
export interface ToolCall { id: string; name: string; status: 'running' | 'done' | 'error' | 'unknown'; summary?: string; timestamp?: number; editedPaths?: string[]; }
export interface Message { id: string; role: 'user' | 'assistant' | 'tool'; kind?: 'inter-agent'; author?: string; recipient?: string; text: string; timestamp?: number; cwd?: string; tools?: ToolCall[]; source?: string; complete?: boolean; }
export interface TokenCounters { input?: number; output?: number; cacheRead?: number; cacheWrite?: number; reasoning?: number; total?: number; cacheSemantics?: 'subset' | 'separate' | 'unknown'; }
export interface UsageRecord extends TokenCounters { id: string; sessionId?: string; turnId?: string; requestId?: string; model?: string; timestamp?: number; kind: 'delta' | 'cumulative'; turnCounters?: TokenCounters; contextUsed?: number; contextLimit?: number; generationMs?: number; turnMs?: number; includesChildren?: boolean; epoch?: string; source?: string; }
export interface GoalRecord { id: string; objective: string; status?: string; timestamp?: number; source?: string; }
export interface SessionEvidence { contentRevision?:string; activeTurn?:{id?:string;startedAt:number;source?:string};initialRequest?:Message;id: string; provider: Provider; path?: string; cwd?: string; title?: string; model?: string; parentId?: string; parentProvider?: Provider; parentSource?: string; task?: string; state?: string; startedAt?: number; lastActivity?: number; messages: Message[]; tools: ToolCall[]; usage: UsageRecord[]; goals: GoalRecord[]; availability: Availability; reason?: string; diagnostics?: string[]; }
export interface ProcessSample { uptimeMs?:number;pid: number; ppid?: number; startTime: string; cpuNs: string; rssBytes: string; name: string; threads?: number; readBytes?: string; writeBytes?: string; availability?: Availability; }
export interface SampleBatch { version?: number; platform: string; bootId: string; sampledAt: number; monotonicNs: string; processes: ProcessSample[]; errors?: string[]; }
export interface HerdrSessionRef { source: string; agent: string; kind: 'id' | 'path'; value: string; }
export interface HerdrAgent { pane_id: string; terminal_id: string; workspace_id: string; tab_id: string; agent?: string | null; display_agent?: string | null; name?: string | null; agent_status: string | { state?: string; status?: string; [key: string]: unknown }; agent_session?: HerdrSessionRef | null; cwd?: string | null; foreground_cwd?: string | null; focused: boolean; revision: number; tokens?: Record<string,string>; [key: string]: unknown; }
export interface HerdrSnapshot { version: string; protocol: number; focused_pane_id?: string | null; focused_tab_id?: string | null; focused_workspace_id?: string | null; agents: HerdrAgent[]; panes: Record<string,unknown>[]; tabs: Record<string,unknown>[]; workspaces: Record<string,unknown>[]; layouts: Record<string,unknown>[]; }
export interface DashboardSession { key: string; evidence: SessionEvidence; attachment?: HerdrAgent;attachments?:HerdrAgent[]; parentKey?: string; depth: number; children: string[]; parentIssue?: string; historical?: boolean; }
export interface Forest { nodes: Map<string,DashboardSession>; order: DashboardSession[]; diagnostics: string[]; }
export interface Rpc { call<T = any>(method: string, params?: Record<string,unknown>): Promise<T>; }
