/** Bounded syntax-preserving scanner. Values stay opaque; only assignment ranges are edited. */
export interface Entry {path:string;tablePath:string;start:number;end:number;valueStart:number;valueEnd:number;value:string;}
export interface Table {path:string;start:number;end:number;bodyEnd:number;}
export interface Document {entries:Entry[];tables:Table[];}
function escaped(text:string,index:number){let n=0;for(let i=index-1;i>=0&&text[i]==='\\';i--)n++;return n%2===1;}
function canonical(parts:string[]){return parts.map(p=>/^[A-Za-z0-9_-]+$/.test(p)?p:JSON.stringify(p)).join('.');}
function dotted(text:string):string[]{const parts:string[]=[];let i=0;while(i<text.length){while(/\s/.test(text[i]??'')&&i<text.length)i++;let value='';if(text[i]==='"'||text[i]==="'"){const quote=text[i++];const start=i-1;while(i<text.length){if(text[i]===quote&& (quote==="'"||!escaped(text,i)))break;i++;}if(i>=text.length)throw new Error('Unterminated TOML key');const raw=text.slice(start,++i);value=quote==='"'?JSON.parse(raw):raw.slice(1,-1);}else{const match=/^[A-Za-z0-9_-]+/.exec(text.slice(i));if(!match)throw new Error('Unsupported TOML key');value=match[0];i+=value.length;}parts.push(value);while(/\s/.test(text[i]??'')&&i<text.length)i++;if(i===text.length)break;if(text[i++]!=='.')throw new Error('Malformed TOML dotted key');}return parts;}
export function scanToml(text:string):Document {
 if(Buffer.byteLength(text)>2*1024*1024)throw new Error('Configuration exceeds 2 MiB limit');const entries:Entry[]=[];const tables:Table[]=[];let table:string[]=[];let pos=0;let lastTable:Table|undefined;const seen=new Set<string>();const arrays=new Map<string,number>();
 while(pos<text.length){const start=pos;let end=text.indexOf('\n',pos);if(end<0)end=text.length;else end++;const line=text.slice(pos,end);const trimmed=line.trimStart();if(!trimmed||trimmed.startsWith('#')||trimmed.trim()===''){pos=end;continue;}
 if(trimmed.startsWith('[')){const array=trimmed.startsWith('[[');let quote='';let close=-1;for(let i=array?2:1;i<trimmed.length;i++){const c=trimmed[i];if(quote){if(c===quote&&(quote==="'"||!escaped(trimmed,i)))quote='';}else if(c==='"'||c==="'")quote=c;else if(c===']'){close=i;break;}}if(close<0)throw new Error('Malformed TOML table');const tail=trimmed.slice(close+(array?2:1)).trim();if(tail&&!tail.startsWith('#'))throw new Error('Malformed TOML table suffix');table=dotted(trimmed.slice(array?2:1,close));const base=canonical(table);if(array){const n=arrays.get(base)??0;arrays.set(base,n+1);table[table.length-1]+='#'+n;}const path=canonical(table);if(!array&&seen.has(path))throw new Error('Duplicate TOML table '+path);if(!array)seen.add(path);if(lastTable)lastTable.bodyEnd=start;lastTable={path,start,end,bodyEnd:text.length};tables.push(lastTable);pos=end;continue;}
 let quote='';let equal=-1;for(let i=0;i<line.length;i++){const c=line[i];if(quote){if(c===quote&&(quote==="'"||!escaped(line,i)))quote='';}else if(c==='"'||c==="'")quote=c;else if(c==='='){equal=i;break;}}if(equal<0)throw new Error('Malformed TOML assignment');const keys=dotted(line.slice(0,equal).trim());let valueStart=start+equal+1;while(text[valueStart]===' '||text[valueStart]==='\t')valueStart++;let i=valueStart,depth=0,mode='',valueEnd=-1;for(;i<text.length;i++){const c=text[i];if(mode){if(mode.length===3){if(text.startsWith(mode,i)&&!(mode==='"""'&&escaped(text,i))){i+=2;mode='';}}else if(c===mode&&(mode==="'"||!escaped(text,i)))mode='';else if(c==='\n')throw new Error('Unterminated TOML string');continue;}if(c==='"'||c==="'"){mode=text.startsWith(c.repeat(3),i)?c.repeat(3):c;if(mode.length===3)i+=2;}else if(c==='['||c==='{')depth++;else if(c===']'||c==='}') {depth--;if(depth<0)throw new Error('Malformed TOML value');}else if(c==='#'){if(depth===0){valueEnd=i;while(i<text.length&&text[i]!=='\n')i++;break;}while(i<text.length&&text[i]!=='\n')i++;}else if(c==='\n'&&depth===0){valueEnd=i;break;}}
 if(mode||depth)throw new Error('Incomplete TOML value');if(valueEnd<0)valueEnd=i;while(valueEnd>valueStart&&/\s/.test(text[valueEnd-1]))valueEnd--;let assignmentEnd=text.indexOf('\n',i);if(assignmentEnd<0)assignmentEnd=text.length;else assignmentEnd++;const path=canonical([...table,...keys]);if(entries.some(e=>e.path===path))throw new Error('Duplicate TOML key '+path);entries.push({path,tablePath:canonical(table),start,end:assignmentEnd,valueStart,valueEnd,value:text.slice(valueStart,valueEnd)});pos=assignmentEnd;
 }
 return {entries,tables};
}
export function replaceValues(text:string,edits:Array<{start:number;end:number;text:string}>){for(const edit of [...edits].sort((a,b)=>b.start-a.start))text=text.slice(0,edit.start)+edit.text+text.slice(edit.end);scanToml(text);return text;}
export function put(text:string,path:string,value:string):string {const doc=scanToml(text);const entry=doc.entries.find(e=>e.path===path);if(entry)return replaceValues(text,[{start:entry.valueStart,end:entry.valueEnd,text:value}]);const dot=path.lastIndexOf('.'),table=path.slice(0,dot),key=path.slice(dot+1);const found=doc.tables.find(t=>t.path===table);if(!found&&doc.entries.some(e=>e.path===table||table.startsWith(e.path+'.')||e.path.startsWith(table+'.')&&(e.tablePath===''||table.startsWith(e.tablePath+'.'))))throw new Error('Unsupported existing TOML topology for '+table+'; choose inspector-only or use explicit tables');if(found)return replaceValues(text,[{start:found.bodyEnd,end:found.bodyEnd,text:`${text[found.bodyEnd-1]==='\n'?'':'\n'}${JSON.stringify(key)} = ${value}\n`}]);return replaceValues(text,[{start:text.length,end:text.length,text:`${text.length&&text.endsWith('\n')?'':'\n'}[${table}]\n${JSON.stringify(key)} = ${value}\n`}]);}
