import{mkdtemp,mkdir,writeFile,rm}from'node:fs/promises';import os from'node:os';import path from'node:path';import{execFile}from'node:child_process';import{promisify}from'node:util';import{performance}from'node:perf_hooks';import{fileURLToPath}from'node:url';
const root=fileURLToPath(new URL('..',import.meta.url));const exec=promisify(execFile);const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const secondsOption=process.argv.indexOf('--seconds');const seconds=Number(secondsOption>=0?process.argv[secondsOption+1]:20);if(!Number.isFinite(seconds)||seconds<5||seconds>120)throw Error('Profile --seconds must be 5–120');
const{Collector}=await import(path.join(root,'dist/runtime/collector.js'));const{renderScreen,createUiState,handleKey}=await import(path.join(root,'dist/tui/screen.js'));
const directory=await mkdtemp(path.join(os.tmpdir(),'hat-profile-'));let collector;
try{
 const cwd=path.join(directory,'checkout'),provider=path.join(directory,'codex');await mkdir(cwd);await mkdir(path.join(provider,'sessions'),{recursive:true});await exec('git',['init','-q'],{cwd});await writeFile(path.join(cwd,'README.md'),'profile fixture\n');await exec('git',['add','README.md'],{cwd});await exec('git',['-c','user.name=Profile','-c','user.email=profile@example.invalid','commit','-qm','fixture'],{cwd});
 const agents=[],processes=[];let historyBytes=0;const body='Fixture monitoring text '+ 'x'.repeat(1000);
 for(let i=0;i<50;i++){const id=`profile-${String(i).padStart(2,'0')}`;const lines=[JSON.stringify({type:'session_meta',payload:{id,cwd,source:'cli'}})];for(let j=0;j<1800;j++)lines.push(JSON.stringify({type:'response_item',payload:{type:'message',id:`m-${j}`,role:j%2?'assistant':'user',channel:'final',content:[{type:'output_text',text:body}]}}));const text=lines.join('\n')+'\n';historyBytes+=Buffer.byteLength(text);await writeFile(path.join(provider,'sessions',id+'.jsonl'),text);agents.push({pane_id:`p${i}`,terminal_id:`t${i}`,workspace_id:'w',tab_id:'tab',agent:'codex',agent_session:{kind:'id',value:id},cwd,focused:i===0,agent_status:'idle',revision:1});for(let j=0;j<10;j++)processes.push({pid:1000+i*10+j,ppid:j?1000+i*10:1,startTime:'1',cpuNs:'0',rssBytes:'1048576',name:j?'fixture-job':'codex',availability:'known'});}
 global.gc?.();const baseline=process.memoryUsage();const snapshot={protocol:22,agents,panes:agents,tabs:[],workspaces:[],layouts:[]};const rpc={call:async(method,params)=>method==='session.snapshot'?{snapshot}:method==='agent.get'?{agent:agents.find(a=>a.pane_id===params.target)}:method==='pane.get'?{pane:agents.find(a=>a.pane_id===params.pane_id)}:method==='pane.process_info'?{process_info:{foreground_processes:[{pid:1000+Number(params.pane_id.slice(1))*10,name:'codex'}]}}:{}};const sampler={sample:async()=>({platform:'fixture',bootId:'profile',sampledAt:Date.now(),monotonicNs:process.hrtime.bigint().toString(),processes}),close:async()=>{}};
 collector=new Collector({paneOpen:true,visibleSession:"codex:profile-00",rpc,sampler,stateDir:path.join(directory,'state'),settings:{nativeMode:'inspector-only',providerHomes:{codex:provider,claude:path.join(directory,'absent-claude'),pi:path.join(directory,'absent-pi')},todosEnabled:false,sampleIntervalMs:2000,follow:true,ascii:false,monochrome:true}});
 const startup=performance.now();await collector.start();const startupMs=performance.now()-startup;global.gc?.();const initial=process.memoryUsage(),cpu=process.cpuUsage(),start=performance.now();await sleep(seconds*1000);const wallMs=performance.now()-start,cpuUse=process.cpuUsage(cpu),keyboard=[];
 const state=createUiState();state.selectedKey=collector.data.sessions[0]?.key;for(const tab of ['Overview','Agents','Processes','Messages','Refs','To-do']){state.tab=tab;for(let i=0;i<50;i++){const before=performance.now();const screen=renderScreen(collector.data,state,80,24);handleKey(state,i%2?'up':'down',collector.data,screen);renderScreen(collector.data,state,80,24);keyboard.push(performance.now()-before);}}
 keyboard.sort((a,b)=>a-b);const result={kind:'collector-profile',boundary:'Real filesystem/provider/Git and Node CPU; synthetic Herdr RPC and 500-process OS batches; excludes helper/Git-child CPU and real terminal latency',agents:50,processes:500,selectedSessions:1,paneOpen:true,historyBytes,startupMs,measuredSeconds:wallMs/1000,nodeCpuPercent:(cpuUse.user+cpuUse.system)/1000/wallMs*100,heapIncreaseMiB:(initial.heapUsed-baseline.heapUsed)/1048576,rssIncreaseMiB:(initial.rss-baseline.rss)/1048576,keyboardRenderP95Ms:keyboard[Math.floor(keyboard.length*.95)],budgets:{idleCpuBelowOnePercent:(cpuUse.user+cpuUse.system)/1000/wallMs*100<1,heapIncreaseBelow150MiB:(initial.heapUsed-baseline.heapUsed)<150*1048576,keyboardRenderP95Below100Ms:keyboard[Math.floor(keyboard.length*.95)]<100}};console.log(JSON.stringify(result,null,2));
}finally{await collector?.close();await rm(directory,{recursive:true,force:true});}
